### ISSUE TITLE
Cannot destructure property 'underline' of 'chalk_1.default' as it is undefined.

### ISSUE THREAD

**Issue by jmogenahalli2021** [forcedotcom/cli#1021]
I have installed sfdx cli with my new laptop, when I try open my default org or any CLI Command, will throw error, can some one look in to this please?
here is log info.

`TypeError: Cannot destructure property 'underline' of 'chalk_1.default' as it is undefined.
    at Object.<anonymous> (C:\Program Files (x86)\sfdx\client\node_modules\@oclif\plugin-help\lib\command.js:8:9)
    at Module._compile (C:\Program Files (x86)\sfdx\client\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\Program Files (x86)\sfdx\client\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Program Files (x86)\sfdx\client\node_modules\@oclif\plugin-help\lib\index.js:7:19)
    at Module._compile (C:\Program Files (x86)\sfdx\client\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
`

<

!--
NOTICE: GitHub is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels.
-->

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by mshanemc** [comment]
Can you please follow the issue template so we can see the versions of the plugins that you have installed?  That helps us know where to look.

Also, try running your command with `--dev-debug` and share the output so we can see exactly where it's breaking

**Comment by jmogenahalli2021** [comment]
I noticed this error in both VS Code and Illuminated Cloud 2 but have also isolated it to the command-line. When I run: 
 
**Steps To Reproduce:**
Step 1 : type command ` sfdx force:org:list `

**Expected result:**
show the list of available org

**Actual result:**
`TypeError: Cannot destructure property 'underline' of 'chalk_1.default' as it is undefined.
    at Object.<anonymous> (C:\Program Files (x86)\sfdx\client\node_modules\@oclif\plugin-help\lib\command.js:8:9)
    at Module._compile (C:\Program Files (x86)\sfdx\client\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\Program Files (x86)\sfdx\client\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Program Files (x86)\sfdx\client\node_modules\@oclif\plugin-help\lib\index.js:7:19)
    at Module._compile (C:\Program Files (x86)\sfdx\client\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)`

**Additional information:**
any sfdx command will end up error as above. I have reinstalled VSCode, SFDX Cli and Node.js
using `--dev-debug` didn't make any difference.

**Comment by mshanemc** [comment]
> SFDX CLI Version(to find the version of the CLI engine run sfdx --version):
> SFDX plugin Version(to find the version of the CLI plugin run sfdx plugins --core)

**Comment by jmogenahalli2021** [comment]
> sfdx plugins --core

any sfdx command will end up same output, can't use 'sfdx ' commands at all
I have downloaded and installed sfdx cli from https://developer.salesforce.com/tools/sfdxcli this morning.
SFDX CLI Installed version v51.13.0

**Comment by mshanemc** [comment]
I just did the install from that same url, on a windows box, with no issues (windows x64).

**Comment by mshanemc** [comment]
If you've got anything else I could try, let me know.

**Comment by sandyvis34** [comment]
any update on this issue, i am facing the same issue repeatedly

**Comment by shetzel** [comment]
@sandyvis34 - there won't be any update on this closed issue without additional information which includes the required information from the template and reproducible steps.
