### ISSUE TITLE
Plugin test doesn't seem to clean up after itself (sinon error "Attempted to wrap request which is already wrapped")

### ISSUE THREAD

**Issue by fransflippo** [forcedotcom/cli#1082]
### Summary

I wrote a plugin which has a test suite consisting of
- an integration test for the command which is based on the generated fancy-test test (e.g. `test.withOrg` etc.)
- some unit test for helpers, some of which interact with the sfdx Connection which use sinon to stub that Connection

When I run either the fancy-test based integration test separately, or my helper tests separately, everything seems fine. But when I run the whole test suite, the command test runs first (and passes), but then as soon as my helper tests try to stub something on `Connection`, I get:

    TypeError: Attempted to wrap request which is already wrapped
          at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:48:21)
          at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:111:13)
          at stub (node_modules/sinon/lib/sinon/stub.js:123:44)
          at /Users/frans/workspaces/salesforce/sfdx-ci-plugin/node_modules/sinon/lib/sinon/util/core/walk-object.js:33:17
          at /Users/frans/workspaces/salesforce/sfdx-ci-plugin/node_modules/sinon/lib/sinon/util/core/walk.js:27:22
          at Array.forEach (<anonymous>)
          at walkInternal (node_modules/sinon/lib/sinon/util/core/walk.js:19:5)
          at walkInternal (node_modules/sinon/lib/sinon/util/core/walk.js:33:9)
          at walk (node_modules/sinon/lib/sinon/util/core/walk.js:48:12)
          at walkObject (node_modules/sinon/lib/sinon/util/core/walk-object.js:18:5)
          at stub (node_modules/sinon/lib/sinon/stub.js:96:16)
          at stub.createStubInstance (node_modules/sinon/lib/sinon/stub.js:131:25)
          at Sandbox.createStubInstance (node_modules/sinon/lib/sinon/sandbox.js:55:52)
          at ( my code which does const connectionStub = sinon.createStubInstance(Connection); )
          at processImmediate (node:internal/timers:463:21)
      --------------
      Error: Stack Trace for original
          at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:139:26)
          at Function.stub (node_modules/sinon/lib/sinon/stub.js:123:44)
          at Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:369:37)
          at Object.stubMethod (node_modules/@salesforce/ts-sinon/lib/index.js:60:20)
          at Object.stubContext (node_modules/@salesforce/core/lib/testSetup.js:233:16)
          at Context.<anonymous> (node_modules/@salesforce/core/lib/testSetup.js:275:17)
          at processImmediate (node:internal/timers:463:21)

### Steps To Reproduce:

1. Generate a new plugin called **sfdx-plugin-sinon-error**: `sfdx plugins:generate sfdx-plugin-sinon-error --defaults`
1. `cd sfdx-plugin-sinon-error`
1. Run `npm install`
1. Run `yarn remove @types/node && yarn add @types/jsforce -D && yarn prepack` as per https://github.com/forcedotcom/cli/issues/1038#issuecomment-856802846
1. Add `@salesforce/ts-sinon` because somehow it isn't there: `yarn add --dev @salesforce/ts-sinon`
1. Add a trivial test that just stubs `Connection`:

       mkdir -p test/helpers && cat <<EOF >test/helpers/test-connection-stubbing.test.ts
       import {Connection} from '@salesforce/core';
       import {expect} from 'chai';
       import sinon = require('sinon');
       describe('Test stubbing Connection', () => {
         it('should be able to stub Connection', async () => {
           const connectionStub = sinon.createStubInstance(Connection);
           expect(connectionStub).to.not.be.null;
         });
       });
       EOF
1. Run `TZ=Z npm test`

Or just paste the following into a file and run it with `sh`:

    #!/bin/sh
    sfdx plugins:generate sfdx-plugin-sinon-error --defaults
    cd sfdx-plugin-sinon-error
    npm install
    yarn remove @types/node && yarn add @types/jsforce -D && yarn prepack
    yarn add --dev @salesforce/ts-sinon
    mkdir -p test/helpers && cat <<EOF >test/helpers/test-connection-stubbing.test.ts
    import {Connection} from '@salesforce/core';
    import {expect} from 'chai';
    import sinon = require('sinon');
    describe('Test stubbing Connection', () => {
        it('should be able to stub Connection', async () => {
            const connectionStub = sinon.createStubInstance(Connection);
            expect(connectionStub).to.not.be.null;
        });
    });
    EOF
    TZ=Z npm test

### Expected result

Both tests pass.

### Actual result

        > sfdx-plugin-sinon-error@0.0.0 test
        > nyc --extension .ts mocha --forbid-only "test/**/*.test.ts"
        
        
        
        hello:org
            ✓ runs hello:org --targetusername test@org.com (397ms)
        
        Test stubbing Connection
        1) should be able to stub Connection
        
        
        1 passing (414ms)
        1 failing
        
        1) Test stubbing Connection
        should be able to stub Connection:
            TypeError: Attempted to wrap request which is already wrapped
        at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:39:21)
        at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:85:13)
        at stub (node_modules/sinon/lib/sinon/stub.js:66:44)
        at /Users/frans/workspaces/salesforce/sfdx-plugin-sinon-error/node_modules/sinon/lib/sinon/stub-entire-object.js:15:13
        at /Users/frans/workspaces/salesforce/sfdx-plugin-sinon-error/node_modules/sinon/lib/sinon/util/core/walk.js:23:22
        at Array.forEach (<anonymous>)
        at walkInternal (node_modules/sinon/lib/sinon/util/core/walk.js:18:37)
        at walkInternal (node_modules/sinon/lib/sinon/util/core/walk.js:29:9)
        at walk (node_modules/sinon/lib/sinon/util/core/walk.js:44:12)
        at stubEntireObject (node_modules/sinon/lib/sinon/stub-entire-object.js:7:5)
        at stub (node_modules/sinon/lib/sinon/stub.js:47:16)
        at Sandbox.stub.createStubInstance (node_modules/sinon/lib/sinon/stub.js:73:12)
        at Context.<anonymous> (test/helpers/test-connection-stubbing.test.ts:6:34)
        at processImmediate (node:internal/timers:463:21)
        --------------
            Error: Stack Trace for original
            at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:110:31)
        at stub (node_modules/sinon/lib/sinon/stub.js:66:44)
        at Sandbox.stub (node_modules/sinon/lib/sinon/sandbox.js:289:33)
        at Object.stubMethod (node_modules/@salesforce/ts-sinon/lib/index.js:60:20)
        at Object.stubContext (node_modules/@salesforce/core/lib/testSetup.js:233:16)
        at Context.<anonymous> (node_modules/@salesforce/core/lib/testSetup.js:275:17)
        at processImmediate (node:internal/timers:463:21)
        

### System Information

    {
      "cliVersion": "sfdx-cli/7.108.0",
      "architecture": "darwin-x64",
      "nodeVersion": "node-v14.17.1",
      "pluginVersions": [
        "@oclif/plugin-autocomplete 0.3.0 (core)",
        "@oclif/plugin-commands 1.3.0 (core)",
        "@oclif/plugin-help 3.2.2 (core)",
        "@oclif/plugin-not-found 1.2.4 (core)",
        "@oclif/plugin-plugins 1.10.0 (core)",
        "@oclif/plugin-update 1.4.0-3 (core)",
        "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
        "@oclif/plugin-which 1.0.3 (core)",
        "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
        "@salesforce/sfdx-trust 3.6.0 (core)",
        "alias 1.1.10 (core)",
        "apex 0.2.2 (core)",
        "auth 1.7.0 (core)",
        "config 1.2.9 (core)",
        "custom-metadata 1.0.12 (core)",
        "data 0.4.12 (core)",
        "generator 1.1.7 (core)",
        "limits 1.2.1 (core)",
        "org 1.6.7 (core)",
        "salesforce-alm 52.0.2 (core)",
        "schema 1.0.7 (core)",
        "sfdx-cli 7.108.0 (core)",
        "telemetry 1.2.2 (core)",
        "templates 52.0.0 (core)",
        "user 1.3.0 (core)"
      ],
      "osVersion": "Darwin 18.7.0"
    }

### Additional information

<img width="756" alt="Screenshot 2021-07-15 at 15 01 56" src="https://user-images.githubusercontent.com/305134/125792508-931119b3-e60b-484c-b818-5e9ebc9e65ae.png">

**Comment by mshanemc** [comment]
your tests need to clean up after themselves or the mocks are left in place.   https://sinonjs.org/releases/latest/sandbox/

on trivial tests like yours, you **can** try connectionStub.restore() but it's easier for more complicated things to hang them off the sandbox and restore that after each

Recommendation: for integration tests (real orgs, real SF) try https://github.com/salesforcecli/cli-plugins-testkit

**Comment by fransflippo** [comment]
Hi Shane and thanks for responding.

So https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_test.htm suggests to "include both unit tests and more complex integration, smoke, and end-to-end tests" but then the generated plugin doesn't actually show you how to do that as it doesn't reset the sandbox so any unit test you add to that generated test that mocks `Connection` would have the problem I showed.

I feel that for this to be properly addressed:
- the documentation at https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_test.htm should be expanded to explain **how** to properly write unit tests as well as integration tests and end-to-end tests for sfdx plugins
- the generated test in the plugin generated with `sfdx plugins:generate` should reset the Sinon sandbox since that appears to be the best practice here


End-to-end tests using a scratch org per test have their place but they can't be the solution for everything since they're slow and are not a workable solution for developers on a developer edition org where only 5 scratch orgs are allowed to be created per day. IMHO end-to-end tests don't replace the need for unit/integration tests that mock out the Org/Connection.

**Comment by fransflippo** [comment]
To be clear, I've tried adding the following at the end of my tests but it seems to make absolutely no difference:

      $$.SANDBOX.restore();
      $$.SANDBOXES.CONNECTION.restore();

A concrete working example would be greatly appreciated.

**Comment by fransflippo** [comment]
Workaround for now: run two "test suites" as separate mocha runs by using this for the test task in `package.json`:

```
"test": "nyc --extension .ts mocha -r ts-node/register --forbid-only \"test/**/*.test.ts\" --exclude \"test/commands/**\" && nyc --exclude \"test/**\" --exclude \"src/helpers/**\" --extension .ts mocha -r ts-node/register --forbid-only \"test/commands/**\""
```

**Comment by mshanemc** [comment]
the code that's running the "basic" test from the plugin lives here: https://github.com/salesforcecli/command/blob/main/src/test/index.ts

it's using oclif/fancy-test.

I have a **theory** that this is related to mixing sinon versions (9 in fancytest, probably 10/11 if you install it yourself).

Could you try installing sinon@^9 and seeing it that prevents the conflict?

The other good alternative would be to not use fancy-test if you intend to do more sophisticated things.  I agree we should do all kinds of updates to the plugin-generate command.

Also, our more opinionated plugin template is here https://github.com/salesforcecli/plugin-template

**Comment by mshanemc** [comment]
we're fixing it this week in @W-10260806@
