### ISSUE TITLE
`deploy --sourcepath` different behavior than `--manifest` or `--metadata` for large deploys

### ISSUE THREAD

**Issue by WillieRuemmele** [forcedotcom/cli#1121]
@EgorBosolyho @zankoav

Hello, I have same problem.
With` -p `- work fine, but with `-m` or `-x` -failing.
`sfdx force:source:deploy -p ./force-app/main/default/classes/Test.cls` - worke fine
Our project has a lot of meta files more then 5k, that is why (sfdx force:source:deploy) doesn't work with deployment by -m or -x.
In small projects - all works fine, but not in large.

My logs:
```
sfdx force:source:deploy -m ApexClass:ETEAssets --loglevel=debug --json { "status": 1, "name": "TypeError", "message": "Cannot read property 'id' of undefined", "exitCode": 1, "commandName": "Deploy", "stack": "TypeError: Cannot read property 'id' of undefined\n at ComponentSet.simpleKey (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:303:116)\n at ComponentSet.has (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:237:58)\n at MetadataResolver.getComponentsFromPathRecursive (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:81:49)\n at MetadataResolver.getComponentsFromPathRecursive (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)\n at MetadataResolver.getComponentsFromPathRecursive (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)\n at MetadataResolver.getComponentsFromPathRecursive (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)\n at MetadataResolver.getComponentsFromPathRecursive (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)\n at MetadataResolver.getComponentsFromPath (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:43:25)\n at Function.fromSource (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:67:46)\n at Function.build (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/lib/componentSetBuilder.js:74:74)\nOuter stack:\n at Function.wrap (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n at Deploy.catch (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)\n at async Deploy._run (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n at async Config.runCommand (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/config/lib/config.js:173:24)\n at async SfdxMain.run (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/command/lib/main.js:27:9)\n at async SfdxMain._run (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/command/lib/command.js:43:20)\n at async Object.run (/Users/aleksandrzanko/.local/share/sfdx/client/7.112.1-b99fa53/dist/cli.js:162:47)", "warnings": [] }
```
https://github.com/forcedotcom/cli/issues/1112#issuecomment-896123479

I'm getting the similar issue when I'm trying to use:
`sfdx force:source:deploy -m ApexClass:MyApexClass` OR` sfdx force:source:deploy -x path/to/package.xml`
After some research, I found that it works if I delete most of the objects in the Objects folder. So I think this may be a problem related to large projects. This also works well if I use a deployment with a direct file path
`sfdx force:source:deploy -p path/to/file`
```
TypeError: Cannot read property 'id' of undefined
    at ComponentSet.simpleKey (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:303:116)
    at ComponentSet.has (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:237:58)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:81:49)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPath (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:43:25)
    at Function.fromSource (/Users/user1/.local/share/sfdx/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:67:46)
    at Function.build (/Users/user1/.local/share/sfdx/node_modules/@salesforce/plugin-source/lib/componentSetBuilder.js:74:74)\nOuter stack:
    at Function.wrap (/Users/user1/.local/share/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:171:27)
    at Deploy.catch (/Users/user1/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)
    at async Deploy._run (/Users/user1/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)
    at async Config.runCommand (/Users/user1/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/config/lib/config.js:173:24)
    at async SfdxMain.run (/Users/user1/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/command/lib/main.js:27:9)
    at async SfdxMain._run (/Users/user1/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/Users/user1/.local/share/sfdx/client/7.112.1-b99fa53/dist/cli.js:162:47)
```

Yes, it is.
-m and -x will fail unless I remove a lot of objects from the objects folder or whole folder.
And it doesn't depend on which objects I left, because I thought I had "bad" objects, and tried different cases

-p works well

unfortunately, I can't provide you with our metadata, but I can do any local testing you need.
We have 442 entries in our objects folder. Here we store standard and custom objects.

objects folder info - 11 035 091 bytes (36,7 MB on disk) for 8 358 items

It seems like there's something else that's wrong with deploying with the`-x` flag. I can deploy all the other source (except the Objects) in my project without errors using VS Code (right click + Deploy Source to Org) or with the sfdx force:source:deploy -p path/to/folder.

When I deploy with `sfdx force:source:deploy -x path/to/package.xml` I get same error as before after removing the CustomObject from the package.xml file.
```
*** Deploying with SOAP API ***
ERROR running force:source:deploy: Cannot set property 'content' of undefined
Here's the --dev-debug error:

*** Internal Diagnostic ***

TypeError: Cannot read property 'id' of undefined
    at ComponentSet.simpleKey (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:303:116)
    at ComponentSet.has (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:237:58)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:81:49)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPathRecursive (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:96:37)
    at MetadataResolver.getComponentsFromPath (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/metadataResolver.js:43:25)
    at Function.fromSource (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:67:46)
    at Function.<anonymous> (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:95:49)
Outer stack:
    at Function.wrap (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/sfdxError.js:171:27)
    at Deploy.catch (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)
    at async Deploy._run (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@salesforce/plugin-source/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)
    at async Config.runCommand (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/config/lib/config.js:173:24)
    at async SfdxMain.run (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/command/lib/main.js:27:9)
    at async SfdxMain._run (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/Users/bpete/.local/share/sfdx/client/7.112.1-b99fa53/dist/cli.js:162:47)
******
```

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9748658](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000TwsrYAC/view)

**Comment by WillieRuemmele** [comment]
closing based on [comment](https://github.com/forcedotcom/cli/issues/1112#issuecomment-900818114)

and lots of the SDR registry errors have been fixed
