### ISSUE TITLE
No source backed components present in package

### ISSUE THREAD

**Issue by mfullmore** [forcedotcom/cli#1151]
Hi I am trying to deploy an apex class into an org like this. `sfdx force:source:deploy -u dev1 -m "ApexClass: Gatekeeper"`

I am expecting to deploy said apex class :)

*** Deploying with SOAP API ***
ERROR running force:source:deploy:  No source backed components present in the package

```
2021-08-24T00:26:53.842Z sfdx:Deploy ERROR [
  'ERROR running force:source:deploy: ',
  'No source backed components present in the package',
  '\n' +
    '*** Internal Diagnostic ***\n' +
    '\n' +
    'ComponentSetError: No source backed components present in the package\n' +
    '    at ComponentSet.<anonymous> (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSet.js:139:23)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSet.js:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSet.js:4:12)\n' +
    '    at ComponentSet.deploy (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSet.js:136:16)\n' +
    '    at Deploy.deploy (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\deploy.js:72:52)\n' +
    '    at async Deploy.run (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\deploy.js:38:9)\n' +
    '    at async Deploy._run (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\plugin-source\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\n' +
    '    at async Config.runCommand (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n' +
    'Outer stack:\n' +
    '    at Function.wrap (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\plugin-source\\node_modules\\@salesforce\\command\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n' +
    '    at Deploy.catch (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\plugin-source\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:248:67)\n' +
    '    at async Deploy._run (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@salesforce\\plugin-source\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n' +
    '    at async Config.runCommand (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n' +
    '    at async SfdxMain.run (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n' +
    '    at async SfdxMain._run (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n' +
    '    at async Object.run (C:\\Users\\mfullmore\\AppData\\Local\\sfdx\\client\\7.115.1-a6551a9\\dist\\cli.js:162:47)\n' +
    '******\n'
]
```

```
2021-08-24T00:26:50.935Z sfdx                        OS:
2021-08-24T00:26:50.935Z sfdx                  platform: win32
2021-08-24T00:26:50.935Z sfdx              architecture: x64
2021-08-24T00:26:50.935Z sfdx                   release: 10.0.18363
2021-08-24T00:26:50.935Z sfdx                     shell: C:\Users\mfullmore\AppData\Local\Programs\Git\usr\bin\bash.exe
2021-08-24T00:26:50.935Z sfdx                      NODE:
2021-08-24T00:26:50.935Z sfdx                   version: 14.17.5
2021-08-24T00:26:50.935Z sfdx                       CLI:
2021-08-24T00:26:50.935Z sfdx                   version: 7.115.1
2021-08-24T00:26:50.935Z sfdx                   channel: stable
2021-08-24T00:26:50.935Z sfdx                       bin: sfdx
2021-08-24T00:26:50.935Z sfdx                      data: C:\Users\mfullmore\AppData\Local\sfdx
2021-08-24T00:26:50.935Z sfdx                     cache: C:\Users\mfullmore\AppData\Local\sfdx
2021-08-24T00:26:50.935Z sfdx                    config: C:\Users\mfullmore\AppData\Local\sfdx
2021-08-24T00:26:50.936Z sfdx                       ENV:
2021-08-24T00:26:50.936Z sfdx              NODE_OPTIONS: <not set>
2021-08-24T00:26:50.936Z sfdx   SFDX_AUTOUPDATE_DISABLE: <not set>
2021-08-24T00:26:50.936Z sfdx              SFDX_BINPATH: C:\Users\mfullmore\AppData\Local\sfdx\client\bin\sfdx
2021-08-24T00:26:50.936Z sfdx        SFDX_COMPILE_CACHE: <not set>
2021-08-24T00:26:50.936Z sfdx   SFDX_DISABLE_AUTOUPDATE: <not set>
2021-08-24T00:26:50.936Z sfdx                  SFDX_ENV: development
2021-08-24T00:26:50.936Z sfdx            SFDX_INSTALLER: true
2021-08-24T00:26:50.936Z sfdx    SFDX_LAZY_LOAD_MODULES: true
2021-08-24T00:26:50.936Z sfdx         SFDX_NPM_REGISTRY: <not set>
2021-08-24T00:26:50.936Z sfdx           SFDX_REDIRECTED: 1
2021-08-24T00:26:50.936Z sfdx              SFDX_S3_HOST: <not set>
2021-08-24T00:26:50.936Z sfdx  SFDX_UPDATE_INSTRUCTIONS: <not set>
2021-08-24T00:26:50.936Z sfdx                      ARGS:
2021-08-24T00:26:50.936Z sfdx                         0: C:\Users\mfullmore\AppData\Local\sfdx\client\7.115.1-a6551a9\bin\node.exe
2021-08-24T00:26:50.936Z sfdx                         1: C:\Users\mfullmore\AppData\Local\sfdx\client\7.115.1-a6551a9\bin\run
2021-08-24T00:26:50.936Z sfdx                         2: force:source:deploy
2021-08-24T00:26:50.936Z sfdx                         3: -u
2021-08-24T00:26:50.936Z sfdx                         4: dev1
2021-08-24T00:26:50.936Z sfdx                         5: -m
2021-08-24T00:26:50.936Z sfdx                         6: ApexClass: Gatekeeper
```

**Comment by mfullmore** [comment]
I also switched to deploy with REST and received the same error.

**Comment by aheber** [comment]
@mfullmore, what happens if you drop the space in the MDT reference, `sfdx force:source:deploy -u dev1 -m "ApexClass:Gatekeeper"`, I had someone on my team with a similar problem and we resolved it by removing the space.

**Comment by WillieRuemmele** [comment]
Hi @mfullmore nice find! @aheber's suggestion was able to fix the problem for me, I'll fix this right away!

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9803972](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000000t6ODYAY/view)

**Comment by ImJohnMDaniel** [comment]
@mshanemc - I am still seeing this issue when trying to deploy only `*.settings-meta.xml` files to an org.  Do you want to reopen this ticket or do you want me to open a new ticket?  

Also, this is going against a Summer 21 scratch org and I running `sfdx-cli/7.121.4 darwin-x64 node-v14.18.0`.  Let me know if you have questions.  Thanks for the help.

**Comment by mshanemc** [comment]
Yes, can you give us your repro, including what type of .settings files you have and the command you're using?

**Comment by avesolovksyy** [comment]
@mshanemc 

In my case I'm running into this error when trying to deploy code from hidden subfolder on Windows, e.g.
`sfdx force:source:deploy -u "myTestOrg" --sourcepath="subfolder/.hiddenFolder/myBundle"`

After updating `.hiddenFolder` to `publicFolder` it starts working right away.
Not sure whether it's expected behaviour, but it's rather inconvenient - we are moving to sfdx from ant migration tool and there is no limitation like that re hidden folders there.

Is there any way to force sfdx deploy from hidden folder as well?

Thanks in advance

**Comment by Nkumarot** [comment]
![image](https://user-images.githubusercontent.com/114013776/202806695-8a801d86-9244-434b-81ff-b0b50e13a399.png)

Successfully validated the pull request with Dev Int instance. It has only one page layout and we have removed the New Account Opening button on the Skience managed package contact layout.

**Comment by manhntbkit** [comment]
"After updating .hiddenFolder to publicFolder it starts working right away." -> works for me.
