### ISSUE TITLE
"ERROR running force:source:deploy: The org cannot be found" after successful login to Salesforce org

### ISSUE THREAD

**Issue by docbill** [forcedotcom/cli#1181]
Same thing as issue #820 after upgrading in Fedora today.

```
sfdx force:mdapi:deploy -d redhatframework-app.mdapi --testlevel=RunSpecifiedTests -r AbstractTriggerTest,BooleanValuesHelperTest,DatabaseHelperTest,DatabaseUtilitiesTest,Field_MapTest,LimitHelperTest,Metadata_Values_HelperTest,SObjectCallableTriggerTest,ThreadLockCallableTriggerTest,ThreadLockTest,TriggerArgumentsTest,TriggerManagementTest, --loglevel=warn -w 30 -u dev1
*** Deploying with SOAP ***
Job ID | 0Af3I00000JQl31SAD
(node:7334) UnhandledPromiseRejectionWarning: Domain Not Found: The org cannot be found
    at Connection.isResolvable (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/connection.js:276:19)
    at async Connection.retrieveMaxApiVersion (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/connection.js:237:9)
    at async Connection.useLatestApiVersion (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/connection.js:248:32)
    at async useLatest (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/connection.js:406:13)
    at async Connection.loadInstanceApiVersion (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/connection.js:428:13)
    at async Function.create (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/connection.js:88:39)
    at async getCoreConnection (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/dist/lib/core/force.js:34:18)
    at async Force.mdapiCheckDeployStatus (/home/remote/briemers/.local/share/sfdx/client/7.116.2-7d0f61b/node_modules/salesforce-alm/dist/lib/core/force.js:197:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by docbill** [comment]
I am attempting the same workaround that user used:

sfdx force:config:set apiVersion=52.0

I am not using a proxy...

**Comment by docbill** [comment]
The workaround works...

```
sfdx force:mdapi:deploy -d redhatframework-app.mdapi --testlevel=RunSpecifiedTests -r AbstractTriggerTest,BooleanValuesHelperTest,DatabaseHelperTest,DatabaseUtilitiesTest,Field_MapTest,LimitHelperTest,Metadata_Values_HelperTest,SObjectCallableTriggerTest,ThreadLockCallableTriggerTest,ThreadLockTest,TriggerArgumentsTest,TriggerManagementTest, --loglevel=warn -w 30 -u dev1
WARNING: apiVersion configuration overridden at "52.0"
*** Deploying with SOAP ***
Job ID | 0Af3I00000JQl6KSAT

=== Test Success [70]
NAME                           METHOD
─────────────────────────────  ────────────────────────────
AbstractTriggerTest            afterInsertTest
AbstractTriggerTest            afterUpdateTest
AbstractTriggerTest            beforeInsertTest
AbstractTriggerTest            beforeOrAfterDeleteTest
AbstractTriggerTest            beforeUpdateTest
AbstractTriggerTest            booleanSettingsTest
AbstractTriggerTest            coverageTests
AbstractTriggerTest            currentUserTest
AbstractTriggerTest            exceptionTests
AbstractTriggerTest            isActiveWithBooleanMetadata
AbstractTriggerTest            processTriggerCompleteTest
BooleanValuesHelperTest        booleanHierarchyTest
BooleanValuesHelperTest        booleanMetadataTest
BooleanValuesHelperTest        booleanSettingsTest
BooleanValuesHelperTest        getBooleanValueTest
DatabaseHelperTest             dmlExceptionTest
DatabaseHelperTest             dmlOptionsTest
DatabaseHelperTest             enqueueJobTest
DatabaseHelperTest             enqueueScopeTest
DatabaseHelperTest             enqueueScopeTest2
DatabaseHelperTest             getErrorsTest
DatabaseHelperTest             safeTest
DatabaseHelperTest             splitTest
DatabaseUtilitiesTest          allowFieldTruncationTest
DatabaseUtilitiesTest          allowFieldTruncationTest2
DatabaseUtilitiesTest          deactivateAllTest
DatabaseUtilitiesTest          simpleErrorListTest
DatabaseUtilitiesTest          updateIsSuccessTest
Field_MapTest                  convertTextTest
Field_MapTest                  copyFieldTest
Field_MapTest                  getDestinationFieldNamesTest
Field_MapTest                  getSourceFieldNamesTest
Field_MapTest                  testMap
LimitHelperTest                checkLimitsCpuTimeTest
LimitHelperTest                checkLimitsDmlRowsTest
LimitHelperTest                checkLimitsDmlStatementsTest
LimitHelperTest                checkLimitsQueriesTest
LimitHelperTest                checkLimitsQueueableJobsTest
LimitHelperTest                cpuTimeTest
LimitHelperTest                dmlRowsTest
LimitHelperTest                dmlStatementsTest
LimitHelperTest                pushPopTest
LimitHelperTest                queriesTest
LimitHelperTest                queueableJobsTest
Metadata_Values_HelperTest     decimal2ValuesTest
Metadata_Values_HelperTest     stringValuesTest
SObjectCallableTriggerTest     assignLegacyNegativeTest
SObjectCallableTriggerTest     assignLegacyTest
SObjectCallableTriggerTest     callExceptionTest
ThreadLockCallableTriggerTest  callExceptionTest
ThreadLockCallableTriggerTest  threadLockTest
ThreadLockTest                 lockAndUnlockTest
TriggerArgumentsTest           afterDeleteTest
TriggerArgumentsTest           afterInsertTest
TriggerArgumentsTest           afterUndeleteTest
TriggerArgumentsTest           afterUpdateTest
TriggerArgumentsTest           afterUpdateTest2
TriggerArgumentsTest           beforeDeleteTest
TriggerArgumentsTest           beforeInsertTest
TriggerArgumentsTest           beforeUpdateTest
TriggerArgumentsTest           beforeUpdateTest2
TriggerArgumentsTest           dummyTriggerTest
TriggerArgumentsTest           getSObjectMapTest
TriggerManagementTest          attachmentTest
TriggerManagementTest          callTest
TriggerManagementTest          callTriggerTest
TriggerManagementTest          callTriggerTest2
TriggerManagementTest          getEntityBaseConditionTest
TriggerManagementTest          getNonEntityValueTest
TriggerManagementTest          getUniqueTriggerString

=== Apex Code Coverage
NAME                         % COVERED  UNCOVERED LINES
───────────────────────────  ─────────  ───────────────
AbstractTrigger              100%
AttachmentTriggerManagement  100%
BooleanValuesHelper          100%
DatabaseHelper               100%
DatabaseHelperQueueable      100%
DatabaseHelperResult         100%
DatabaseUtilities            100%
Field_Map                    100%
LimitHelper                  100%
Metadata_Values_Helper       100%
SObjectCallableTrigger       100%
ThreadLock                   100%
ThreadLockCallableTrigger    100%
TriggerArguments             100%
TriggerManagement            100%

Total Test Time:  52832.0
```

**Comment by docbill** [comment]
But I'm left confused as to why a lookup to salesforce would fail.

I tried configuring the domain with the default:

https://test.salesforce.com

and

https://redhat--dev1.my.salesforce.com

Both consistently give the same domain lookup failure error.

**Comment by docbill** [comment]
The same error occurs when I attempt to run a test class in vscode.

**Comment by maggiben** [comment]
Hi, can you try setting the environment variable `SFDX_DISABLE_DNS_CHECK=true` as a workaround ?

**Comment by docbill** [comment]
I could try it if you can provide the answer to this question:

https://superuser.com/questions/19044/how-do-i-set-an-environmental-variable-for-a-gnome-session

Using the setting from commandline would be much less convient than the apiVersion workaround, as I could then never use the VSCode icon to launch the application.

**Comment by docbill** [comment]
Looks like while adding the environmental variable to /etc/profile will not be picked up by all applications running in gnome, vscode does pick it up for both commands running in the command palette, and the vscode terminal windows.   

It would however, be very useful to understand why this is happening and fix the problem, rather than just providing a workaround.   As this means every single developer needs to discover this workaround.   There is obviously something broken in that dns lookup...   As there is absolutely no reason it should be failing when dig, nslookup, and webbrowsers are able to lookup the domains without problems.

**Comment by docbill** [comment]
```
$ dig redhat--dev1.my.salesforce.com

; <<>> DiG 9.16.20-RH <<>> redhat--dev1.my.salesforce.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10502
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;redhat--dev1.my.salesforce.com.        IN      A

;; ANSWER SECTION:
redhat--dev1.my.salesforce.com. 20 IN   CNAME   cs123.force.com.
cs123.force.com.        20      IN      CNAME   cs123-ia4.force.com.
cs123-ia4.force.com.    20      IN      CNAME   cs123-ia4.ia4.r.force.com.
cs123-ia4.ia4.r.force.com. 20   IN      A       13.109.186.17
cs123-ia4.ia4.r.force.com. 20   IN      A       13.110.58.17
cs123-ia4.ia4.r.force.com. 20   IN      A       13.109.187.17

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Sep 09 11:20:32 EDT 2021
;; MSG SIZE  rcvd: 187

```

**Comment by docbill** [comment]
Perhaps the lookup is code is being confused because salesforce uses cname that ultimately resolves to multiple IP addresses.  Both for my domain names and for test.salesforce.com.

**Comment by mshanemc** [comment]
if you add `--dev-debug`, you'll get a much deeper trace that may give better hints to what it's using to resolve

**Comment by docbill** [comment]
Thanks.  I will try this ASAP.
