### ISSUE TITLE
npm install sfdx-cli proxy errors

### ISSUE THREAD

**Issue by kikemoto** [forcedotcom/cli#1212]
### Summary

Starting with sfdx-cli@7.120.0, Jenkins CI scripts fail to install package.

Our co's jenkins environment:
1. is behind a proxy
2. uses artifactory as a package repository
3. cannot make callouts to github.com during package install

Our ci scripts were successfully able to install versions prior to 7.120.0.

The issue we are facing seems related to this commit:
https://github.com/salesforcecli/sfdx-cli/commit/1676c0bbe843a24a5fc458921f5cf832665a7e94#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR1195

And this line introduced the url to `package-lock.json`:
```
Package-lock.json line 1195
inquirer "https://github.com/salesforcecli/Inquirer.js/tarball/github_release"
```

### Steps To Reproduce:
From jenkins machine behind firewall, with artifactory repo and env where ci machine cannot make callout to github.com:
1.  npm install sfdx-cli

### Expected result
sfdx-cli installed successfully

### Actual result

```
npm ERR! code ECONNREFUSED
errno ECONNREFUSED
FetchError: request to https://github.com/salesforcecli/Inquirer.js/tarball/github_release failed, reason: connect ECONNREFUSED 140.82.114.4:443
    at ClientRequest.<anonymous> (/usr/lib64/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 FetchError: request to https://github.com/salesforcecli/Inquirer.js/tarball/github_release failed, reason: connect ECONNREFUSED 140.82.114.4:443
    at ClientRequest.<anonymous> (/usr/lib64/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  parent: '@salesforce/cli'
}

If you are behind a proxy, please make sure that the
'proxy' config is set properly.  See: 'npm help config'
```

### System Information

Run `sfdx version --verbose --json` and paste the output here.
```
{
	"cliVersion": "sfdx-cli/7.114.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v14.17.5",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.2 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.4.0-3 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-trust 3.6.0 (core)",
		"alias 1.1.10 (core)",
		"apex 0.2.7 (core)",
		"auth 1.7.1 (core)",
		"config 1.2.23 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.0 (core)",
		"generator 1.1.7 (core)",
		"limits 1.2.1 (core)",
		"org 1.6.9 (core)",
		"salesforce-alm 52.2.5 (core)",
		"schema 1.0.8 (core)",
		"sfdx-cli 7.114.0 (core)",
		"source 1.0.9 (core)",
		"telemetry 1.2.3 (core)",
		"templates 52.1.0 (core)",
		"user 1.4.0 (core)"
	],
	"osVersion": "Darwin 20.6.0"
}
```

### Additional information

Here is a snippet from `npm install sfdx-cli --verbose` when run locally, not behind a proxy.
Please note the 2nd get request. 
```
npm http fetch GET 200 https://artifactory.company.biz/api/npm/js-virtual/@salesforce%2fplugin-env 32ms (from cache)
npm http fetch GET 304 https://codeload.github.com/salesforcecli/Inquirer.js/legacy.tar.gz/github_release 632ms (from cache)
npm http fetch GET 200 https://artifactory.company.biz/api/npm/js-virtual/get-package-type 8ms (from cache)
```

**Comment by peternhale** [comment]
@kikemoto we are tracking this problem on this #1208
