### ISSUE TITLE
SFDX upgrade from 7.125.0 to 7.126.0 is breaking community file deployment - Error: Expected source files for type 'SiteDotCom'

### ISSUE THREAD

**Issue by dragomir-enachi-ibm** [forcedotcom/cli#1279]
After upgrading SFDX from
sfdx-cli/7.125.0 linux-x64 node-v16.13.0
to
7.126.0

We started getting the following issue while trying to deploy community files.

force:source:deploy fails with
app/main/default/sites/IBM_Partner_Portal.site-meta.xml: Expected source files for type 'SiteDotCom'

Started failing today(Nov 11, 2021) between 1PM GMT and 5PM GMT

reverting SFDX back to 7.125.0 confirmed to resolve the issue.

**Comment by jk-ng** [comment]
Also seeing this issue with the upgrade to 7.126.0. Rolling back the version also corrected the issue

**Comment by joneychow-intertek** [comment]
Similar issue for me as well. It happens during **source:convert** in my pipeline after updated to 7.126.0
 
sfdx force:source:convert -p force-app -d mdapioutput
ERROR running force:source:convert:  ./force-app/main/default/sites/MTC.site-meta.xml: Expected source files for type 'SiteDotCom'

**Comment by Erisiel** [comment]
Same issue here also with source:convert and then Expected source files for type 'SiteDotCom'

**Comment by mshanemc** [comment]
This is fixed in 7.127 ( `sfdx update stable-rc` if you want to test or use it now)

**Comment by hansalves** [comment]
Upgrading to 7.127 resolved the issue for me 👍

**Comment by anthonyshughes** [comment]
Upgrading to 7.127 fixed this for me. I was however on 7.97 previously so I don't think this was an issue specifically with 7.126.

**Comment by fkramer690** [comment]
I phase the problem with an azure pipeline.

"cliVersion": "@salesforce/cli/2.79.4",


![Image](https://github.com/user-attachments/assets/592f64da-02be-4a7c-8890-6ef0b0241630)

[sfdx-hardis] [31m[1mSadly there has been Deployment error(s)[22m[39m
2025-03-13T14:36:15.4204085Z [sfdx-hardis] [31m[39m
2025-03-13T14:36:15.4204431Z [31m{[39m
2025-03-13T14:36:15.4204800Z [31m  "name": "ExpectedSourceFilesError",[39m
2025-03-13T14:36:15.4205394Z [31m  "message": "/home/vsts/work/1/s/force-app/main/default/siteDotComSites/customerportal1.site-meta.xml: Expected source files for type 'SiteDotCom'",[39m
2025-03-13T14:36:15.4205849Z [31m  "exitCode": 1,[39m
2025-03-13T14:36:15.4206336Z [31m  "context": "DeployMetadata",[39m
2025-03-13T14:36:15.4208879Z [31m  "stack": "ExpectedSourceFilesError: /home/vsts/work/1/s/force-app/main/default/siteDotComSites/customerportal1.site-meta.xml: Expected source files for type 'SiteDotCom'\n    at SfCommandError.from (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at DeployMetadata.catch (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:323:47)\n    at DeployMetadata.catch (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/deploy/start.js:272:27)\n    at DeployMetadata._run (/opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:185:29)\n    at async Config.runCommand (/opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:456:25)\n    at async run (/opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:96:16)\n    at async file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@salesforce/cli/bin/run.js:15:1",[39m
2025-03-13T14:36:15.4210368Z [31m  "cause": "undefined",[39m
2025-03-13T14:36:15.4210667Z [31m  "warnings": [],[39m
2025-03-13T14:36:15.4211027Z [31m  "code": "ExpectedSourceFilesError",[39m
2025-03-13T14:36:15.4211391Z [31m  "status": 1,[39m
2025-03-13T14:36:15.4211766Z [31m  "commandName": "DeployMetadata"[39m
2
