### ISSUE TITLE
sfdx force:mdapi:convert throws UnhandledPromiseRejection for corrupt static resource

### ISSUE THREAD

**Issue by brsanthu** [forcedotcom/cli#1384]
### Summary

If static resource has mime type and content is not actually a zip file, sfdx command fails with UnhandledPromiseRejection

### Steps To Reproduce:

**Repository to reproduce:**
https://github.com/brsanthu/sfdx-issuerepo-1

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Extract repo
1.  Run command `sfdx force:mdapi:convert --rootdir=mdfiles --manifest=mdfiles/package.xm`

### Expected result

It should have properly handled the error and command should have returned error and not fail with UnhandledPromiseRejection. Also if there are other components, should have processed.

### Actual result

```
sfdx force:mdapi:convert --rootdir=mdfiles --manifest=mdfiles/package.xml --json
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ERROR: We've encountered an error in /private/var/folders/ng/0glsnjjs4lldj3z_2ggx8hvw0000gn/T/com.datasert/retrieve-sfdx/mdfiles/staticresources/leaflet.resource, which is likely not an issue with Salesforce CLI. Verify that the MIME type you expect matches what you have: application/zip. Here's the error: Error: Invalid CEN header (bad signature)
    at Object.loadFromBinary (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/headers/entryHeader.js:209:23)
    at Object.set header [as header] (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/zipEntry.js:287:26)
    at readEntries (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/zipFile.js:50:26)
    at Object.get entries [as entries] (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/zipFile.js:123:17)
    at Object.extractAllTo (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/adm-zip.js:604:18)
    at StaticResource.expandArchive (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/staticResource.js:257:36)
    at StaticResource.saveResource (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/staticResource.js:86:29)
    at StaticResourceContentStrategy.saveContent (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/staticResourceContentStrategy.js:24:83)
    at AggregateSourceElement.commitContent (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/aggregateSourceElement.js:349:121)
    at AggregateSourceElement.commit (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/aggregateSourceElement.js:311:24)
    at async SourceWorkspaceAdapter.updateSource (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:249:93)
    at async Walker.<anonymous> (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/mdapiConvertApi.js:426:25).".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ERROR: We've encountered an error in /private/var/folders/ng/0glsnjjs4lldj3z_2ggx8hvw0000gn/T/com.datasert/retrieve-sfdx/mdfiles/staticresources/leaflet.resource, which is likely not an issue with Salesforce CLI. Verify that the MIME type you expect matches what you have: application/zip. Here's the error: Error: Invalid CEN header (bad signature)
    at Object.loadFromBinary (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/headers/entryHeader.js:209:23)
    at Object.set header [as header] (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/zipEntry.js:287:26)
    at readEntries (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/zipFile.js:50:26)
    at Object.get entries [as entries] (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/zipFile.js:123:17)
    at Object.extractAllTo (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/adm-zip/adm-zip.js:604:18)
    at StaticResource.expandArchive (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/staticResource.js:257:36)
    at StaticResource.saveResource (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/staticResource.js:86:29)
    at StaticResourceContentStrategy.saveContent (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/staticResourceContentStrategy.js:24:83)
    at AggregateSourceElement.commitContent (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/aggregateSourceElement.js:349:121)
    at AggregateSourceElement.commit (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/aggregateSourceElement.js:311:24)
    at async SourceWorkspaceAdapter.updateSource (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:249:93)
    at async Walker.<anonymous> (/Users/brsanthu/.local/share/sfdx/client/7.134.0-4f69b20/node_modules/salesforce-alm/dist/lib/source/mdapiConvertApi.js:426:25).".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`

```
> sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.134.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.13.2",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.2.0 (core)",
		"apex 0.7.0 (core)",
		"auth 1.8.0 (core)",
		"config 1.3.14 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.8 (core)",
		"generator 1.2.1 (core)",
		"info 1.2.0 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.0 (core)",
		"salesforce-alm 53.7.2 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.134.0 (core)",
		"source 1.8.0 (core)",
		"telemetry 1.4.0 (core)",
		"templates 53.1.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.0 (core)"
	],
	"osVersion": "Darwin 19.2.0"
}
```
### Additional information

_Feel free to attach a screenshot_.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10512135](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000jvOjdYAE/view)

**Comment by mshanemc** [comment]
Yeah, I can see the `--json` output work correctly (returns exit code 1) but the stdout looks like it "succeeds" with an early exit.
