### ISSUE TITLE
PackageInstallationCommand is failing with "Details: intelligentDiscoveryStatus: No TOKEN named force:base.cardSpacingMargin found"

### ISSUE THREAD

**Issue by vmamidala-conga** [forcedotcom/cli#1433]
### Summary
Package Installation is failing intermittently on a fresh ScartchOrg using sfdx cli package installation Commmand.
this was working well since many days, and observing this error since few days for few builds.

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Create a scratchOrg
2. Install the package using packageInstallCommand using SFDX CLI ( I could not share package info, but it was working fine since many days and this installation issue is intermittent, if we rerun the process again with new org, it is working fine.)

### Expected result
1. Package should install
### Actual result

_Describe what actually happened_.
1. Package installation is failed with below error, cli logs are provided.

```
ERROR:  Encountered errors installing the package!,Installation errors: 
1) (intelligentDiscoveryStatus) No TOKEN named force:base.cardSpacingMargin found, Details: intelligentDiscoveryStatus: No TOKEN named force:base.cardSpacingMargin found
{
  "status": 1,
  "name": "Error",
  "message": "Installation errors: \n1) (intelligentDiscoveryStatus) No TOKEN named force:base.cardSpacingMargin found, Details: intelligentDiscoveryStatus: No TOKEN named force:base.cardSpacingMargin found",
  "exitCode": 1,
  "commandName": "PackageInstallCommand",
  "stack": "Error: Installation errors: \n1) (intelligentDiscoveryStatus) No TOKEN named force:base.cardSpacingMargin found, Details: intelligentDiscoveryStatus: No TOKEN named force:base.cardSpacingMargin found\n    at force.toolingRetrieve.then.request (/usr/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/package/packageInstallCommand.js:94:27)\n    at tryCatcher (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\nOuter stack:\n    at Function.wrap (/usr/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at PackageInstallCommand.catch (/usr/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:248:46)",

  "warnings": []

}
```

### System Information
```
  ~  sfdx version --verbose --json
 ›   Warning: sfdx-cli update available from 7.96.1 to 7.129.0.
sfdx-cli/7.96.1 darwin-x64 node-v16.4.0
```

**Comment by cristiand391** [comment]
@vmamidala-conga are you still getting this error?
If so, please try updating `sfdx` to latest, you are using a very old version.

**Comment by vmamidala-conga** [comment]
No, we have not faced this issue afterwards, how this issue is related to sfdx cli version?

**Comment by mshanemc** [comment]
@vmamidala-conga I'm not really sure.  The packaging team owns those commands, so they have may fixed something in the command or on the server side.  Either way, I'm glad the error is gone
