### ISSUE TITLE
sfdx force:source:deploy with RunSpecifiedTests fails with "Method not implemented" error

### ISSUE THREAD

**Issue by jeffb-sfdc** [forcedotcom/cli#1489]
This bug was originally raised in https://github.com/forcedotcom/salesforcedx-vscode/issues/4056.  The initial issue was that when a deploy (using the extension) failed for the customer, an error was reported, but no additional information was reported.  The user also reported that when they ran:
```
sfdx force:source:deploy -p force-app/main/default -l RunSpecifiedTests -c -r --json
```
...from the CLI, they got:
```
{
  "status": 1,
  "name": "DeployFailed",
  "message": "Deploy failed.",
  "exitCode": 1,
  "commandName": "Deploy",
  "stack": "DeployFailed: Deploy failed.\n    at DeployResultFormatter.display (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\formatters\\deployResultFormatter.js:62:19)\n    at Deploy.formatResult (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\deploy.js:133:23)\n    at Deploy.run (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\deploy.js:35:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Deploy._run (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\n    at async Config.runCommand (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async SfdxMain.run (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async SfdxMain._run (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\sryan\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\dist\\cli.js:162:47)",
  "warnings": []
}
```

The (initial) issue the user was having with deploying using the VS Code extension is separate from this and is a different issue.

I was able to reproduce this myself running:
```
sfdx force:source:deploy -p force-app/main/default -l RunSpecifiedTests -c -r --json
```
...and I found that running just:
```
sfdx force:source:deploy -p force-app/main/default --json
```
...worked, so there appears there might be an issue with the `RunSpecifiedTests` option.

**Comment by mshanemc** [comment]
**That is not a correct usage**

`sfdx force:source:deploy -p force-app/main/default -l RunSpecifiedTests -c -r --json` is invalid because you said "run some specified tests" but didn't specify any tests after `-r`

That said, the CLI could have validated that flag combo upfront instead of doing the deploy and then having the test step fail because of bad inputs.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11083681](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000wBB4vYAG/view)

**Comment by mshanemc** [comment]
link to the underlying oclif bug oclif/config#318

**Comment by WillieRuemmele** [comment]
Closing this as the CLI's handle the flag validation better, the OCLIF bug still exists of reading the next arg into the array, but you can't replicate this anymore

```bash
 ➜  sf force source deploy -p force-app -l RunSpecifiedTests -c -r --json   
{
  "code": 1,
  "context": "Deploy",
  "commandName": "Deploy",
  "message": "Flag --runtests expects a value",
...
 ➜  sf project deploy start --source-dir force-app/main/default --test-level RunSpecifiedTests --tests --json
{
  "code": 1,
  "context": "DeployMetadata",
  "commandName": "DeployMetadata",
  "message": "Flag --tests expects a value",
```
