### ISSUE TITLE
Unable to retrieve LWC with manifest

### ISSUE THREAD

**Issue by Kxviswa** [forcedotcom/cli#154]
### Summary

Not able to retrieve LWC with manifest

### Steps To Reproduce:

Do the following in VS code.

1.  Create a project with Manifest.
2. Authorize the org.
3. Right click on package.xml in manifest folder and Retrieve Source in Manifest from Org

The following command also resulted in same error

sfdx force:source:retrieve --manifest ~/Documents/workspace/IT/manifest/package.xml

### Expected result

To retrieve all the LWC from the org

### Actual result

ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined

### Additional information

The following is the package.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <version>45.0</version>
</Package>
```

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.20.1-d88ae4707c darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.10.2 (core)
├─ force-language-services 46.14.0 (core)
└─ salesforce-alm 46.13.0 (core)

sfdx-cli 7.20.1 (core)

**OS and version**:
ProductName:	Mac OS X
ProductVersion: 10.14.5
BuildVersion:	18F203

**Comment by clairebianchi** [comment]
@Kxviswa we are not seeing this issue on our side. Can you please run the command with `--dev-debug` 

I does the -m LightningComponentBundle work?

**Comment by Kxviswa** [comment]
@clairebianchi  I executed both the commands with --dev-debug. The following are the errors that I got.


**sfdx force:source:retrieve --manifest ~/Documents/workspace/IT/manifest/package.xml  --dev-debug**

ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined 
*** Internal Diagnostic ***

TypeError: Cannot read property 'fileName' of undefined
    at Function.getMetadataFileNameFromBundleFileProperties (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:41:48)
    at Function.getPathFromBundleTypeFileProperties (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:35:43)
    at LightningComponentBundleMetadataType.getDefaultAggregateMetadataPath (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/metadataTypeImpl/bundleMetadataType.js:30:52)
    at SourceWorkspaceAdapter.processMdapiFileProperty (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:278:59)
    at result.fileProperties.forEach.fileProperty (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:139:22)
    at Array.forEach (<anonymous>)
    at MdapiPullApi._syncDownSource (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:132:31)
    at SourceRetrieve.retrieveFromManifest (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourceRetrieve.js:128:56)
Outer stack:
    at Function.wrap (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at SourceRetrieveCommand.catch (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/ToolbeltCommand.js:230:46)
******



**sfdx force:source:retrieve -m LightningComponentBundle --dev-debug**

ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined 
*** Internal Diagnostic ***

TypeError: Cannot read property 'fileName' of undefined
    at Function.getMetadataFileNameFromBundleFileProperties (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:41:48)
    at Function.getPathFromBundleTypeFileProperties (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:35:43)
    at LightningComponentBundleMetadataType.getDefaultAggregateMetadataPath (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/metadataTypeImpl/bundleMetadataType.js:30:52)
    at SourceWorkspaceAdapter.processMdapiFileProperty (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:278:59)
    at result.fileProperties.forEach.fileProperty (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:139:22)
    at Array.forEach (<anonymous>)
    at MdapiPullApi._syncDownSource (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:132:31)
    at SourceRetrieve.retrieveFromManifest (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/lib/source/sourceRetrieve.js:128:56)
Outer stack:
    at Function.wrap (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at SourceRetrieveCommand.catch (/Users/nathan/.local/share/sfdx/client/7.20.1-d88ae4707c/node_modules/salesforce-alm/dist/ToolbeltCommand.js:230:46)
******

**Comment by clairebianchi** [comment]
@Kxviswa, can you submit a case with support? This looks unique to your setup.

**Comment by Kxviswa** [comment]
@clairebianchi  You mean Salesforce Support ?

**Comment by Kxviswa** [comment]
@clairebianchi Thanks will do.
