### ISSUE TITLE
"sfdx force:source:manifest:create --fromorg" crashes with "The specified metadata type is unsupported: []"

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#1623]
### Summary

"sfdx force:source:manifest:create --fromorg" crashes with "The specified metadata type is unsupported: []" in same production org as that mentioned in #1492

### Steps To Reproduce:

**Repository to reproduce:** customer's production org

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

Run `sfdx force:source:manifest:create --fromorg=<myusername> -o manifest -n package-snapshot-fromorg.xml --loglevel=trace --json`

### Expected result

Should produce a manifest file

### Actual result

{
  "status": 1,
  "name": "SfError",
  "message": "The specified metadata type is unsupported: []",
  "exitCode": 1,
  "context": "create",
  "stack": "SfError: The specified metadata type is unsupported: []\n    at Function.build (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSetBuilder.js:109:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async createManifest (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@salesforce/plugin-source/lib/commands/force/source/manifest/create.js:52:30)\n    at async create.run (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@salesforce/plugin-source/lib/commands/force/source/manifest/create.js:32:9)\n    at async create._run (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@salesforce/command/lib/sfdxCommand.js:89:40)\n    at async Config.runCommand (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/xxx/.local/share/sfdx/client/7.156.1-6536039/dist/cli.js:162:47)",
  "warnings": [],
  "commandName": "create"
}

### System Information

- Which shell/terminal are you using? bash

- If you are using `sfdx`
sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.156.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.0 (core)",
                "schema 2.1.1 (core)",
                "sfdmu 4.14.4",
                "sfdx-cli 7.156.1 (core)",
                "sfdx-qsf-plugin 0.0.2 (link) /Users/xxx/.../sfdx-qsf-plugin",
                "sfpowerkit 4.2.8",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/sfdx-sosl 1.1.0",
                "└─ @mshanemc/plugin-streaming 1.1.7",
                "signups 1.2.0 (core)",
                "source 2.0.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}

### Additional information

This is the same org as that mentioned in #1492

**Comment by shetzel** [comment]
I believe this is fixed in the CLI release candidate.  Could you update to the RC version and try the command to see if that fixes it for you?

**Comment by cristiand391** [comment]
Closing due to inactivity, but please let us know if this still happens on latest and we'll re-open this.
