### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established" on package create

### ISSUE THREAD

**Issue by MarcDBehr** [forcedotcom/cli#1646]
### Summary

When trying to create a new package version, getting an error message  "Client network socket disconnected before secure TLS connection was established"

### Steps To Reproduce:

1. Attempt to create a new package version  `sfdx force:package:version:create -w 60 -x -c --package package_name --json` 

### Expected result

Package version gets created

### Actual result

{
  "status": 1,
  "name": "Fetch",
  "message": "request to https://xxx.my.salesforce.com/services/data/v55.0/tooling/query?q=SELECT%20Id%2C%20Status%2C%20Package2Id%2C%20Package2VersionId%2C%20Package2Version.SubscriberPackageVersionId%2C%20Tag%2C%20Branch%2C%20CreatedDate%2C%20Package2Version.HasMetadataRemoved%2C%20CreatedById%20FROM%20Package2VersionCreateRequest%20WHERE%20Id%20%3D%20%2708c5G000000PCXXXXX%27%20ORDER%20BY%20CreatedDate failed, reason: Client network socket disconnected before secure TLS connection was established",
  "exitCode": 1,
  "context": "PackageVersionCreateCommand",
  "stack": "Fetch: request to https://xxx.my.salesforce.com/services/data/v55.0/tooling/query?q=SELECT%20Id%2C%20Status%2C%20Package2Id%2C%20Package2VersionId%2C%20Package2Version.SubscriberPackageVersionId%2C%20Tag%2C%20Branch%2C%20CreatedDate%2C%20Package2Version.HasMetadataRemoved%2C%20CreatedById%20FROM%20Package2VersionCreateRequest%20WHERE%20Id%20%3D%20%2708c5G000000PCXXXXX%27%20ORDER%20BY%20CreatedDate failed, reason: Client network socket disconnected before secure TLS connection was established\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfError.js:61:25)\n    at PackageVersionCreateCommand.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:255:44)\n    at async PackageVersionCreateCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:93:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
  "warnings": [],
  "commandName": "PackageVersionCreateCommand"
}

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here

$ sfdx version --json
{
        "cliVersion": "sfdx-cli/7.160.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.2"
}
C02Z91V3LVDQ:proact_base wra1365$ sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.160.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.2",
        "pluginVersions": [
                "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.3",
                "@oclif/plugin-autocomplete 1.3.0",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-diff 0.0.6",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 1.1.0 (core)",
                "auth 2.2.2 (core)",
                "bbdoc 4.0.5",
                "community 2.0.0 (core)",
                "config 1.4.14 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.3 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdmu 4.15.0",
                "sfdx-cli 7.160.0 (core)",
                "sfdx-flowdoc-plugin 0.5.1",
                "sfdx-waw-plugin 1.5.0",
                "sfpowerkit 4.2.11",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/plugin-streaming 1.1.7",
                "└─ @mshanemc/sfdx-sosl 1.1.0",
                "signups 1.2.0 (core)",
                "source 2.0.7 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Darwin 21.6.0"
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by MarcDBehr** [comment]
It appears that this may have been a temporary Salesforce glitch, as it is now working again.
