### ISSUE TITLE
"INVALID_OPERATION: Too many files in zip" on sfdx force:source:push

### ISSUE THREAD

**Issue by nzhdanova-intellective** [forcedotcom/cli#1674]
My old scratch org expired and I created a new one. However, started getting the following error on **sfdx force:source:push** command:

```
ERROR running force:source:push:  INVALID_OPERATION: Too many files in zip
*** Internal Diagnostic ***

sf:INVALID_OPERATION: INVALID_OPERATION: Too many files in zip
    at Function.wrap (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\core\lib\sfError.js:61:25)
    at Push.catch (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\command\lib\sfdxCommand.js:267:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Push._run (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\command\lib\sfdxCommand.js:93:13)
    at async Config.runCommand (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\core\lib\config\config.js:272:25)
    at async run (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\core\lib\main.js:76:5)
******

```

Before creating a new org I updated sfdx cli from 7.161.0 to 7.163.0. Tried to to downgrade it later and re-install completely, that didn't work.

Result of **sfdx version --verbose --json**                                                                                                        
```
{                                                                                                                                                              
 "cliVersion": "sfdx-cli/7.163.0",                                                                                                                            
 "architecture": "win32-x64",                                                                                                                                 
 "nodeVersion": "node-v16.15.1",                                                                                                                              
 "pluginVersions": [                                                                                                                                           
       "@oclif/plugin-autocomplete 1.3.0 (core)",                                                                                                                    
       "@oclif/plugin-commands 2.2.0 (core)",                                                                                                                       
       "@oclif/plugin-help 5.1.12 (core)",                                                                                                                           
       "@oclif/plugin-not-found 2.3.1 (core)",                                                                                                                       
       "@oclif/plugin-plugins 2.1.0 (core)",                                                                                                                        
       "@oclif/plugin-update 3.0.0 (core)",                                                                                                                         
       "@oclif/plugin-version 1.1.1 (core)",                                                                                                                         
       "@oclif/plugin-warn-if-update-available 2.0.4 (core)",                                                                                                        
       "@oclif/plugin-which 2.1.0 (core)",                                                                                                                           
       "alias 2.1.0 (core)",                                                                                                                                         
       "apex 1.1.0 (core)",                                                                                                                                        
       "auth 2.2.3 (core)",                                                                                                                                          
       "community 2.0.0 (core)",                                                                                                                                   
       "config 1.4.17 (core)",                                                                                                                                       
       "custom-metadata 2.0.0 (core)",                                                                                                                               
       "data 2.1.1 (core)",                                                                                                                                          
       "generator 2.0.2 (core)",                                                                                                                                     
       "info 2.0.1 (core)",                                                                                                                                          
      "limits 2.0.1 (core)",                                                                                                                                        
      "org 2.0.7 (core)",                                                                                                                                          
      "schema 2.1.1 (core)",                                                                                                                                      
      "signups 1.2.0 (core)",                                                                                                                                      
      "source 2.0.11 (core)",                                                                                                                                    
      "telemetry 2.0.0 (core)",                                                                                                                                  
      "templates 55.1.0 (core)",                                                                                                                                
      "trust 2.0.3 (core)",                                                                                                                                   
      "user 2.1.0 (core)",                                                                                                                                     
      "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",                                                                                               
      "salesforce-alm 54.7.1 (core)"                                                                                                                              
 ],                                                                                                                                                            
 "osVersion": "Windows_NT 10.0.19043"                                                                                                                        
}                                                                                                                                                              
```

**sfdx force:source:status** gives 487 lines, so I guess I have 487 files to push.

Any ideas on what may cause the error and how it can be solved?

**Comment by mdonnalley** [comment]
@nzhdanova-intellective the metadata api has an upper limit of 10,000 files per deploy: https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_metadata.htm

Since you're running `sfdx force:source:push` on a brand new scratch org it's likely going to push all of your source files to the new org. If you have more than 10,000 source files, you're going to hit the `INVALID_OPERATION: Too many files in zip` error.

To work around this you might want to try pushing individual parts of project one at a time

**Comment by nzhdanova-intellective** [comment]
@mdonnalley, thank you for reply. I have ~500 files, that seems to be under the limit

**Comment by mdonnalley** [comment]
Thanks @nzhdanova-intellective 

It's still possible that the size of the zip file is exceeds the limit, even if you are under 10,000 files. According to the docs, the limit is 39mb

Can you try pushing your source in smaller chunks to see if that resolves the issue for you?

**Comment by nzhdanova-intellective** [comment]
@mdonnalley did I get it right, that I need to include some folders in .forceignore to check it? Or it there a better way to accomplish it?

**Comment by nzhdanova-intellective** [comment]
![image](https://user-images.githubusercontent.com/69501668/185184207-ad360559-5b06-46c8-9f76-ca765697bb40.png)
Here is a size of main project folder

**Comment by mdonnalley** [comment]
@nzhdanova-intellective I think the easiest approach would be to use `sfdx force:source:deploy` and pass in individual folders using the `-p` flag, e.g.

`sfdx force:source:deploy -p path-1`
`sfdx force:source:deploy -p path-2`
etc...

**Comment by nzhdanova-intellective** [comment]
@mdonnalley I tried to deploy folders one by one, and all was fine till I initiated deploy operation for aura folder:

**sfdx force:source:deploy -p force-app\main\default\aura**

```
ERROR running force:source:deploy:  Deploy failed.
*** Internal Diagnostic ***

DeployFailed: Deploy failed.
    at DeployResultFormatter.display (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\lib\formatters\deployResultFormatter.js:68:19)
    at Deploy.formatResult (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\lib\commands\force\source\deploy.js:150:23)
    at Deploy.run (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\lib\commands\force\source\deploy.js:35:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Deploy._run (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\command\lib\sfdxCommand.js:89:40)
    at async Config.runCommand (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\core\lib\config\config.js:272:25)
    at async run (C:\Users\nzhdanova\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\core\lib\main.js:76:5)
******

```

Couldn't find error description. Any idea on what may cause it?

**Comment by mdonnalley** [comment]
@nzhdanova-intellective It's possible that the metadata you're deploying depends on another piece of metadata that hasn't been deployed yet

**Comment by nzhdanova-intellective** [comment]
@mdonnalley for other folders it showed me the missing component. For aura it's unclear what may be missing.  Is it possible to find out what metadata is required?
Btw, I have some structure under aura folder, **com > organization name > product > component groups**. And components are located under component groups folders. May it cause the problem? (previously that worked fine)

**Comment by nzhdanova-intellective** [comment]
By some reason I'm getting error even when try to deploy a simple event component, which doesn't have any dependencies:
**sfdx force:source:deploy -p force-app\main\default\aura\com\organization\product\event\CheckCmpPresenceEvent**

```
*** Deploying with SOAP API v49.0 ***                                                                                                                         
Deploy ID: 0Af1g00001PvL7rCAF                                                                                                                                                                                                                                                                                               
=== Component Failures [0]                                                                                                                                                                                                                                                                                                   
Type Name Problem                                                                                                                                             ──── ──── 
───────                                                                                                                                                                                                                                                                                                          
ERROR running force:source:deploy:  Deploy failed.                                                                                                             
```

**Comment by nzhdanova-intellective** [comment]
Does anyone has any idea why it may fail? It seems strange, that even the component with no dependencies can't be deployed. Is it because of folders structure? Is there any way to troubleshoot it?

**Comment by nzhdanova-intellective** [comment]
Here is an error I see when try to deploy aura components, which doesn't have any dependencies:

C:\projects\sf-app>sfdx force:source:deploy -p force-app\main\default\aura\com\organization\product\event --json                                          
"errorMessage": "UNKNOWN_EXCEPTION: Unable to handle Aura Definition 'com/organization/product/event/CmpPillRemoveEvent/CmpPillRemoveEvent.evt': filepath not expected",

Updated sfdx to 7.165.0

**Comment by iowillhoit** [comment]
Hey @nzhdanova-intellective, could you try installing `7.161.0` from a TAR file (not `npm`) and see if you still having this issue? 
- Instructions on installing from a TAR file can be found [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux). 
- The download urls of older versions can be found in the JSON files [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_olderversions)

**Comment by nzhdanova-intellective** [comment]
@iowillhoit, thank you for the suggestion. I've installed 7.161.0 from TAR file. Unfortunately that didn't work for me. I also tried to use 7.158.1 version. After calling **sfdx force:source:push** for 7.158.1 I see the following info in logs: "errno":-4066,"code":"EMFILE","syscall":"open"

One more detail. After creating new org, I run **npm install** and it gave me errors. After that I run **yarn install** and it was completed successfully. This is something we do pretty rare, as it's only for tests. Not sure if it can be related somehow... Can there be some conflicting dependencies? Or maybe you'll suggest other ideas / options for troubleshooting?

Here is my package.json file:
```
{
  "name": "salesforce-app",
  "private": true,
  "version": "1.0.0",
  "description": "Salesforce App",
  "scripts": {
    "lint": "npm run lint:lwc && npm run lint:aura",
    "lint:aura": "eslint **/aura/**",
    "lint:lwc": "eslint **/lwc/**",
    "test": "npm run test:unit",
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    "test:unit:coverage": "sfdx-lwc-jest --coverage",
    "prettier": "prettier --write \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
    "prettier:verify": "prettier --list-different \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\""
  },
  "devDependencies": {
    "@prettier/plugin-xml": "^0.12.0",
    "@salesforce/eslint-config-lwc": "^0.7.0",
    "@salesforce/eslint-plugin-aura": "^1.4.0",
    "@salesforce/sfdx-lwc-jest": "^0.9.2",
    "eslint": "^7.6.0",
    "eslint-config-prettier": "^6.11.0",
    "husky": "^4.2.1",
    "lint-staged": "^10.0.7",
    "prettier": "^2.0.5",
    "prettier-plugin-apex": "^1.6.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}": [
      "prettier --write"
    ],
    "**/{aura|lwc}/**": [
      "eslint"
    ]
  }
}

```

**Comment by nzhdanova-intellective** [comment]
Steps to reproduce the issue from scratch:
1) create a new project
2) create new aura component in force-app/main/default/aura
3) run pushing (**sfdx force:source:push**)
Result: all is fine
4) create the following folder structure: force-app/main/default/aura/com/organization/product/event
5) create new aura event in event folder. If the event name is TestEvent, it should be located in force-app/main/default/aura/com/organization/product/event/TestEvent
6) run deploy command:
**sfdx force:source:deploy -p force-app\main\default\aura\com\organization\product\event --json**
Result: UNKNOWN_EXCEPTION: Unable to handle Aura Definition 'com/organization/product/event/TestEvent/TestEvent.cmp': filepath not expected
**sfdx force:source:push** pushes nothing, it seems like this type of structure isn't tracked anymore.

Grouping components into folders worked before. We have many components in our project and it's inconvenient to keep them all in 1 folder, so we created this folder structure and grouped the components into different folders.

**Comment by nzhdanova-intellective** [comment]
Did I get it right that grouping components into folders is not available anymore? Will it be fixed?
