### ISSUE TITLE
Node 12 does not support null coalescing operator

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#1741]
### Summary

Running sfdx with node 12 no longer works

### Steps To Reproduce:

1.  Have node 12 setup
1.  install sfdx cli `npm i -g sfdx-cli@7.96.1`
1. run `sfdx --version`

### Expected result

The version of sfdx is displayed

### Actual result

```
/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/env.js:18
    constructor(store = process?.env || {}) {
                                ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/index.js:25:14)
    at Module._compile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
- bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`

```
 sfdx version --verbose --json
/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/env.js:18
    constructor(store = process?.env || {}) {
                                ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/index.js:25:14)
    at Module._compile (/Users/kevinwatson/.fnm/node-versions/v12.22.12/installation/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by cristiand391** [comment]
Hey @Kevmo92  node v12 isn't supported anymore.

We bundle the current LTS node with our installers and support node >= current maintenance for npm installs.

See:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm
https://github.com/nodejs/release#release-schedule

**Comment by Kevmo92** [comment]
> Hey @Kevmo92 node v12 isn't supported anymore.
> 
> We bundle the current LTS node with our installers and support node >= current maintenance for npm installs.
> 
> See: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm https://github.com/nodejs/release#release-schedule

@cristiand391 I understand the latest version of sfdx doesn't work with node 12. However the `7.96.1` was working with node 12 until this dependency was updated yesterday https://www.npmjs.com/package/@salesforce/kit

Before that it was using `(process && process.env)` but the new version uses `process?.env`. So it seems like the sfdx dependencies aren't locked and this is causing the error when running 7.96.1 now

**Comment by ChaseBowen** [comment]
We have large codebases that we are currently in the process of converting off of node 12 now to newer versions. This sfdx version was the last one to support node 12 and it has been working fine until a recent dependency update. Why are dependency versions being updated on an older version of sfdx? I assumed those dependency versions would be pinned since this is a pinned version of sfdx (7.96.1)

**Comment by Kevmo92** [comment]
https://github.com/forcedotcom/kit/compare/1.6.1...1.7.0 <- breaking changes made here

**Comment by Kevmo92** [comment]
@cristiand391 ^

**Comment by cristiand391** [comment]
@Kevmo92 @ChaseBowen
we started locking dependencies with a shrinkwrap lockfile in sfdx v7.165.0, see: https://github.com/forcedotcom/cli/issues/1678

all sfdx versions installed with npm before that ⬆️ will get the latest version of dependencies because of carets, even if we revert the change made in `kit` your setup can be broken by any other dep not owned by us.

For these cases we suggest to use the tarballs during your migration as those include the dependencies, a teammate found the tarballs for sfdx v7.96.0:

linux: https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.96.0/633fe15/sfdx-v7.96.0-633fe15-linux-x64.tar.gz
darwin: https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.96.0/633fe15/sfdx-v7.96.0-633fe15-darwin-x64.tar.gz
win: https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.96.0/633fe15/sfdx-v7.96.0-633fe15-win32-x64.tar.gz

Please note that the tarballs include the node binary, if the only reason you were using an old sfdx version is because of other code requiring node v12 to be used you all should use the tarballs (or the installers found [here](https://developer.salesforce.com/tools/sfdxcli)) and install the latest stable release, it will use its own binary and you can still use v12 for other projects.

**Comment by ChaseBowen** [comment]
Thanks for the suggestions @cristiand391

**Comment by Brian-Triplett** [comment]
@cristiand391 that's super helpful and a great workaround.

By chance to you have the tar for 7.96.1?

**Comment by cristiand391** [comment]
@Brian-Triplett we don't see the tarballs listed for v7.96.1 in our server.

**Comment by Brian-Triplett** [comment]
Thanks for checking though!
