### ISSUE TITLE
Getting Syntax error in install sfdx plugin vlocity tools section

### ISSUE THREAD

**Issue by subhashini1k** [forcedotcom/cli#1746]
Using azure devops, node agent is 12.x and cfdx cli-7.73.1, while running builds getting below syntax error- in install sfdx vlocity plugin s. For reference am adding error here.
D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\env.js:25
2022-10-11T09:59:21.5502793Z     }
2022-10-11T09:59:21.5502854Z     ^
2022-10-11T09:59:21.5502910Z 
2022-10-11T09:59:21.5502989Z SyntaxError: Unexpected token '}'
2022-10-11T09:59:21.5503054Z     at new Script (vm.js:88:7)
2022-10-11T09:59:21.5503171Z     at NativeCompileCache._moduleCompile (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
2022-10-11T09:59:21.5503278Z     at Module._compile (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
2022-10-11T09:59:21.5503553Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2022-10-11T09:59:21.5503633Z     at Module.load (internal/modules/cjs/loader.js:863:32)
2022-10-11T09:59:21.5503703Z     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2022-10-11T09:59:21.5503801Z     at Module.require (internal/modules/cjs/loader.js:887:19)
2022-10-11T09:59:21.5503950Z     at require (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
2022-10-11T09:59:21.5504165Z     at Object.<anonymous> (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\index.js:25:14)
2022-10-11T09:59:21.5504332Z     at Module._compile (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
2022-10-11T09:59:21.8814811Z D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\env.js:25
2022-10-11T09:59:21.8816635Z     }
2022-10-11T09:59:21.8816770Z     ^
2022-10-11T09:59:21.8816840Z 
2022-10-11T09:59:21.8816906Z SyntaxError: Unexpected token '}'
2022-10-11T09:59:21.8817018Z     at new Script (vm.js:88:7)
2022-10-11T09:59:21.8817176Z     at NativeCompileCache._moduleCompile (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
2022-10-11T09:59:21.8817335Z     at Module._compile (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
2022-10-11T09:59:21.8818371Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2022-10-11T09:59:21.8818515Z     at Module.load (internal/modules/cjs/loader.js:863:32)
2022-10-11T09:59:21.8818655Z     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2022-10-11T09:59:21.8818781Z     at Module.require (internal/modules/cjs/loader.js:887:19)
2022-10-11T09:59:21.8818870Z     at require (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
2022-10-11T09:59:21.8818991Z     at Object.<anonymous> (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\index.js:25:14)
2022-10-11T09:59:21.8819089Z     at Module._compile (D:\Agents\Agent2\_work\_tool\node\12.22.12\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
Note:its impacting project deliverables, could you please suggest on this
thanks

**Comment by mshanemc** [comment]
did this go away?  FYI, node 12 isn't supported by node anymore, so SalesforceCLI doesn't support it either

**Comment by subhashini1k** [comment]
the issue is resolved, i used 14 as node. Thanks for reply
