### ISSUE TITLE
Org-Dependent package says that custom fields don't exist

### ISSUE THREAD

**Issue by MarcDBehr** [forcedotcom/cli#1765]
### Summary

When installing an org dependent package, it does not appear that custom fields that part of the package are being included in the package.

I am creating an org-dependent package that includes custom fields on several objects (Account and Opportunity). The package creation works fine, but when I attempt to install the package, I get error messages that say that the fields that should be part of the package don't exist.

Package Folder:

![image](https://user-images.githubusercontent.com/3748097/196728768-54951517-ad8f-475b-8d1a-e58ae7da514e.png)

After creating the package, when I try to install it, I get:

```
$ sfdx force:package:install -b 5 -w 10 -p 04t5G00000xxxxxxxx -u qa
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
ERROR:  Encountered errors installing the package!,Installation errors: 
1) An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.Classification_EU__c: An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory
2) An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.EU_CDB_Number__c: An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory
```

### Steps To Reproduce:

Create a org-dependent package that includes new custom fields, then try to install that package

### Expected result

Package is installed sucessfully

### Actual result

Error message indicating that custom fields don't exist 

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`

```
{
  "cliVersion": "sfdx-cli/7.172.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.13.2",
  "pluginVersions": [
    "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.3 (user)",
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 1.3.1 (user)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.14 (core)",
    "@oclif/plugin-not-found 2.3.3 (core)",
    "@oclif/plugin-plugins 2.1.1 (core)",
    "@oclif/plugin-update 3.0.2 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.6 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.5 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.13 (core)",
    "community 2.0.3 (core)",
    "config 1.4.21 (core)",
    "custom-metadata 2.0.1 (core)",
    "data 2.1.4 (core)",
    "generator 2.0.5 (core)",
    "info 2.1.9 (core)",
    "limits 2.0.5 (core)",
    "org 2.2.7 (core)",
    "packaging 1.9.4 (core)",
    "schema 2.1.10 (core)",
    "signups 1.2.7 (core)",
    "source 2.0.17 (core)",
    "telemetry 2.0.2 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.10 (core)",
    "@salesforce/sfdx-diff 0.0.6 (user)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "bbdoc 4.0.5 (user)",
    "salesforce-alm 54.8.1 (core)",
    "sfdmu 4.17.2 (user)",
    "sfdx-flowdoc-plugin 0.5.1 (user)",
    "sfdx-waw-plugin 1.5.0 (user)",
    "sfdxdatadicgen 0.1.2 (user)",
    "sfpowerkit 6.0.0 (user)",
    "shane-sfdx-plugins 4.43.0 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "bash",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli"
}
```
### Additional information

trace level attempted install

```
$ sfdx force:package:install -b 5 -w 10 -p 04t5G00000xxxxxxxx -u qa --json --loglevel=trace
ERROR:  Encountered errors installing the package!,Installation errors: 
1) An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.Classification_EU__c: An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory
2) An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.EU_CDB_Number__c: An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory
{
  "status": 1,
  "name": "",
  "message": "Installation errors: \n1) An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.Classification_EU__c: An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory\n2) An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.EU_CDB_Number__c: An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory",
  "exitCode": 1,
  "context": "PackageInstallCommand",
  "stack": "Installation errors: \n1) An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.Classification_EU__c: An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory\n2) An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.EU_CDB_Number__c: An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfError.js:61:25)\n    at PackageInstallCommand.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:255:44)\n    at async PackageInstallCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:106:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25)\n    at async run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:76:5)\nCaused by: Error: Installation errors: \n1) An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.Classification_EU__c: An object 'Account.Classification_EU__c' of type CustomField was named in package.xml, but was not found in zipped directory\n2) An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory, Details: Account.EU_CDB_Number__c: An object 'Account.EU_CDB_Number__c' of type CustomField was named in package.xml, but was not found in zipped directory\n    at /usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/package/packageInstallCommand.js:95:27\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "warnings": [],
  "commandName": "PackageInstallCommand"
}
```

**Comment by 6ithu8u53r** [comment]
We had same error message when running create package version command after cli updated to 7.171.0; see [Issue 1742](https://github.com/forcedotcom/cli/issues/1742).  Try downgrading cli to version 7.170.0.

**Comment by MarcDBehr** [comment]
I downgraded to version 7.170.0 and recreated the package and now it installs fine. Appreciate the pointer @6ithu8u53r
I am going to leave the bug open so it can be checked with whatever the fix ends up being

**Comment by WillieRuemmele** [comment]
Hi @MarcDBehr - I'm going to close this issue and use the original. We'll make sure this is tracked with the original issue
