### ISSUE TITLE
sfdx force:source:retrieve taking 30+ min to run

### ISSUE THREAD

**Issue by blake-yolabs** [forcedotcom/cli#1787]
Trying to retrieve a single file via sfdx force:source:retrieve is taking over 30 min to run then times out. This is only happening for one of my orgs others are fine. 

The problem org is: yolabs--dev.sandbox.my.salesforce.com Instance | CS44

SFDX CLI version - sfdx-cli/7.175.0 darwin-x64 node-v18.12.0

I attempted running with `--dev-debug --loglevel=trace` as mentioned it [this comment](https://github.com/forcedotcom/cli/issues/18#issuecomment-455954825) but no log file was created. 

Here is the end of the trace out put in terminal 

```
sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +460ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +2ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +306ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +145ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +459ms
  sf:core TRACE Setup child 'MyDomainResolver' logger instance +459ms
  sf:core TRACE Setup child 'PollingClient' logger instance +0ms
  sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +457ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +2ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +315ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +155ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +544ms
  sf:core TRACE Setup child 'MyDomainResolver' logger instance +546ms
  sf:core TRACE Setup child 'PollingClient' logger instance +0ms
  sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +544ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +2ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +391ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +204ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +587ms
  sf:core TRACE Setup child 'MyDomainResolver' logger instance +584ms
  sf:core TRACE Setup child 'PollingClient' logger instance +0ms
  sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +582ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +2ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +379ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +290ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +620ms
  sf:core TRACE Setup child 'MyDomainResolver' logger instance +621ms
  sf:core TRACE Setup child 'PollingClient' logger instance +0ms
  sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +619ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +1ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +330ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +159ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +945ms
  sf:core TRACE Setup child 'MyDomainResolver' logger instance +944ms
  sf:core TRACE Setup child 'PollingClient' logger instance +1ms
  sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +944ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +1ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +787ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +156ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +485ms
  sf:core TRACE Setup child 'MyDomainResolver' logger instance +486ms
  sf:core TRACE Setup child 'PollingClient' logger instance +0ms
  sf:MyDomainResolver DEBUG Attempting to resolve url: yolabs--dev.sandbox.my.salesforce.com +485ms
  sf:MyDomainResolver DEBUG Successfully resolved host: yolabs--dev.sandbox.my.salesforce.com result: {"address":"13.110.3.196","family":4} +2ms
  sf:connection DEBUG request: {"method":"GET","url":"https://yolabs--dev.sandbox.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +330ms
  sf:connection DEBUG response for org versions: 31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0 +1s
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +2s
  sfdx:Lifecycle A lifecycle event with the name POLLING_TIME_OUT does not exist. An event must be registered before it can be emitted. +33m
  sf:PollingClient DEBUG Polling timed out +0ms
ERROR running force:source:retrieve:  Metadata API request failed: The client has timed out. 
*** Internal Diagnostic ***

MetadataTransferError: Metadata API request failed: The client has timed out.
    at MetadataApiRetrieve.pollStatus (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataTransfer.js:83:27)
    at async Retrieve.retrieve (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:97:31)
    at async Retrieve.run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:29:9)
    at async Retrieve._run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)
    at async Config.runCommand (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/main.js:76:5)
DUE TO:
PollingClientTimeout: The client has timed out.
    at PollingClient.subscribe (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/core/lib/status/pollingClient.js:91:19)
    at async MetadataApiRetrieve.pollStatus (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataTransfer.js:71:43)
    at async Retrieve.retrieve (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:97:31)
    at async Retrieve.run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:29:9)
    at async Retrieve._run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)
    at async Config.runCommand (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/main.js:76:5)
******

  sf:Retrieve ERROR [
  sf:Retrieve   '\x1B[1mERROR running force:source:retrieve: \x1B[22m',
  sf:Retrieve   '\x1B[31mMetadata API request failed: The client has timed out.\x1B[39m',
  sf:Retrieve   '\x1B[31m\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m*** Internal Diagnostic ***\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m\x1B[39m\n' +
  sf:Retrieve     '\x1B[31mMetadataTransferError: Metadata API request failed: The client has timed out.\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at MetadataApiRetrieve.pollStatus (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataTransfer.js:83:27)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Retrieve.retrieve (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:97:31)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Retrieve.run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:29:9)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Retrieve._run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Config.runCommand (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/config/config.js:272:25)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/main.js:76:5)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31mDUE TO:\x1B[39m\n' +
  sf:Retrieve     '\x1B[31mPollingClientTimeout: The client has timed out.\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at PollingClient.subscribe (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/core/lib/status/pollingClient.js:91:19)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async MetadataApiRetrieve.pollStatus (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataTransfer.js:71:43)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Retrieve.retrieve (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:97:31)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Retrieve.run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/plugin-source/lib/commands/force/source/retrieve.js:29:9)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Retrieve._run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async Config.runCommand (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/config/config.js:272:25)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m    at async run (/Users/bt61056/.local/share/sfdx/client/7.175.0-a62760c/node_modules/@oclif/core/lib/main.js:76:5)\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m******\x1B[39m\n' +
  sf:Retrieve     '\x1B[31m\x1B[39m'
  sf:Retrieve ] +33m

```

**Comment by mshanemc** [comment]
Sounds like that instance is having some performance problems.

If it persists, you can set the `--wait` on that command (default is like 33 min) to avoid the timeout.
