### ISSUE TITLE
Error when creating Scratch Org: Settings won't deploy

### ISSUE THREAD

**Issue by patmcclellan** [forcedotcom/cli#1826]
Trying to create a new scratch org, using the same definition file I've used dozens of times.

I'm using VS Code's actions menu to create the org, which results in this cli:
`sfdx force:org:create -f config/project-scratch-def.json --setalias nov28 --durationdays 30 --setdefaultusername --json --loglevel fatal`

It results in this error:
`A scratch org was created with username test-whatever@example.com, but the settings failed to deploy due to: 
Not available for deploy for this API version`

This is my def file:
```
{
    "orgName": "Proton7Group",
    "hasSampleData": true,
    "edition": "Enterprise",
    "namespace": "mynamespace",
    "features": ["Communities", "PartnerCommunity", "ForceComPlatform"],
    "settings": {
        "orgPreferenceSettings": {
            "s1DesktopEnabled": true,
            "s1EncryptedStoragePref2": false
        },
        "communitiesSettings": {
            "enableNetworksEnabled": true
        }
    }
}
```
If I remove the settings property from the def, it will create a scratch org with the alias, but I get dozens of errors trying to push source to the scratch org.

**Comment by patmcclellan** [comment]
I ran this, changing the log level to trace, same result, but lots more info:
```
{
  "result": {
    "checkOnly": false,
    "completedDate": "2022-11-28T17:15:52.000Z",
    "createdBy": "0057A000005fu47",
    "createdByName": "User User",
    "createdDate": "2022-11-28T17:15:40.000Z",
    "details": {
      "componentFailures": [
        {
          "changed": false,
          "componentType": "OrgPreferenceSettings",
          "created": false,
          "createdDate": "2022-11-28T17:15:47.000Z",
          "deleted": false,
          "fileName": "shape_1669655701254/settings/OrgPreference.settings",
          "fullName": "settings/OrgPreference.settings",
          "problem": "Not available for deploy for this API version",
          "problemType": "Error",
          "success": false
        }
      ],
      "componentSuccesses": [
        {
          "changed": true,
          "componentType": "",
          "created": false,
          "createdDate": "2022-11-28T17:15:51.000Z",
          "deleted": false,
          "fileName": "shape_1669655701254/package.xml",
          "fullName": "package.xml",
          "success": true
        },
        {
          "changed": true,
          "componentType": "CommunitiesSettings",
          "created": false,
          "createdDate": "2022-11-28T17:15:51.000Z",
          "deleted": false,
          "fileName": "shape_1669655701254/settings/Communities.settings",
          "fullName": "Communities",
          "success": true
        }
      ],
      "runTestResult": {
        "numFailures": 0,
        "numTestsRun": 0,
        "totalTime": 0,
        "codeCoverage": [],
        "codeCoverageWarnings": [],
        "failures": [],
        "flowCoverage": [],
        "flowCoverageWarnings": [],
        "successes": []
      }
    },
    "done": true,
    "id": "0Af7A00001XsktXSAR",
    "ignoreWarnings": false,
    "lastModifiedDate": "2022-11-28T17:15:52.000Z",
    "numberComponentErrors": 1,
    "numberComponentsDeployed": 1,
    "numberComponentsTotal": 2,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": false,
    "runTestsEnabled": false,
    "startDate": "2022-11-28T17:15:41.000Z",
    "status": "SucceededPartial",
    "success": true
  },
  "status": 1,
  "name": "ProblemDeployingSettings",
  "message": "A scratch org was created with username test-dxt3faisnnf0@example.com, but the settings failed to deploy due to: \nNot available for deploy for this API version",
  "exitCode": 1,
  "context": "Create",
  "data": {
    "checkOnly": false,
    "completedDate": "2022-11-28T17:15:52.000Z",
    "createdBy": "0057A000005fu47",
    "createdByName": "User User",
    "createdDate": "2022-11-28T17:15:40.000Z",
    "details": {
      "componentFailures": [
        {
          "changed": false,
          "componentType": "OrgPreferenceSettings",
          "created": false,
          "createdDate": "2022-11-28T17:15:47.000Z",
          "deleted": false,
          "fileName": "shape_1669655701254/settings/OrgPreference.settings",
          "fullName": "settings/OrgPreference.settings",
          "problem": "Not available for deploy for this API version",
          "problemType": "Error",
          "success": false
        }
      ],
      "componentSuccesses": [
        {
          "changed": true,
          "componentType": "",
          "created": false,
          "createdDate": "2022-11-28T17:15:51.000Z",
          "deleted": false,
          "fileName": "shape_1669655701254/package.xml",
          "fullName": "package.xml",
          "success": true
        },
        {
          "changed": true,
          "componentType": "CommunitiesSettings",
          "created": false,
          "createdDate": "2022-11-28T17:15:51.000Z",
          "deleted": false,
          "fileName": "shape_1669655701254/settings/Communities.settings",
          "fullName": "Communities",
          "success": true
        }
      ],
      "runTestResult": {
        "numFailures": 0,
        "numTestsRun": 0,
        "totalTime": 0,
        "codeCoverage": [],
        "codeCoverageWarnings": [],
        "failures": [],
        "flowCoverage": [],
        "flowCoverageWarnings": [],
        "successes": []
      }
    },
    "done": true,
    "id": "0Af7A00001XsktXSAR",
    "ignoreWarnings": false,
    "lastModifiedDate": "2022-11-28T17:15:52.000Z",
    "numberComponentErrors": 1,
    "numberComponentsDeployed": 1,
    "numberComponentsTotal": 2,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": false,
    "runTestsEnabled": false,
    "startDate": "2022-11-28T17:15:41.000Z",
    "status": "SucceededPartial",
    "success": true
  },
  "stack": "ProblemDeployingSettings: A scratch org was created with username test-dxt3faisnnf0@example.com, but the settings failed to deploy due to: 
Not available for deploy for this API version
    at SettingsGenerator.deploySettingsViaFolder (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@salesforce/core/lib/org/scratchOrgSettingsGenerator.js:229:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploySettings (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:336:13)
    at async Promise.all (index 1)
    at async scratchOrgCreate (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:181:24)
    at async Create.createScratchOrg (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68)
    at async Create._run (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)
    at async Config.runCommand (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async run (/Users/patmcclellan/.local/share/sfdx/client/7.178.0-ce727f2/node_modules/@oclif/core/lib/main.js:74:5)"
  "warnings": [
    "apiVersion configuration overridden at \"54.0\""
  ],
  "commandName": "Create"
}
```

**Comment by patmcclellan** [comment]
Changed my settings in the def file and it works:
```
 "settings": {
        "mobileSettings": {
            "enableS1EncryptedStoragePref2": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "communitiesSettings": {
            "enableNetworksEnabled": true
        }
    }
```

**Comment by cristiand391** [comment]
`OrgPreferenceSettings` was removed in API 48.0: https://developer.salesforce.com/docs/atlas.en-us.238.0.api_meta.meta/api_meta/meta_orgpreferencesettings.htm

`Trying to create a new scratch org, using the same definition file I've used dozens of times.`

I think the old `force:org:create` had some code to transform it/set the right api version, we switched to a new implementation of that command in v7.164.2: https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71642-aug-18-2022

maybe you just updated from an old version?

**Comment by peternhale** [comment]
Thanks @cristiand391. I am going to close this issue.
