### ISSUE TITLE
UNKNOWN_EXCEPTION for Group Edition Scratch Orgs

### ISSUE THREAD

**Issue by johnzhao9** [forcedotcom/cli#187]
### Summary

In the terminal, trying to create a Group Edition scratch org and interact with it with SFDX but getting an unknown exception.

SFDX version is the latest as of now:
```
root@24818b8f6793:/# sfdx update
sfdx-cli: Updating CLI... already on latest version: 7.25.3-16d54c01ee
root@24818b8f6793:/# sfdx version
sfdx-cli/7.25.3-16d54c01ee linux-x64 node-v10.15.3
root@24818b8f6793:/# sfdx plugins --core
...(omitted)
salesforcedx 46.15.3 (core)
├─ force-language-services 46.22.0 (core)
└─ salesforce-alm 46.20.0 (core)
```

### Steps To Reproduce:

1.  Create a group edition org definition file. The `features` block is optional.
```
{
"orgName":"getest",
"edition":"Group",
"features":[
"API",
"AuthorApex"
]
}
```
2. Create the org with `sfdx force:org:create -d 1 -f f.json -a a`
3. Run any command against the created org, such as `sfdx force:org:open -u a` or `sfdx force:org:display -u a`

### Expected result
The commands run successfully

### Actual result

Got this error message
```
ERROR running force:org:display:  An unexpected error occurred. Please include this ErrorId if you contact support: 1934940418-16149 (-1294006151)
```
and in JSON
```
{
    "status": 1,
    "name": "UNKNOWN_EXCEPTION",
    "message": "An unexpected error occurred. Please include this ErrorId if you contact support: 2087920329-57512 (-1294006151)",
    "exitCode": 1,
    "commandName": "OrgDisplayCommand",
    "stack": "UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 2087920329-57512 (-1294006151)\n    at HttpApi.getError (/root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/salesforce-alm/node_modules/jsforce/lib/http-api.js:250:13)\n    at /root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/salesforce-alm/node_modules/jsforce/lib/http-api.js:95:22\n    at tryCallOne (/root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/promise/lib/core.js:37:12)\n    at /root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/promise/lib/core.js:123:15\n   at flush (/root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/asap/raw.js:50:29)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\nOuter stack:\n    at Function.wrap (/root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at OrgDisplayCommand.catch (/root/.local/share/sfdx/client/7.25.3-16d54c01ee/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)",
    "warnings": []
}
```

### Additional information

![image](https://user-images.githubusercontent.com/13734035/65700217-e243c180-e044-11e9-9d1e-7de6a3f21bca.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.25.3-16d54c01ee linux-x64 node-v10.15.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.15.3 (core)
├─ force-language-services 46.22.0 (core)
└─ salesforce-alm 46.20.0 (core)

sfdx-cli 7.25.3 (core)
```

**OS and version**:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by johnzhao9** [comment]
SF support has helped us to submit the bug and the fix is being scheduled:
https://success.salesforce.com/issues_view?id=a1p3A0000003ey0QAA
