### ISSUE TITLE
sfdx force org open displays error message

### ISSUE THREAD

**Issue by MarcDBehr** [forcedotcom/cli#1903]
### Summary

Getting an error when opening a org using 'sfdx force open -u [org]' command

### Steps To Reproduce:

When I try to open an org using the command 'sfdx force org open -u [org]' I get an error (but the command sucessfully completes) 

### Expected result

Org opens without any error message

### Actual result

```
$ sfdx force org open -u xxx
Opening org 00D7f000000XXXXXXX as user user@ccc.xxx
CLIError: timed out
    at Object.error (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:124:9) {
  oclif: { exit: 2 },
  code: undefined
}
Waiting to resolve the Lightning Experience-enabled custom domain...... done
```

And then the org opens successfully 

### System Information

```
{
  "versionDetail": {
    "cliVersion": "sfdx-cli/7.185.0",
    "architecture": "darwin-x64",
    "nodeVersion": "node-v16.13.2",
    "pluginVersions": [
      "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.4 (user)",
      "@mshanemc/plugin-streaming 1.1.7 (user)",
      "@mshanemc/sfdx-sosl 1.1.0 (user)",
      "@oclif/plugin-autocomplete 1.4.2 (user)",
      "@oclif/plugin-commands 2.2.2 (core)",
      "@oclif/plugin-help 5.1.22 (core)",
      "@oclif/plugin-not-found 2.3.13 (core)",
      "@oclif/plugin-plugins 2.1.8 (core)",
      "@oclif/plugin-search 0.0.8 (core)",
      "@oclif/plugin-update 3.0.9 (core)",
      "@oclif/plugin-version 1.1.4 (core)",
      "@oclif/plugin-warn-if-update-available 2.0.19 (core)",
      "@oclif/plugin-which 2.2.6 (core)",
      "alias 2.1.18 (core)",
      "apex 1.4.2 (core)",
      "auth 2.3.12 (core)",
      "community 2.1.3 (core)",
      "config 1.4.23 (core)",
      "custom-metadata 2.0.11 (core)",
      "data 2.1.22 (core)",
      "generator 2.0.16 (core)",
      "info 2.3.3 (core)",
      "limits 2.2.3 (core)",
      "org 2.2.22 (core)",
      "packaging 1.12.3 (core)",
      "schema 2.2.2 (core)",
      "signups 1.2.12 (core)",
      "source 2.3.15 (core)",
      "telemetry 2.0.5 (core)",
      "templates 55.2.1 (core)",
      "trust 2.2.8 (core)",
      "user 2.1.25 (core)",
      "@salesforce/sfdx-diff 0.0.6 (user)",
      "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
      "bbdoc 4.1.0 (user)",
      "salesforce-alm 54.8.5 (core)",
      "sfdmu 4.26.0 (user)",
      "sfdx-flowdoc-plugin 0.5.1 (user)",
      "sfdx-waw-plugin 1.5.0 (user)",
      "sfdxdatadicgen 0.1.3 (user)",
      "sfpowerkit 6.0.1 (user)",
      "shane-sfdx-plugins 4.43.0 (user)"
    ],
    "osVersion": "Darwin 22.3.0",
    "shell": "bash",
    "rootPath": "/usr/local/lib/node_modules/sfdx-cli"
  },
  "sfdxEnvVars": [
    [
      "SFDX_AUTOUPDATE_DISABLE",
      "true"
    ],
    [
      "SFDX_DISABLE_AUTOUPDATE",
      "true"
    ],
    [
      "SFDX_UPDATE_INSTRUCTIONS",
      "Use \"npm update --global sfdx-cli\" to update npm-based installations."
    ]
  ],
  "sfEnvVars": [],
  "cliConfig": {
    "_base": "@oclif/core@1.24.3",
    "debug": 0,
    "topicSeparator": " ",
    "warned": false,
    "commandPermutations": {
      "validPermutations": {}
    },
    "topicPermutations": {
      "validPermutations": {}
    },
    "_commands": {},
    "_topics": {},
    "root": "/usr/local/lib/node_modules/sfdx-cli",
    "name": "sfdx-cli",
    "version": "7.185.0",
    "channel": "stable",
    "valid": true,
    "arch": "x64",
    "platform": "darwin",
    "windows": false,
    "bin": "sfdx",
    "dirname": "sfdx",
    "flexibleTaxonomy": true,
    "userAgent": "sfdx-cli/7.185.0 darwin-x64 node-v16.13.2",
    "shell": "bash",
    "home": "/Users/wra1365",
    "cacheDir": "/Users/wra1365/Library/Caches/sfdx",
    "configDir": "/Users/wra1365/.config/sfdx",
    "dataDir": "/Users/wra1365/.local/share/sfdx",
    "errlog": "/Users/wra1365/Library/Caches/sfdx/error.log",
    "nodeEngine": ">=14.0.0"
  },
  "pluginSpecificData": {
    "@salesforce/plugin-source": [
      {
        "sourceApiVersion": "56.0",
        "targetDevHubApiVersion": "56.0",
        "targetOrgApiVersion": "57.0"
      }
    ]
  },
  "diagnosticResults": [
    {
      "testName": "salesforcedx plugin not installed",
      "status": "pass"
    },
    {
      "testName": "no linked plugins",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches apiVersion",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] default target DevHub max apiVersion matches default target org max apiVersion",
      "status": "warn"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches default target org max apiVersion",
      "status": "warn"
    },
    {
      "testName": "using latest or latest-rc CLI version",
      "status": "pass"
    }
  ],
  "suggestions": [
    "Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.",
    "Check http://status.salesforce.com for general Salesforce availability and performance.",
    "The max apiVersion of the default DevHub org doesn't match the max apiVersion of the default target org. This mismatch means that the default target orgs are running different API versions. Be sure you explicitly set the apiVersion when you deploy or retrieve source, or you will likely run into problems.",
    "The sourceApiVersion in sfdx-project.json doesn't match the max apiVersion of the default target org. As a result, you're not using the latest features available in API version 57.0. The version mismatch isn't a problem, as long as it's the behavior you actually want."
  ],
  "logFilePaths": []
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by petter-eikeland** [comment]
Me too, however I get it twice saying 

```
CLIError: timed out
    at Object.error (/Users/user/.local/share/sfdx/client/7.186.1-6dbe2f1/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at /Users/user/.local/share/sfdx/client/7.186.1-6dbe2f1/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/Users/user/.local/share/sfdx/client/7.186.1-6dbe2f1/node_modules/@oclif/core/lib/cli-ux/index.js:124:9) {
  oclif: { exit: 2 },
  code: undefined
}
```


However, I got it after updating to Release Candidate version. It has remained ever since, even when downgrading back to 7.185

**Comment by mshanemc** [comment]
we're trying to figure out what caused this.

**Comment by cristiand391** [comment]
Thanks for reporting!
We published a new RC with the fix (`7.186.2`). Since err doesn't affect the exit code of the command it shouldn't break scripts 👍🏼

**Comment by petter-eikeland** [comment]
Fixed for me now with 7.186.2

**Comment by MarcDBehr** [comment]
Looks good to me also with 7.186.2... thanks!

**Comment by shetzel** [comment]
This is now in the production CLI, v7.186.2
