### ISSUE TITLE
[7.186.0+] `Converting circular structure to JSON` error when creating package version without `versionName`

### ISSUE THREAD

**Issue by scolladon** [forcedotcom/cli#1914]
### Summary

`Converting circular structure to JSON` error is returned
When creating a new package version 
With the command `sfdx force:package:version:create`
Starting version `7.186.0+` (version `7.185.0` creates package version successfully)

### Steps To Reproduce:

You need a devhub authorized in your local sfdx cli.
Here it will be named `hub`

Create a project
```sh
sfdx force:project:create --projectname repro --manifest           
```

Update the `sfdx-project.json` file so it has a default `packageDirectories` with package information (do not specify `versionName`:
```json
{
  "packageDirectories": [
    {
      "path": "force-app/main/default",
      "default": true,
      "package": "repro",
      "versionNumber": "0.1.0.NEXT"
    }
  ],
  "name": "repro",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "55.0"
}
```

Add content in the packaging folder:
```sh
$ sfdx force:apex:class:create -n myclass -d force-app/main/default/classes
```

Create a package:
```sh
sfdx force:package:create --name "repro" --packagetype Unlocked --path "force-app/main/default" -v hub
```
_It is the same result if the package is Unlocked or Managed_

Create a package version:
```sh
$ sfdx force:package:version:create --definitionfile config/project-scratch-def.json --package "repro" --wait 120 --skipancestorcheck --installationkeybypass --json -v hub
```
_You can pass the `--skipvalidation` flag if you want to speed up the version creation_

### Expected result

The package version is created and the commands returns a "status": 0

### Actual result

The package version is not created and the command returns a "status": 1
```json
{
  "message": "Converting circular structure to JSON\n    --> starting at object with constructor 'Timeout'\n    |     property '_idlePrev' -> object with constructor 'TimersList'\n    --- property '_idleNext' closes the circle",
  "name": "TypeError",
  "status": 1,
  "stack": "TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Timeout'\n    |     property '_idlePrev' -> object with constructor 'TimersList'\n    --- property '_idleNext' closes the circle\n    at JSON.stringify (<anonymous>)\n    at /opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/logger.js:702:31\n    at Array.map (<anonymous>)\n    at filterSecrets (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/logger.js:691:41)\n    at /opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/logger.js:142:37\n    at /opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/logger.js:617:61\n    at Array.forEach (<anonymous>)\n    at Logger.applyFilters (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/logger.js:617:33)\n    at Logger.warn (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/logger.js:548:31)\n    at PackageVersionCreate.setPackageDescriptorJsonValues (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:595:25)\n    at PackageVersionCreate.createPackageVersionCreateRequestFromOptions (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:324:14)\n    at async PackageVersionCreate.packageVersionCreate (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:507:25)\n    at async Function.create (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersion.js:105:30)\n    at async PackageVersionCreateCommand.run (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:46:24)\n    at async PackageVersionCreateCommand._run (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:80:22)\n    at async Config.runCommand (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:298:25)",
  "exitCode": 1,
  "warnings": [
    "The \"force package version create\" command has been deprecated. Use \"package version create\" instead.",
    "The \"--definitionfile\" flag has been deprecated. Use \"--definition-file\" instead.",
    "The \"--skipancestorcheck\" flag has been deprecated. Use \"--skip-ancestor-check\" instead.",
    "The \"--installationkeybypass\" flag has been deprecated. Use \"--installation-key-bypass\" instead.",
    "The \"--skipvalidation\" flag has been deprecated. Use \"--skip-validation\" instead."
  ]
}
```

### System Information

**os:** Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
**yarn:** 1.22.15
**node:** v14.20.1
**shell:** zsh 5.8.1 (x86_64-apple-darwin22.0)
**sfdx:**
```json
{
  "cliVersion": "sfdx-cli/7.186.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v14.20.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.2 (core)",
    "@oclif/plugin-commands 2.2.3 (core)",
    "@oclif/plugin-help 5.2.1 (core)",
    "@oclif/plugin-not-found 2.3.17 (core)",
    "@oclif/plugin-plugins 2.2.4 (core)",
    "@oclif/plugin-search 0.0.11 (core)",
    "@oclif/plugin-update 3.1.0 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.23 (core)",
    "@oclif/plugin-which 2.2.9 (core)",
    "alias 2.1.19 (core)",
    "apex 1.4.3 (core)",
    "auth 2.3.12 (core)",
    "community 2.1.3 (core)",
    "config 1.4.23 (core)",
    "custom-metadata 2.0.11 (core)",
    "data 2.1.22 (core)",
    "generator 2.0.17 (core)",
    "info 2.3.5 (core)",
    "limits 2.2.3 (core)",
    "org 2.2.24 (core)",
    "packaging 1.12.4 (core)",
    "schema 2.2.3 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.16 (core)",
    "telemetry 2.0.7 (core)",
    "templates 55.2.3 (core)",
    "trust 2.3.0 (core)",
    "user 2.2.1 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 3.8.0 (user)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.23.8 (user)",
    "sfdx-git-delta 5.11.4 (user)"
  ],
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/opt/homebrew/lib/node_modules/sfdx-cli"
}
```

### Additional information

To workaround this in my CI (github action), I have created a repository variable `SFDX_VERSION`
In my github action sfdx installation step I use this variable to tell npm to install the version I want.
This way I don't have to add a new commit to change the sfdx version I want to use.

Example:
```yml
- name: Install sfdx
   run: npm install --global sfdx-cli@${{ vars.SFDX_VERSION }}
```

### Workaround

Specifying a `versionName` does not produce the error, even if this attribut is flagged as optional in the [documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_package.htm#cli_reference_force_package_version_create)

**Comment by petter-eikeland** [comment]
@scolladon Seems like you are getting the same bug as me https://github.com/forcedotcom/cli/issues/1907

Could you see whether adding the `versionName` parameter fixes the bug?

**Comment by scolladon** [comment]
You're right @petter-eikeland 

The package version is created with sfdx version `7.186.2` when adding the [optional](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_package.htm#cli_reference_force_package_version_create) `versionName` attribut in the `packageDirectories` element in the `sfdx-project.json`

I'm adding it in the potential workaround in my issue description, thanks !

Duplicate of #1907

**Comment by shetzel** [comment]
We'll use 1907 to track/fix this.

**Comment by arupsarkar-sfdc** [comment]
Error while creating a scratch org.

Error (1): The request to create a scratch org failed with error code: C-1033.
Error: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
