### ISSUE TITLE
The request to create a scratch org failed with error code: C-1033

### ISSUE THREAD

**Issue by bdovh** [forcedotcom/cli#1931]
> There's a problem affecting scratch orgs, sandboxes, packages, and more.  There are some partial workarounds.  Please follow the issue here: https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4

### Summary

```
The request to create a scratch org failed with error code: C-1033. 
at checkScratchOrgInfoForErrors (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgErrorCodes.js:76:15) 
at async pollForScratchOrgInfo (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:304:16) 
at async scratchOrgCreate (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:165:17) 
at async Create.createScratchOrg (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:151:68) 
at async Create._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:107:22) 
at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:296:25)
```

### Steps To Reproduce:

1. Using a valid 2GP project, try to create a scratch org
 

### Expected result

I expect a scratch org to be created successfully

### Actual result

It fails with an error

```
The request to create a scratch org failed with error code: C-1033. 
at checkScratchOrgInfoForErrors (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgErrorCodes.js:76:15) 
at async pollForScratchOrgInfo (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:304:16) 
at async scratchOrgCreate (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:165:17) 
at async Create.createScratchOrg (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:151:68) 
at async Create._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:107:22) 
at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:296:25) 
```

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
Github actions bash or zsh.

 
Version of SFDX CLI is: sfdx-cli/7.187.1 linux-x64 node-v16.19.0

**Comment by bdovh** [comment]
<img width="1146" alt="Screenshot 2023-02-13 at 15 19 59" src="https://user-images.githubusercontent.com/75684333/218468886-bf793472-670f-44a9-b99a-f71c8cf2a5c5.png">

**Comment by bdovh** [comment]
```
{
    "orgName": "Package Development",
    "edition": "Developer",
    "features": [],
    "settings": {
        "apexSettings": {
            "enableGaplessTestAutoNum": true, "enableDisableParallelApexTesting": true
        },
        "quoteSettings": {
            "enableQuote": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "nameSettings": {
            "enableNameSuffix": false
        },
        "mobileSettings": {
            "enableS1EncryptedStoragePref2": false
        }
    }
}
```

**Comment by bdovh** [comment]
<img width="670" alt="Screenshot 2023-02-13 at 15 21 05" src="https://user-images.githubusercontent.com/75684333/218469047-0b6e9155-fe62-4530-9e9c-06f2b3c5530e.png">

**Comment by bdovh** [comment]
```
      - name: "Create scratch org"
        id: create
        run: |
          echo $(sfdx force:org:create -f src/unpackaged/config/project-scratch-def.json -a scratch-org -s -d 1 --json) > create.json
          v=$(cat create.json | jq '.status' -r)
          if [[ $v != 0 ]] 
          then 
              echo "Create scratch org failed"
              n=$(cat create.json | jq '.name' -r)
              s=$(cat create.json | jq '.stack' -r)
              echo "Error message: $n $s"
              m="Org creation failed with error $n $s"
              echo "success=false" >> $GITHUB_OUTPUT
              mx=$(echo $m | tr '\n' ' ')
              echo "result=$mx" >> $GITHUB_OUTPUT
          else
              echo "success=true" >> $GITHUB_OUTPUT
          fi
```
<img width="1016" alt="Screenshot 2023-02-13 at 15 21 56" src="https://user-images.githubusercontent.com/75684333/218469272-5db11404-da9f-4d91-b6d9-7fb9636244f5.png">

**Comment by daveespo** [comment]
Did you check your DevHub instance against this list?

https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4

https://status.salesforce.com/incidents/10793

**Comment by bdovh** [comment]
> Did you check your DevHub instance against this list?
> 
> https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4
> 
> https://status.salesforce.com/incidents/10793

Thanks David.
Ok, two devhubs are located on NA208 and NA156 so both of them are affected by that issue. Probably I should try to switch to my personal devhub then

**Comment by bdovh** [comment]
what a heck is going on? when I tried to switch to my European-based devhub, I started receiving the following errors:

<img width="1305" alt="Screenshot 2023-02-13 at 16 21 41" src="https://user-images.githubusercontent.com/75684333/218483635-336e6032-a71e-47bd-ab78-e8adcd55e358.png">

I use English locale and English language. How come the scratch org is created with Russian language?

**Comment by mshanemc** [comment]
closing because the linked KI closed.
