### ISSUE TITLE
REGRESSION: Release Candidate (7.191.3) CLI has updated telemetry plugin that crashes with "Perf results not available. Did you forget to call await Performance.collect()"

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#1987]
### Summary

Starting a few hours ago, the CI builds we have scheduled that use the Release Candidate CLI started failing with:

```
 [exec] WARNING: [24:25:07.236] [WARN] 9 issues were found in source CSV file. See CSVIssuesReport.csv file for the details.
Error: xec] [24:27:43.864] [ERROR] Execution of the command has aborted due to unexpected error: Perf results not available. Did you forget to call await Performance.collect()?.
Error: xec] [24:27:43.866] [ERROR] [STACK TRACE] Error: Perf results not available. Did you forget to call await Performance.collect()?
     [exec]     at get highlights [as highlights] (/home/runner/work/patronquery/patronquery/sfdx/node_modules/@oclif/core/lib/performance.js:44:15)
     [exec]     at CommandExecution.toJson (/home/runner/work/patronquery/patronquery/sfdx/node_modules/@salesforce/plugin-telemetry/lib/commandExecution.js:90:47)
     [exec]     at process.<anonymous> (/home/runner/work/patronquery/patronquery/sfdx/node_modules/@salesforce/plugin-telemetry/lib/hooks/telemetryPrerun.js:68:47)
     [exec]     at Object.onceWrapper (node:events:628:26)
     [exec]     at process.emit (node:events:525:35)
     [exec]     at process.exit (node:internal/process/per_thread:192:15)
     [exec]     at RunCommandExecutor.execute (/home/runner/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommandExecutor.js:48:47)
     [exec]     at async Run.run (/home/runner/.local/share/sfdx/node_modules/sfdmu/lib/commands/sfdmu/run.js:20:9)
     [exec]     at async Run._run (/home/runner/.local/share/sfdx/node_modules/sfdmu/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)
     [exec]     at async Config.runCommand (/home/runner/work/patronquery/patronquery/sfdx/node_modules/@oclif/core/lib/config/config.js:326:25)
```

The only builds that are failing are ones that use the SFDMU plugin to populate seed data. But the SFDMU plugin hasn't been updated in weeks.

The telemetry plugin was updated earlier today and smells like the smoking gun:

https://github.com/salesforcecli/plugin-telemetry/commit/84d0377d35f9f75b073807c6506037863f007d8d

Our last successful build had the following versions of CLI and plugins:

```
sfdx-cli/7.191.1 linux-x64 node-v18.14.1
@oclif/plugin-autocomplete 2.1.3 (core)
@oclif/plugin-commands 2.2.10 (core)
@oclif/plugin-help 5.2.6 (core)
@oclif/plugin-not-found 2.3.21 (core)
@oclif/plugin-plugins 2.3.2 (core)
@oclif/plugin-search 0.0.13 (core)
@oclif/plugin-update 3.1.6 (core)
@oclif/plugin-version 1.2.1 (core)
@oclif/plugin-warn-if-update-available 2.0.29 (core)
@oclif/plugin-which 2.2.16 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
apex 2.2.1 (core)
auth 2.7.3 (core)
community 2.2.3 (core)
custom-metadata 2.1.5 (core)
data 2.3.4 (core)
info 2.4.7 (core)
limits 2.3.5 (core)
org 2.4.4 (core)
packaging 1.15.0 (core)
schema 2.3.1 (core)
settings 1.4.0 (core)
sfdx-cli 7.191.1 (core)
signups 1.4.5 (core)
source 2.5.5 (core)
telemetry 2.1.1 (core)
templates 55.4.4 (core)
trust 2.4.4 (core)
user 2.3.2 (core)
```

The failing CLI has the following versions of CLI and plugins:

```
sfdx-cli/7.191.3 linux-x64 node-v18.14.1
@oclif/plugin-autocomplete 2.1.3 (core)
@oclif/plugin-commands 2.2.10 (core)
@oclif/plugin-help 5.2.6 (core)
@oclif/plugin-not-found 2.3.21 (core)
@oclif/plugin-plugins 2.3.2 (core)
@oclif/plugin-search 0.0.13 (core)
@oclif/plugin-update 3.1.6 (core)
@oclif/plugin-version 1.2.1 (core)
@oclif/plugin-warn-if-update-available 2.0.29 (core)
@oclif/plugin-which 2.2.16 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
apex 2.2.1 (core)
auth 2.7.3 (core)
community 2.2.3 (core)
custom-metadata 2.1.5 (core)
data 2.3.4 (core)
info 2.5.1 (core)
limits 2.3.5 (core)
org 2.4.4 (core)
packaging 1.15.0 (core)
schema 2.3.1 (core)
settings 1.4.0 (core)
sfdx-cli 7.191.3 (core)
signups 1.4.5 (core)
source 2.5.5 (core)
telemetry 2.1.2 (core)
templates 55.4.4 (core)
trust 2.4.4 (core)
user 2.3.2 (core)
```

**Comment by iowillhoit** [comment]
Hey @daveespo, thanks for this issue. We did roll back the current `latest-rc` to `7.191.1` because of this. The telemetry updates (and the fix) will ship in tomorrow's `latest-rc`
