### ISSUE TITLE
running "bin/dev hello world" throws error on @swc/core 

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/cli#2056]
### Summary

I'm following the steps here to create an `sf` plugin

https://github.com/salesforcecli/cli/wiki/Get-Started-And-Create-Your-First-Plug-In#generate-a-plugin-and-run-the-hello-world-command

### Steps To Reproduce:

1.  Following the instructions on https://github.com/salesforcecli/cli/wiki/Get-Started-And-Create-Your-First-Plug-In#generate-a-plugin-and-run-the-hello-world-command to create a plugin
1.  Run `bin/dev hello world`

### Expected result

I should see the output of the sample command hello world

### Actual result

I get this error

```
/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/transpilers/swc.ts:262
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Bindings not found
    at createVariant (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/transpilers/swc.ts:262:13)
    at createSwcOptions (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/transpilers/swc.ts:211:25)
    at create (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/transpilers/swc.ts:56:41)
    at createTranspiler (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/index.ts:1341:28)
    at createFromPreloadedConfig (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/index.ts:1404:34)
    at create (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/index.ts:624:10)
    at Object.register (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/ts-node/src/index.ts:591:15)
    at Object.<anonymous> (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/bin/dev:11:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

I fixed this problem by using a higher version of `@swc/core`

`npm install @swc/core`

it updated from `"@swc/core": "^1.3.19"` to  ` "@swc/core": "^1.3.49"` and now I get the correct result

`bin/dev hello world`

`Hello World at Thu Apr 13 2023.`

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

zsh

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`

```
{
  "cliVersion": "sfdx-cli/7.194.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 21.0.1",
  "shell": "zsh",
  "rootPath": "/Users/pgonzalez/.local/share/sfdx/client/7.194.1-faa045e",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "community 2.2.8 (core)",
    "custom-metadata 2.1.9 (core)",
    "data 2.3.8 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "org 2.6.2 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.8 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 3.10.0 (user)",
    "bbdoc 4.1.0 (user)",
    "sfdmu 4.26.10 (user)",
    "sfdx-cli 7.194.1 (core)",
    "sfdx-essentials 2.12.0 (user)",
    "sfdx-git-delta 5.17.1 (user)",
    "sfdx-hardis 3.13.1 (user)",
    "texei-sfdx-plugin 1.17.2 (user)"
  ]
}
```

- If you are using `sf`
	- Run `sf version --verbose --json`

```
{
  "cliVersion": "@salesforce/cli/1.71.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 21.0.1",
  "shell": "zsh",
  "rootPath": "/Users/pgonzalez/.local/share/sfdx/client/7.194.1-faa045e/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "@salesforce/cli 1.71.0 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "data 2.3.8 (core)",
    "deploy-retrieve 1.8.5 (core)",
    "dev 0.7.0 (user)",
    "env 2.1.3 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "login 1.2.4 (core)",
    "org 2.6.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "sobject 0.1.9 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
Hey @pgonzaleznetwork - thanks for bringing this up. I'll bump that version now

**Comment by pgonzaleznetwork** [comment]
Thank you @WillieRuemmele , how do I know when this'll be released? I'm new to following updates on the CLI :)

**Comment by WillieRuemmele** [comment]
Hey @pgonzaleznetwork - for most fixes this would be availble in the `nightly` channel every night, but since this command just clones the `plugin-template-sf` repository, it should be fixed if you delete your plugin, and run the command again. This is because I merged the fix directly to the `main` branch in the template

**Comment by pgonzaleznetwork** [comment]
Great, thanks!
