### ISSUE TITLE
--json flag not available in SfCommand class

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/cli#2060]
### Summary

I'm following the guide here https://github.com/salesforcecli/cli/wiki/Get-Started-And-Create-Your-First-Plug-In#generate-a-plugin-and-run-the-hello-world-command to create a new `sf` plugin; I haven't modified any of the code, I'm using exactly what the plugin builder generated.

When I run `bin/dev hello world --json`, I get the following error:

```
{
  "message": "Nonexistent flag: --json\nSee more help with --help",
  "name": "Error",
  "status": 1,
  "stack": "Error: Nonexistent flag: --json\nSee more help with --help\n    at validateArgs (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/@oclif/core/lib/parser/validate.js:9:19)\n    at validate (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/@oclif/core/lib/parser/validate.js:156:5)\n    at Object.parse (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/@oclif/core/lib/parser/index.js:19:35)\n    at async World.parse (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/@oclif/core/lib/command.js:193:25)\n    at async World.run (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/src/commands/hello/world.ts:32:23)\n    at async World._run (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/@oclif/core/lib/command.js:107:22)\n    at async Config.runCommand (/Users/pgonzalez/Documents/apps/sfplugin/dxfolders/node_modules/@oclif/core/lib/config/config.js:296:25)",
  "exitCode": 1,
  "warnings": []
}
```

According to the [docs](https://github.com/salesforcecli/sf-plugins-core#sfcommand-abstract-class) for the `sfcommand` class, it should have native `--json` support.

What's more weird, is that somehow the test that asserts that the `--json` flag works, is passing.

`yarn test`

```
✔ runs hello world with no provided name (1098ms)
 ✔ runs hello world with --json and no provided name
 ✔ runs hello world --name Astro
 ✔ runs hello world --name Astro --json
```

### Steps To Reproduce:

1.  Following the instructions [here](https://github.com/salesforcecli/cli/wiki/Get-Started-And-Create-Your-First-Plug-In#generate-a-plugin-and-run-the-hello-world-command) to create a new plugin
1.  Run `bin/dev hello world --json`

### Expected result

I should see a `json` representation of the return value for the command

```
export type HelloWorldResult = {
  name: string;
  time: string;
};
```

### Actual result

I get the error message shown above. 

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

zsh

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`

```
{
  "cliVersion": "sfdx-cli/7.194.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 21.0.1",
  "shell": "zsh",
  "rootPath": "/Users/pgonzalez/.local/share/sfdx/client/7.194.1-faa045e",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "community 2.2.8 (core)",
    "custom-metadata 2.1.9 (core)",
    "data 2.3.8 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "org 2.6.2 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.8 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 3.10.0 (user)",
    "bbdoc 4.1.0 (user)",
    "sfdmu 4.26.10 (user)",
    "sfdx-cli 7.194.1 (core)",
    "sfdx-essentials 2.12.0 (user)",
    "sfdx-git-delta 5.17.1 (user)",
    "sfdx-hardis 3.13.1 (user)",
    "texei-sfdx-plugin 1.17.2 (user)"
  ]
}
```

- If you are using `sf`
	- Run `sf version --verbose --json`

```
{
  "cliVersion": "@salesforce/cli/1.71.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 21.0.1",
  "shell": "zsh",
  "rootPath": "/Users/pgonzalez/.local/share/sfdx/client/7.194.1-faa045e/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "@salesforce/cli 1.71.0 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "data 2.3.8 (core)",
    "deploy-retrieve 1.8.5 (core)",
    "dev 0.7.0 (user)",
    "env 2.1.3 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "login 1.2.4 (core)",
    "org 2.6.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "sobject 0.1.9 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
Hey once again @pgonzaleznetwork 👋 

I couldn't reproduce this issue... here are the steps I ran
```
 ➜  sf plugins install @salesforce/plugin-dev                    
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/plugin-dev.
Finished digital signature check.
Installing plugin dev... ⣽ [1/4] Resolving packages...
Installing plugin dev... ⣻ [1/4] Resolving packages...
Installing plugin dev... ⢿ [1/4] Resolving packages...
Installing plugin dev... ⣻ [1/4] Resolving packages...
Installing plugin dev... ⣾ [2/4] Fetching packages...
warning "@salesforce/plugin-custom-metadata > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "@salesforce/plugin-custom-metadata > @oclif/core > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
warning "@salesforce/plugin-dev > yeoman-environment@3.15.1" has unmet peer dependency "mem-fs@^1.2.0 || ^2.0.0".
Installing plugin dev... installed v0.7.0
➜  scratches 
 ➜  sf dev generate plugin

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │    Time to build an sf   │
   `---------´   │   plugin! Version 0.7.0  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Are you building a plugin for an internal Salesforce team? No
? Enter the name of your new plugin: d
? Enter a robust description for your plugin: d
? Enter the author of the plugin: WillieRuemmele
? Select the % code coverage do you want to enforce: 50%
Cloning into '/Users/william.ruemmele/projects/scratches/d'...
Initialized empty Git repository in /Users/william.ruemmele/projects/scratches/d/.git/
    force d/.nycrc
    force d/package.json

Changes to package.json were detected.

Running yarn install for you to install the required dependencies.
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "@salesforce/dev-scripts > typedoc@0.22.18" has incorrect peer dependency "typescript@4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x || 4.6.x || 4.7.x".
warning "oclif > yeoman-environment@3.12.1" has unmet peer dependency "mem-fs@^1.2.0 || ^2.0.0".
warning "oclif > yeoman-environment@3.12.1" has unmet peer dependency "mem-fs-editor@^8.1.2 || ^9.0.0".
[5/5] 🔨  Building fresh packages...
$ yarn husky install
yarn run v1.22.19
$ /Users/william.ruemmele/projects/scratches/d/node_modules/.bin/husky install
husky - Git hooks installed
✨  Done in 0.37s.
✨  Done in 12.52s.
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn husky install
yarn run v1.22.19
$ /Users/william.ruemmele/projects/scratches/d/node_modules/.bin/husky install
husky - Git hooks installed
Done in 0.25s.
Done in 0.65s.
yarn run v1.22.19
$ sf-build
yarn clean
$ sf-clean
> rm -rf tmp/,package-lock.json,.npmrc,npm-error.log,yarn-error.log,lib,*xunit.xml,*checkstyle.xml,*unitcoverage,.nyc_output,coverage,test_session*,docs,*.tgz,*.sig,package.json.bak.
yarn compile
$ sf-compile
tsc -p . --pretty
yarn lint
$ sf-lint
eslint "src/**/*.ts" "test/**/*.ts" 
Done in 7.05s.
➜  scratches 
 ➜  cd d             
➜  d git:(main) ✗ 
 ➜  yarn && yarn builld
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ yarn husky install
yarn run v1.22.19
$ /Users/william.ruemmele/projects/scratches/d/node_modules/.bin/husky install
husky - Git hooks installed
✨  Done in 0.25s.
✨  Done in 0.65s.
yarn run v1.22.19
$ sf-build
yarn clean
$ sf-clean
> rm -rf tmp/,package-lock.json,.npmrc,npm-error.log,yarn-error.log,lib,*xunit.xml,*checkstyle.xml,*unitcoverage,.nyc_output,coverage,test_session*,docs,*.tgz,*.sig,package.json.bak.
yarn compile
$ sf-compile
tsc -p . --pretty
yarn lint
$ sf-lint
eslint "src/**/*.ts" "test/**/*.ts" 
✨  Done in 5.90s.
➜  d git:(main) ✗ 
 ➜  bin/dev hello world                                                                                        
Hello World at Thu Apr 13 2023.
➜  d git:(main) ✗ 
 ➜  bin/dev hello world  --json
{
  "status": 0,
  "result": {
    "name": "World",
    "time": "Thu Apr 13 2023"
  },
  "warnings": []
}
```

did you do anything differently?

**Comment by pgonzaleznetwork** [comment]
Hey @WillieRuemmele ,

The only difference is I chose 75% code coverage. 

I uploaded my plugin here https://github.com/pgonzaleznetwork/dxfolders-cli-plugin

Can you try with that one? I really didn't change anything; that's what the generator did.

**Comment by WillieRuemmele** [comment]
@pgonzaleznetwork - try pinning `@swc/core` to `1.3.39` we've seen this dependency interfere with the `--json` flag before. We have a WI to track it down, but haven't gotten to yet... that's what I set to to in the template earlier today

Once I did that I was able to run with `--json`

**Comment by pgonzaleznetwork** [comment]
Thank you @WillieRuemmele !

I upgraded the CLI just in case with `sfdx update` and then pinned the dependency with `yarn add @swc/core@1.3.39` 

Now `bin/dev hello world  --json` returns the correct output:

```
{
  "status": 0,
  "result": {
    "name": "World",
    "time": "Thu Apr 13 2023"
  },
  "warnings": []
}
```

I have a few questions:

1- In #2056 , you said you bumped the version of `swc/core` to `1.3.39` and merged to master. But when I created a new plugin just now, I still had `1.3.19`

That's why I tried upgrading the CLI, but even after that, version `1.3.19` was there.

Can you confirm this is fixed?

2- Was  `yarn add @swc/core@1.3.39`  the correct way to pin the dependency? I read [this article](https://the-guild.dev/blog/how-should-you-pin-dependencies-and-why) on pinning dependencies and got overwhelmed. I'm not an expert in yarn and nodejs dependencies in general.

3- How come #2056 wasn't caught by CI tests? This was a failure on a core command, not an edge case. I would expect this to be caught by automated tests.

4- This is my first time creating a plugin and I'm using `sf` as it is the future. Is `sf` in a "stable" state for users to create plugins? I worry that it's still somehow WIP and that I'm going to bump into a lot of issues/inconsistencies.

Sorry for all the questions. Thanks a lot for your help!

**Comment by pgonzaleznetwork** [comment]
@WillieRuemmele just checking if you had a chance to review the above :)

**Comment by WillieRuemmele** [comment]
Hey - not fully yet - the command must work differently than I thought, but pinning `@swc/core: 1.3.39` should fix the issue correct?

**Comment by pgonzaleznetwork** [comment]
Yes, the issue is fixed. I only have some doubts/questions, which I documented above.

**Comment by mshanemc** [comment]
>This is my first time creating a plugin and I'm using sf as it is the future. Is sf in a "stable" state for users to create plugins? I worry that it's still somehow WIP and that I'm going to bump into a lot of issues/inconsistencies.

Every plugin the CLI teams owns is using sfCommand and in sf.  As a frequent user of it, it's much better and less error-prone than building on top of SfdxCommand was.

We're going to spend some time making the plugin dev experience and tooling easier.
