### ISSUE TITLE
sf project deploy quick command issue

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/cli#2159]
sf project deploy quick -w 1 --job-id $deploy_id --json > deploy-result.json || {
        echo_method_error "$(cat deploy-result.json)"
      }

This is the script I have used in my GitLab pipeline where deploy_id has valid validated deployment id. Deployment has been successfully done in Salesforce side but, sf project deploy quick command failed with the following error:

{
  "code": 1,
  "context": "DeployMetadataQuick",
  "commandName": "DeployMetadataQuick",
  "message": "undefinedComponentSet",
  "name": "SfError",
  "status": 1,
  "stack": "SfError: undefinedComponentSet
    at ComponentSetBuilder.build (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSetBuilder.js:140:19)
    at buildComponentSet (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/utils/deploy.js:47:57)
    at async DeployMetadataQuick.run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/deploy/quick.js:30:30)
    at async DeployMetadataQuick._run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:117:22)
    at async Config.runCommand (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:329:25)
    at async run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:89:16)",
  "exitCode": 1,
  "warnings": [
    "org-api-version configuration overridden at 57.0"
  ]
}

**Comment by iowillhoit** [comment]
Hey @shabu74, we are going to need more information to look into this. All I can really tell is that you are hitting this [throw here](https://github.com/forcedotcom/source-deploy-retrieve/blob/0c97dee694035287b4d625d0cdb394a7bd6f67b3/src/collections/componentSetBuilder.ts#L175-L178), which means a componentSet should have been created by then.

Please fill out all of the information in the `Issue > Bug` template. Ideally with a repository including steps to reproduce your problem. Thanks

**Comment by shabu74** [comment]
Hi Willhoit,

Thanks for the reply.

**Comment by shabu74** [comment]
Created a new case with details
