### ISSUE TITLE
Displaying the navigation URL outputs a superfluous error

### ISSUE THREAD

**Issue by ncinolando** [forcedotcom/cli#2208]
### Summary

Using the URL Only and JSON output options for the `force:org:open` command appends an additional error with no explanation.

### Steps To Reproduce:
This error did not show up until I upgraded my Node.js version and installed sfdx-cli via `npm` for that version.

1. Install a fresh version of Node.js (either through `nvm` or uninstalling and reinstalling).
1. Install the sfdx-cli tool via `npm` for the newly installed Node.js version.
1. Ensure the `SFDX_LOG_LEVEL` environment variable is set to `debug`.
1. Identify an existing scratch org or create a new scratch org.
1. Execute `sfdx force:org:open --urlonly --json -u <IDENTIFIED_ORG_USERNAME>` 

### Expected result

The command should display a JSON only output that can easily be consumed by JSON accepting scripts.

```Shell
{
  "status": 0,
  "result": {
    "orgId": "<ORG_ID>",
    "url": "https://<SALESFORCE_INSTANCE_URL>/secur/frontdoor.jsp?sid=<ORG_ID>!<TOKEN>",
    "username": "<USERNAME>"
  }
}
```

### Actual result
The JSON output does display, but a random error is printed underneath which seems unrelated.

```Shell
{
  "status": 0,
  "result": {
    "orgId": "<ORG_ID>",
    "url": "https://<SALESFORCE_INSTANCE_URL>/secur/frontdoor.jsp?sid=<ORG_ID>!<TOKEN>",
    "username": "<USERNAME>"
  }
}
JsonParseError: Unexpected end of JSON input
    at Function.create (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/errors.js:49:20)
    at Object.parseJson (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/json.js:27:39)
    at args.map.arg (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/logger.js:548:53)
    at Array.map (<anonymous>)
    at _filter (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/logger.js:500:17)
    at Logger.addFilter.args (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/logger.js:96:37)
    at bunyan.filters.forEach (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/logger.js:456:61)
    at Array.forEach (<anonymous>)
    at Logger.applyFilters (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/logger.js:456:33)
    at Logger.info (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/logger.js:421:31)
    at UX.logJson (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/ux.js:103:21)
    at OrgOpenCommand.finally (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:305:25)
    at OrgOpenCommand._run (~/.nvm/versions/node/v10.16.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:98:31)
```

### Additional information

This issue currently causes automated scripts to fail that assume only JSON will be output from this command.

![image](https://user-images.githubusercontent.com/43143995/61098521-4afba480-a42d-11e9-9984-62a8de13eda0.png)

The issue seems be due to [logger.ts](https://github.com/forcedotcom/sfdx-core/blob/8505f04e80a561a94be52a99ba5fa75b1131b190/src/logger.ts#L727). The Regex pattern `sid=(.*)` seems to be replacing the rest of the JSON string with a `<HIDDEN>` string for the log. When the logger tries to parse the JSON, the JSON string is invalid.
 
 While the JSON logged should look like this:

```Javascript
{"status":0,"result":{"orgId":"??????????????????","url":"https://some-words-####-dev-ed.cs##.my.salesforce.com/secur/frontdoor.jsp?sid=<HIDDEN>","username":"test-raNd0mSt1ng@example.com"}}
```

it actually ends up being this:

```Javascript
{"status":0,"result":{"orgId":"??????????????????","url":"https://some-words-####-dev-ed.cs##.my.salesforce.com/secur/frontdoor.jsp?sid=<HIDDEN>"
```

My current workaround is to overwrite the local file **logger.js** in the @salesforce/core/lib directory to use a different regex pattern that does not match to the end of the string:

```Javascript
_arg = _arg.replace(/sid=([A-Za-z0-9._!]+)/, `sid=<${HIDDEN}>`);
```

**SFDX CLI Version**: sfdx-cli/7.14.0 darwin-x64 node-v10.16.0

**SFDX plugin Version**: salesforcedx 46.4.0 (core)

**OS and version**: macOS Mojave (10.14.5)

**Comment by clairebianchi** [comment]
@callietoothman we are unable to reproduce in the current CLI, can you update your CLI and try again

**Comment by ncinolando** [comment]
@clairebianchi Updated sfdx, same issue:

**SFDX CLI Version**: sfdx-cli/7.33.2 darwin-x64 node-v10.16.0

**SFDX plugin Version**: salesforcedx 47.6.2 (core)

**OS and version**: macOS Mojave (10.14.6)

![image](https://user-images.githubusercontent.com/43143995/68974646-3a827e80-07bf-11ea-9887-6b4f02d97867.png)

**Comment by paferpo** [comment]
FYI: I experienced the same issue after setting the environment variable for nodejs DEBUG=app

**Comment by ncinolando** [comment]
Ahhh! Thanks! I didn't have `DEBUG=app`, but I did have `SFDX_LOG_LEVEL=debug`. When I unset it, the error disappeared.

**Comment by ncinolando** [comment]
@clairebianchi You should be able to run the following to reproduce the error:

```shell
SFDX_LOG_LEVEL=debug sfdx force:org:open --urlonly --json
```
