### ISSUE TITLE
`sf apex run test` - Error (1): Invalid time value

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#2220]
### Summary
Executing tests with `--output-dir` flag specified results in error and no test results output to file or to screen.

### Steps To Reproduce
1. Using [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) project
2. Run tests with `--output-dir` flag specified
    ```
    sf apex run test --output-dir test-results -w 10 -o dreamhouse
   ```
### Expected result
Tests should execute, command should exit successfully and results written to file(s) in output directory.

### Actual result
Tests execute but no results written to output directory (or screen) and command exits with error:
> Error (1): Invalid time value

### System Information
```json
{
  "cliVersion": "@salesforce/cli/1.82.6",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Linux 5.19.0-41-generic",
  "shell": "zsh",
  "rootPath": "/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.82.6 (core)",
    "apex 2.3.2 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.4 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "login 1.2.11 (core)",
    "org 2.9.7 (core)",
    "schema 2.3.12 (core)",
    "settings 1.4.10 (core)",
    "signups 1.4.14 (user)",
    "sobject 0.1.23 (core)",
    "source 2.10.13 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.16 (core)",
    "gr-sfdx-plugin 0.0.0 (link) /home/alan.morey/repos/salesforce/gr-sfdx-plugin"
  ]
}
```
### Additional information

```
Error (1): Invalid time value                                                                  
                                                                                               
*** Internal Diagnostic ***                    
                                               
RangeError: Invalid time value                                                                 
    at Date.toISOString (<anonymous>)                                                                                                                                                         
    at JUnitReporter.format (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/src/reporters/junitReporter.ts:32:61)                         
    at TestService.<anonymous> (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/src/tests/testService.ts:278:53)                           
    at Generator.next (<anonymous>)            
    at /home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:8:71                                                   
    at new Promise (<anonymous>)                                                                                                                                                              
    at __awaiter (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:4:12)                                       
    at TestService.writeResultFiles (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:174:16)                  
    at TestReporter.report (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-apex/src/reporters/testReporter.ts:63:25)                         
    at Test.run (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-apex/src/commands/apex/run/test.ts:154:27)                                   
    at processTicksAndRejections (node:internal/process/task_queues:95:5)                      
    at async Test._run (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:117:22)                                                       
    at async Config.runCommand (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:329:25)                                         
    at async run (/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:89:16)                                                                 
******                                                                                                                                                                                        
```

Tried changing the result format, e.g. `--result-format tap`, still get same error

**Comment by alan-morey** [comment]
Looks like this is related to a similar issue I reported with `sfdx` 2 years ago `salesforcedx-apex/issues/213`, I didn't find it before creating this issue because it had been moved around.

Is there any plans to actually fix this issue?

The root cause of the issue is my locale is set to `en_CA.UTF-8` and the JSON output from the command contains  `en_US` locale specific formatted datetime strings instead of ISO formatted datetime strings.

A temporary workaround for this is specifying the locale for the command execution with `LANG` env var :

```
LANG=en_US.UTF-8 sf apex run test -w 10 -o dreamhouse --output-dir reports
Test result files written to reports
=== Test Summary
NAME                 VALUE                        
───────────────────  ─────────────────────────────
Outcome              Passed                       
Tests Ran            11                           
Pass Rate            100%                         
Fail Rate            0%                           
Skip Rate            0%                           
Test Run Id          7070100001wvtZO              
Test Execution Time  2218 ms                      
Org Id               00D010000001L7yEAE           
Username             test-fi7uet48sknr@example.com


=== Test Results
TEST NAME                                                 OUTCOME  MESSAGE  RUNTIME (MS)
────────────────────────────────────────────────────────  ───────  ───────  ────────────
GeocodingServiceTest.blankAddress                         Pass              10          
GeocodingServiceTest.errorResponse                        Pass              7           
GeocodingServiceTest.successResponse                      Pass              6           
TestPropertyController.testGetPagedPropertyList           Pass              772         
TestPropertyController.testGetPicturesNoResults           Pass              32          
TestPropertyController.testGetPicturesWithResults         Pass              379         
TestSampleDataController.importSampleData                 Pass              277         
FileUtilitiesTest.createFileFailsWhenIncorrectBase64Data  Pass              97          
FileUtilitiesTest.createFileFailsWhenIncorrectFilename    Pass              28          
FileUtilitiesTest.createFileFailsWhenIncorrectRecordId    Pass              307         
FileUtilitiesTest.createFileSucceedsWhenCorrectInput      Pass              303         
```

While this is adequate for me in the short term, it's really inconvenient to have to remember to specify this each time I want to run tests with reports and ruins the `sf` user experience.

The ideal solution should be the JSON output does not contain locale specific formatted datetimes. I'm sure there are many users around the world using sf with locales other that `en_US`.

**Comment by WillieRuemmele** [comment]
hey @alan-morey 

I've pinged someone on the team that owns that library, hopefully we can get this fixed now

just to link everything together:
https://github.com/forcedotcom/salesforcedx-apex/issues/213
W-10226817

**Comment by JonnyPower** [comment]
I have a pending PR open for months to resolve this over at https://github.com/forcedotcom/salesforcedx-apex/pull/324 - unfortunately has proven hard to get reviewed

**Comment by JonnyPower** [comment]
@WillieRuemmele if you have contact with the owners of salesforcedx-apex, could you ping them my PR (and the other PR to fix incorrect namespacing of apex classes) - would appreciate it!

**Comment by shetzel** [comment]
It looks like an attempt was made long ago to fix this but was abandoned due to the possibility of it breaking existing results parsing.  See https://github.com/forcedotcom/salesforcedx-apex/pull/271

I'm not sure why the format conversion was done to begin with.  I'll get something going for this.

**Comment by shetzel** [comment]
work item: W-10226817

**Comment by shetzel** [comment]
The fix should be in the next CLI release candidate (next Wednesday, the 15th) but if you want it sooner you can install the latest `@salesforce/plugin-apex` plugin.
