### ISSUE TITLE
No arguments for destructive changes in sf project deploy validate command

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/cli#2246]
**Is your feature request related to a problem? Please describe.**
sf project deploy validate command has argument to specify manifest for constructive deployment only

**What are you trying to do**
I need to validate destructive deployment also like sf deploy start command

**Describe the solution you'd like**
manifest arguments for destructive deployment also need to be included in the command eg: ---pre-destructive-changes and --post-destructive-changes

**Describe alternatives you've considered**
sf deploy start command

**Comment by WillieRuemmele** [comment]
Hi @shabu74 - these new flags have been released in `@salesforce/cli 2.0.2`

**Comment by shabu74** [comment]
Thanks. But I think documentation has not been updated, Would you please specify the argument name

**Comment by shabu74** [comment]
Hi @WillieRuemmele,

No, I have installed latest SF CLI. But still getting error:

{
  "code": 1,
  "context": "DeployMetadataValidate",
  "commandName": "DeployMetadataValidate",
  "message": "Nonexistent flag: --post-destructive-changes
See more help with --help",
  "name": "Error",
  "status": 1,
  "stack": "Error: Nonexistent flag: --post-destructive-changes
See more help with --help
    at validateArgs (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/parser/validate.js:9:19)
    at validate (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/parser/validate.js:157:5)
    at Object.parse (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/parser/index.js:19:35)
    at async DeployMetadataValidate.parse (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:221:25)
    at async Promise.all (index 0)
    at async DeployMetadataValidate.run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/deploy/validate.js:29:34)
    at async DeployMetadataValidate._run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:[117](https://gitlab.service.nsw.gov.au/salesforce/caresnsw/-/jobs/7395188#L117):22)
    at async Config.runCommand (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:329:25)
    at async run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}

**Comment by shabu74** [comment]
More over, test level can not be specified with No test Run. Then How can we validate non-apex components? @WillieRuemmele

**Comment by dudunato** [comment]
@shabu74 were you able to get this working? The flag is in the docs but it gives Nonexistent flag. Quite annoying...

**Comment by dudunato** [comment]
Any insight, @WillieRuemmele?

**Comment by dudunato** [comment]
@WillieRuemmele would you know any workaround. I need to validate and grab the jobId. So we can run quick deploy afterwards. So --dry-run on deploy start doesn't really work for me here. :/

**Comment by WillieRuemmele** [comment]
Hi @dudunato - are you still seeing this on the latest version of the CLI? 

I'm using `@salesforce/cli/2.17.6 darwin-arm64 node-v18.15.0`
and see the flags and confirmed they're working

```bash
sf project deploy validate --help                   
Validate a metadata deployment without actually executing it.
...

DELETE FLAGS
  --post-destructive-changes=<value>  File path for a manifest (destructiveChangesPost.xml) of components to delete after the deploy.
  --pre-destructive-changes=<value>   File path for a manifest (destructiveChangesPre.xml) of components to delete before the deploy
  --purge-on-delete                   Specify that deleted components in the destructive changes manifest file are immediately eligible for deletion
                                      rather than being stored in the Recycle Bin.

```

```bash
 ➜  sf project deploy validate --pre-destructive-changes destructiveChangesPre.xml --manifest package.xml 
Validating Deployment of v59.0 metadata to test-wobioos3usus@example.com using the v59.0 REST API.
```
