### ISSUE TITLE
SFDX commands using PollingClient throws "CLIError: timed out"

### ISSUE THREAD

**Issue by SakshiV19** [forcedotcom/cli#2266]
Summary
While using PollingClient (salesforce/core) module, the command times out in most of the newer SFDX versions.
Although the other operation continues to work, but this error displays on the terminal.

CLIError: timed out
    at Object.error (/Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/errors/index.js:27:15)
    at /Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/cli-ux/index.js:29:62
    at flush (/Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/cli-ux/index.js:121:9) {
  oclif: { exit: 2 },
  code: undefined
}

It is working fine for v7.179.0 but not for v7.192.0
Not sure about the versions in between this range and when it actually stopped working.

Steps To Reproduce:
TBD

Expected result
It should not time-out.

Actual result
For newer versions, it times out in under a minute.

Additional information: N/a

OS and version: N/a

**Comment by SakshiV19** [comment]
Closing this as info was incomplete.
