### ISSUE TITLE
sfdx force:project:create error, what is going wrong?

### ISSUE THREAD

**Issue by dannyodd** [forcedotcom/cli#236]
### Summary

When I attempt to create a new Project in the CLI, using VisualStudio Code as my IDE, I get the following error message:
PS C:\Users\dthto\sfdxprojects\testProject> sfdx force:project:create --projectname testProject1
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\templates\project\standard\ScratchDef.json
    at EditionInterface.exports.copy (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at ProjectGenerator.writing (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\generators\projectGenerator.js:53:17)       
    at Object.<anonymous> (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\yeoman-generator\lib\index.js:395:23)    
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\yeoman-generator\lib\index.js:396:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\templates\project\standard\ScratchDef.json
    at EditionInterface.exports.copy (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at ProjectGenerator.writing (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\generators\projectGenerator.js:53:17)       
    at Object.<anonymous> (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\yeoman-generator\lib\index.js:395:23)    
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\yeoman-generator\lib\index.js:396:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }

### Steps To Reproduce:

1.  Type "sfdx force:project:create --projectname PROJECTNAME " and press enter

### Expected result

A project skeleton structure and definition file will be created

### Actual result

Error message as shown above

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): Current

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) Current

**OS and version**: Windows 10 Pro version 10.0.18362 Build 18362

**Comment by clairebianchi** [comment]
@ntotten would you take a look at this issue?

**Comment by lcampos** [comment]
Hi @dannyodd thanks for opening this issue. The stack trace you've added indicates that a template file that the cli ships with and is used by the project:create command, is not available. I'm currently testing on a Windows machine with the same OS version you are on and can't replicate the issue on the latest version of the CLI (v7.33.2). Could you confirm you are in this version and still experiencing the issue ?

If you are still getting this issue in that version then could you go into your file system and verify that this file is not present( C:\Program Files (x86)\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\templates\project\standard\ScratchDef.json ) ? If that's the case then something might've gone wrong during installation/update of your CLI.

**Comment by kazmierczykm** [comment]
`sfdx update` helped in my case

I have x86 version
