### ISSUE TITLE
SF CLI apex run test RunLocalTests is throwing an error and not providing valid testRunId

### ISSUE THREAD

**Issue by VenkatNaveenM** [forcedotcom/cli#2409]
### Summary

- SF CLI apex run test RunLocalTests is throwing an error and not providing valid testRunId.
- The error code is 431, This can happen because the total size of the request headers is too large or it can happen because a single header field is too large.
- Error may be because we are running all local tests and internally it is exceeding URL limits.
- Can't provide the repository link as it is confidential.

### Steps To Reproduce
**Commands:**
sf apex run test --test-level RunLocalTests --synchronous --json > test_outcome_full.json --wait 180
sf apex run test --test-level RunLocalTests --json > test_outcome_full.json --wait 180

**Expected Result:**
```json
{
  "status": 0,
  "result": {
    "summary": {
      "outcome": "Passed",
      "testsRan": 1,
      "passing": 1,
      "failing": 0,
      "skipped": 0,
      "passRate": "100%",
      "failRate": "0%",
      "testStartTime": "Wed Aug 16 2023 3:44:51 PM",
      "testExecutionTime": "11 ms",
      "testTotalTime": "11 ms",
      "commandTime": "773 ms",
      "hostname": "",
      "orgId": "",
      "username": "",
      "testRunId": "707Oy000000C_Id_should_be_here",
      "userId": ""
    },
    "tests": [
      {
        "Id": "07MOy00000094w5MAA",
        "QueueItemId": "709Oy0000005J3dIAE",
        "StackTrace": null,
        "Message": null,
        "AsyncApexJobId": "707Oy000000bvHCIAY",
        "MethodName": "SFDXPipelineRun",
        "Outcome": "Pass",
        "ApexClass": {
          "Id": "01p79000000EXTyAAO",
          "Name": "SFDXPipelineRunTest",
          "NamespacePrefix": null
        },
        "RunTime": 11,
        "FullName": "SFDXPipelineRunTest.SFDXPipelineRun"
      }
    ]
  },
  "warnings": []
}
```
**Actual Result:**
```json
{
  "code": 1,
  "context": "Test",
  "commandName": "Test",
  "message": "<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>",
  "name": "ERROR_HTTP_431",
  "status": 1,
  "stack": "ERROR_HTTP_431: <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>\n    at HttpApi.getError (C:\\Program Files\\sf\\client\\node_modules\\jsforce\\lib\\http-api.js:252:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async C:\\Program Files\\sf\\client\\node_modules\\jsforce\\lib\\http-api.js:122:23\n    at async Query._execute (C:\\Program Files\\sf\\client\\node_modules\\jsforce\\lib\\query.js:413:18)\n    at async C:\\Program Files\\sf\\client\\node_modules\\jsforce\\lib\\query.js:346:9",
  "exitCode": 1,
  "warnings": []
}
```
**Note:**
Apex run test is working as expected when command is issued with RunSpecifiedTests.

**Command:**
sf apex run test --test-level RunSpecifiedTests --class-names SFDXPipelineRunTest --json > test_outcome_full.json --wait 180

**Result:**
```json
{
  "status": 0,
  "result": {
    "summary": {
      "outcome": "Passed",
      "testsRan": 1,
      "passing": 1,
      "failing": 0,
      "skipped": 0,
      "passRate": "100%",
      "failRate": "0%",
      "testStartTime": "Wed Aug 16 2023 3:44:51 PM",
      "testExecutionTime": "11 ms",
      "testTotalTime": "11 ms",
      "commandTime": "773 ms",
      "hostname": "",
      "orgId": "",
      "username": "",
      "testRunId": "707Oy000000C_Id_should_be_here",
      "userId": ""
    },
    "tests": [
      {
        "Id": "07MOy00000094w5MAA",
        "QueueItemId": "709Oy0000005J3dIAE",
        "StackTrace": null,
        "Message": null,
        "AsyncApexJobId": "707Oy000000bvHCIAY",
        "MethodName": "SFDXPipelineRun",
        "Outcome": "Pass",
        "ApexClass": {
          "Id": "01p79000000EXTyAAO",
          "Name": "SFDXPipelineRunTest",
          "NamespacePrefix": null
        },
        "RunTime": 11,
        "FullName": "SFDXPipelineRunTest.SFDXPipelineRun"
      }
    ]
  },
  "warnings": []
}
```

### System Information

- We are running bash script.

```json
{
  "cliVersion": "@salesforce/cli/2.3.8",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\vmedaram\\AppData\\Local\\sf\\client\\2.3.8-7de1e6e",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.3 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.15 (core)",
    "@oclif/plugin-not-found 2.3.34 (core)",
    "@oclif/plugin-plugins 3.1.8 (core)",
    "@oclif/plugin-search 0.0.21 (core)",
    "@oclif/plugin-update 3.1.28 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.3.8 (core)",
    "apex 2.3.9 (core)",
    "auth 2.8.10 (core)",
    "data 2.5.4 (core)",
    "deploy-retrieve 1.16.5 (core)",
    "info 2.6.35 (core)",
    "limits 2.3.27 (core)",
    "login 1.2.23 (core)",
    "org 2.9.28 (core)",
    "schema 2.3.21 (core)",
    "settings 1.4.21 (core)",
    "sobject 0.1.42 (core)",
    "source 2.10.28 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.7 (core)",
    "trust 2.5.1 (core)",
    "user 2.3.27 (core)"
  ]
}
```
### Additional information
**Doctor Command Results:**

Attached command-debug log and command-studout log with this.

**My observation:** In command-stdout.log - line number 1116, request is having large URL. The error we are getting is 431-This can happen because the total size of the request headers is too large or it can happen because a single header field is too large.
[1692181008593-command-debug.log](https://github.com/forcedotcom/cli/files/12358478/1692181008593-command-debug.log)
[1692181008593-command-stdout.log](https://github.com/forcedotcom/cli/files/12358479/1692181008593-command-stdout.log)

**Comment by mshanemc** [comment]
Yep, the Salesforce REST API has size limits.  The CLI can't do anything to get around them.
It doesn't provide a testRunId because the request failed (too long) before it made it to the actual test runner.

You should either break this dynamic specification of tests into multiple test runs OR create some test suites and use `--suite-names` to specify groups of tests (1 suite can encompass a lot of tests and that makes the URL smaller)
