### ISSUE TITLE
Cannot read properties of null (reading 'replace') when trying to retrieve Apex Test results

### ISSUE THREAD

**Issue by Garnet-Merrill** [forcedotcom/cli#2433]
### Summary
I am running the following command to retrieve Apex test run results.
sf apex get test -o <org> --test-run-id <run-ID> -d <path> --code-coverage -r human

### Expected result
This should produce 6 files in the specified directory

### Actual result
I received the following error.
Error (1): Cannot read properties of null (reading 'replace')

This error only occurs if if use the -d flag to specify where to save the results.  If I run without the -d and path, I will get data returned which I can redirect to a file.

I have a similar problem when I try to use the -d parameter in running the test, although the error is slightly different.

### Steps To Reproduce
I've updated the sf client to ensure I had the latest version.  I've run this against different SalesForce Orgs and specified different directories to eliminate environmental issues.  I've also run this from a Mac and Linux.  Everything seems to run fine until I specify the directory output.  (I've tried relative and full paths) 

### System Information
{
  "cliVersion": "@salesforce/cli/2.2.7",
  "architecture": "linux-arm64",
  "nodeVersion": "node-v20.5.0",
  "osVersion": "Linux 5.15.49-linuxkit-pr",
  "shell": "ash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.3 (core)",
    "@oclif/plugin-commands 2.2.20 (core)",
    "@oclif/plugin-help 5.2.14 (core)",
    "@oclif/plugin-not-found 2.3.34 (core)",
    "@oclif/plugin-plugins 3.1.8 (core)",
    "@oclif/plugin-search 0.0.21 (core)",
    "@oclif/plugin-update 3.1.28 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.45 (core)",
    "@oclif/plugin-which 2.2.27 (core)",
    "@salesforce/cli 2.2.7 (core)",
    "apex 2.3.8 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.3 (core)",
    "deploy-retrieve 1.16.3 (core)",
    "info 2.6.32 (core)",
    "limits 2.3.27 (core)",
    "login 1.2.22 (core)",
    "org 2.9.27 (core)",
    "schema 2.3.21 (core)",
    "settings 1.4.21 (core)",
    "sobject 0.1.40 (core)",
    "source 2.10.27 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.7 (core)",
    "trust 2.4.34 (core)",
    "user 2.3.27 (core)"
  ]

### Debug Information
Running the get test command above, I see the following:

...
  sf:connection DEBUG request: {"method":"GET","url":"https://wexinc.my.salesforce.com/services/data/v58.0/tooling/query?q=SELECT%20PercentCovered%20FROM%20ApexOrgWideCoverage","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +3s
Error (1): Cannot read properties of null (reading 'replace')

*** Internal Diagnostic ***

TypeError: Cannot read properties of null (reading 'replace')
    at JUnitReporter.xmlEscape (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/reporters/junitReporter.js:71:14)
    at JUnitReporter.buildTestCases (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/reporters/junitReporter.js:53:37)
    at JUnitReporter.format (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/reporters/junitReporter.js:27:24)
    at TestService.<anonymous> (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:208:81)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:4:12)
    at TestService.writeResultFiles (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/tests/testService.js:174:16)
    at TestReporter.report (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-apex/lib/reporters/testReporter.js:34:31)
******
...

**Comment by Garnet-Merrill** [comment]
{
  "cliVersion": "@salesforce/cli/2.5.8",
  "architecture": "linux-arm64",
  "nodeVersion": "node-v20.5.0",
  "osVersion": "Linux 5.15.49-linuxkit-pr",
  "shell": "ash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.22 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.6 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.30 (core)",
    "@salesforce/cli 2.5.8 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.6 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.30 (core)",
    "login 1.2.26 (core)",
    "org 2.10.0 (core)",
    "schema 2.3.23 (core)",
    "settings 1.4.25 (core)",
    "sobject 0.2.4 (core)",
    "source 2.10.31 (core)",
    "telemetry 2.3.0 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.1 (core)",
    "user 2.3.28 (core)"
  ]
}

**Comment by pogilvieCB** [comment]
I'm having a similar problem

```
sf package version list -v devhub
    TypeError: Cannot read properties of undefined (reading 'prototype')
```
