### ISSUE TITLE
Unable to install official plugins: Warning: Accessing non-existent property 'register' of module exports inside circular dependency, TypeError: common.register is not a function

### ISSUE THREAD

**Issue by williamtsoi-sf** [forcedotcom/cli#2720]
### Summary
Hi,

I'm having an issue with installing plugins, I've tried to install the plugins `@salesforce/sfdx-scanner` and `custom-metadata`, and they both had the same error:

Stack trace:
```
sf plugins install @salesforce/sfdx-scanner
    TypeError: common.register is not a function
(node:32784) Warning: Accessing non-existent property 'register' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: common.register is not a function
    at Object.<anonymous> (/Users/******/.nvm/versions/node/v20.6.0/lib/node_modules/@salesforce/cli/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at /Users/******/.nvm/versions/node/v20.6.0/lib/node_modules/@salesforce/cli/node_modules/shelljs/shell.js:25:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/******/.nvm/versions/node/v20.6.0/lib/node_modules/@salesforce/cli/node_modules/shelljs/shell.js:24:23)

Node.js v20.6.0
```

sf doctor:
```
=== Running all diagnostics

pass - salesforcedx plugin not installed
pass - no linked plugins
pass - [@salesforce/plugin-source] sourceApiVersion matches apiVersion
pass - [@salesforce/plugin-source] default target DevHub max apiVersion matches default target org max apiVersion
warn - [@salesforce/plugin-source] sourceApiVersion matches default target org max apiVersion
pass - using latest or latest-rc CLI version
```

### Steps To Reproduce
_This does not seem to be related to a specific repo, so I have not provided a repo._

1. I'm using the sf-cli installed via npm (latest version): `npm install --gloabl @salesforce/cli`
2. I'm trying to run the command `sf plugins install custom-metadata`

### Expected result
plguins installed

### Actual result
error + trace as shown above, and this without the trace:
```
sf plugins install custom-metadata         
(node:44676) Warning: Accessing non-existent property 'register' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
    TypeError: common.register is not a function
```

### System Information
Using: zsh

sf version --verbose --json 
```json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.27.6",
  "nodeVersion": "node-v20.6.0",
  "osVersion": "Darwin 23.2.0",
  "rootPath": "/Users/******/.nvm/versions/node/v20.6.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.23 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.27.6 (core)",
    "apex 3.0.22 (core)",
    "auth 3.3.6 (core)",
    "data 3.0.18 (core)",
    "deploy-retrieve 3.2.9 (core)",
    "info 3.0.19 (core)",
    "limits 3.1.6 (core)",
    "marketplace 1.0.20 (core)",
    "org 3.3.10 (core)",
    "packaging 2.1.4 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.21 (core)",
    "sobject 1.1.6 (core)",
    "source 3.1.8 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.12 (core)",
    "trust 3.3.4 (core)",
    "user 3.2.6 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
Hey, @williamtsoi-sf 

There were some other reports of problems with node 20.6.0 ex: https://github.com/shelljs/shelljs/issues/1133.  It's patched in later node versions (looks like you can even use 20.6.1 if the `.6` is really important to you.  https://github.com/nodejs/node/releases/tag/v20.6.1

If you're updating, you might as well use the current 20.11.0 that's been out for about a month.
