### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mikesobczak** [forcedotcom/cli#280]
### Summary

Trying to deploy code to an org by right-clicking on the the package.xml and selecting SFDX: Deploy source in manifest to org.  The console displays "RangeError: Maximum call stack size exceeded"

### Steps To Reproduce:

1.  Right-click on package.xml
1.  Select the "SFDX: Deploy source in manifest to org" option

### Expected result

Code deployed to org.

### Actual result

Starting SFDX: Deploy Source to Org

18:12:54.152 sfdx force:source:deploy --manifest c:\projects\VS Code\B2B User Budgets 4.11\manifest\package.xml --json --loglevel fatal
18:13:02.950 sfdx force:source:deploy --manifest c:\projects\VS Code\B2B User Budgets 4.11\manifest\package.xml --json --loglevel fatal ended with exit code 1

RangeError: Maximum call stack size exceeded

### Additional information

I can create a package version from the code in my workspace.  Issue must be with my package.xml, but it is valid XML as far as I can tell.

**VS Code Version**: 47.10.0

**SFDX CLI Version**: sfdx-cli/7.41.0-2a5f766389 win32-x64 node-v10.15.3

**OS and version**: Windows 10

**Comment by lcampos** [comment]
Hi @mikesobczak thanks for opening this issue. We released a fix for this a couple of releases ago so I'm wondering if there's something we missed or some plugin config that's outdated. Could you add the output of running `sfdx plugins --core` ?

**Comment by lcampos** [comment]
Also, if you run the deploy command directly in the CLI adding `--dev-debug` what's the stack trace you get ?

**Comment by mikesobczak** [comment]
I figured out what the issue was. My package.xml referenced a WorkflowRule and WorkflowFieldUpdate that were not included as meta data.  I wish the error message could be more descriptive.  Sorry for the trouble!

**Comment by lcampos** [comment]
Thanks for the details @mikesobczak, we've been able to replicate the issue on our side and we'll leave this open for now to address the error message.

**Comment by mserinjane** [comment]
@lcampos We are having this issue

Output from sfdx plugins --core

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.4.1 (core)
generator 1.1.2 (core)
salesforcedx 47.16.0 (core)
├─ salesforcedx-templates 47.17.0 (core)
└─ salesforce-alm 47.15.0 (core)
sfdx-cli 7.43.1 (core)

**Comment by mserinjane** [comment]
ERROR running force:source:deploy: Maximum call stack size exceeded

*** Internal Diagnostic ***

RangeError: Maximum call stack size exceeded
at RegExp.test (<anonymous>)
at Function.enabled (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\debug\src\common.js:220:32)
at createDebug (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\debug\src\common.js:119:33)
at Object.apply (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\lazy-require\lib\LazyLoader.js:173:36)
at new DefaultMetadataType (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\metadataTypeImpl\defaultMetadataType.js:22:23)
at new NondecomposedTypesWithChildrenMetadataType (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\metadataTypeImpl\nondecomposedTypesWithChildrenMetadataType.js:16:1)
at new CustomLabelsMetadataType (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\metadataTypeImpl\customLabelsMetadataType.js:10:1)
at Function.getMetadataTypeFromMetadataName (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\metadataTypeFactory.js:179:44)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:193:72)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)
at Object.exports.loadSourceElement (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:219:28)

From previous event:
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)

From previous event:
at SourceApiCommand.execute (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\lib\source\sourceApiCommand.js:47:14)
at SourceDeployCommand.execLegacyCommand (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\ToolbeltCommand.js:148:43)

Outer stack:
at Function.wrap (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@salesforce\core\lib\sfdxError.js:151:27)
at SourceDeployCommand.catch (......AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\salesforce-alm\dist\ToolbeltCommand.js:247:46)
******

**Comment by mserinjane** [comment]
@lcampos Node version: 10.14.1 with problem, Node version without problems 8.11.1

**Comment by mserinjane** [comment]
@lcampos Turns out we were missing the custom labels directory :(

**Comment by lcampos** [comment]
@mserinjane ok, this is in the same piece of code. Could you confirm which version of the CLI you're on (sfdx --version) and which core plugins you're running (sfdx plugins --core) ?
