### ISSUE TITLE
Cannot read property 'getAggregateSourceElements' of undefined

### ISSUE THREAD

**Issue by reda-benhemmouche** [forcedotcom/cli#349]
### Summary
I get error without details during the execution of the command `sfdx force:source:convert`

### Steps To Reproduce:

1.  This is step 1.
run the command `sfdx force:source:convert`
1.  This is step 2. 
get error 
`ERROR running force:source:convert:  Cannot read property 'getAggregateSourceElements' of undefined`

### Expected result

Sometime the error is related to incorrect folder name of non-supported file extension.
We need the details about the metadatas (file, folders) that are  causing this error to be able to fix it.

### Actual result

No details about the metadata causing this error.
```
$ sfdx force:source:convert -d ./src/ --json
{
    "status": 1,
    "name": "TypeError",
    "message": "Cannot read property 'getAggregateSourceElements' of undefined",
    "exitCode": 1,
    "commandName": "SourceConvertCommand",
    "stack": "TypeError: Cannot read property 'getAggregateSourceElements' of undefined\n    at initWorkspaceAdapter.then.catch.then (/Users/redabenhemmouche/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:73:52)\nOuter stack:\n    at Function.wrap (/Users/redabenhemmouche/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at SourceConvertCommand.catch (/Users/redabenhemmouche/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)",
    "warnings": []
}

```

### Additional information

```

**SFDX CLI Version** (to find the version of the CLI engine run sfdx --version):

`sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3`

**SFDX plugin Version** (to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)
sfdx-essentials 1.0.3
sfpowerkit 1.30.1

```
**OS and version**:
mac os high sierra
version: 10.13.6 (17G8037)

**Comment by clairebianchi** [comment]
@reda-benhemmouche can you please update your CLI version and try to run the command again. We believe we fixed this issue.
