### ISSUE TITLE
SyntaxError: Unexpected Token } when using sfdx force:mdapi:retrieve

### ISSUE THREAD

**Issue by dkelll** [forcedotcom/cli#362]
### Summary

I am trying to pull metadata from a sandbox using sfdx force:mdapi:retrieve and I receive an error "SyntaxError: Unexpected Token }". This happens with VS Code through the metadata explorer, through the right-click context menu, and through the command in the command palette 

### Steps To Reproduce:

1.  Connect sfdx to a sandbox (i.e. not a scratch org)
1.  Run `sfdx force:source:retrieve --sourcepath /Users/dkelll/mySfdxApp/manifest/flexipages/myFlexipage.flexipage`
1. Receive the error

### Expected result

Metadata gets pulled from the sandbox.

### Actual result
Error received:
```
myMbp:mySfdxApp dkelll$ sfdx force:source:retrieve --sourcepath /Users/dkelll/mySfdxApp/manifest/flexipages/myFlexipage.flexipage

/Users/dkelll/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/fineGrainTrackingCommitStrategy.js:21
});
^
SyntaxError: Unexpected token }
    at NativeCompileCache._moduleCompile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Function._load (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (~/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/decompositionStrategyFactory.js:12:43)
    at Module._compile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Function._load (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
```

### Additional information
Looking at the `fineGrainTrackingCommitStrategy.js` file it looks like it wasn't compiled properly:
![image](https://user-images.githubusercontent.com/1993010/78414845-c87eca80-75e3-11ea-9a59-9632b153dfab.png)

I tried reinstalling to no avail. Not really sure where to go from here. 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.53.0 darwin-x64 node-v12.9.1`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
dependencies-cli 2.0.1
generator 1.1.2 (core)
salesforcedx 48.8.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.8.0
└─ salesforce-alm 48.8.0

sfdx-cli 7.53.0 (core)
```
**OS and version**:

![image](https://user-images.githubusercontent.com/1993010/78414925-3a571400-75e4-11ea-9035-a94e58bbc475.png)

**Comment by shetzel** [comment]
You are mixing `source:retrieve` with `mdapi:retrieve`.  Use `source:retrieve` when working with metadata in source format, and `mdapi:retrieve` when working with metadata in mdapi format.  You'll get errors like this if you mix them.

**Comment by dkelll** [comment]
I just tried again and both methods are giving me that error. To make sure I had my args right when trying the source method I tried with `-h` and interestingly enough I'm getting the same thing:

```
myMbp:mySfdxApp dkelll$ sfdx force:source:retrieve -h
/Users/dkelll/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/fineGrainTrackingCommitStrategy.js:21
});
^
SyntaxError: Unexpected token }
    at NativeCompileCache._moduleCompile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Function._load (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (~/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/decompositionStrategyFactory.js:12:43)
    at Module._compile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Function._load (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
```

Using `sfdx force:mdapi:retrieve -h` returns as expected but then when I try pulling the metadata using `sfdx force:mdapi:retrieve` it breaks with the same error:

```
myMbp:mySfdxApp dkelll$ sfdx force:mdapi:retrieve -d tmp/ -k tmp/package.xml -r tmp/
ERROR running force:mdapi:retrieve:  Unexpected token } 
```

@shetzel Thoughts? Thanks for your help

**Comment by dkelll** [comment]
Hi @shetzel,

I tried creating a new sfdx project from scratch 

```
myMbp:Projects dkelll$ sfdx force:project:create -n newProject3 --manifest
target dir = /Users/dkelll/Projects
   create newProject3/config/project-scratch-def.json
   create newProject3/README.md
   create newProject3/sfdx-project.json
   create newProject3/manifest/package.xml
   create newProject3/.vscode/extensions.json
   create newProject3/.vscode/launch.json
   create newProject3/.vscode/settings.json
   create newProject3/force-app/main/default/lwc/.eslintrc.json
   create newProject3/scripts/soql/account.soql
   create newProject3/scripts/apex/hello.apex
   create newProject3/.eslintignore
   create newProject3/.forceignore
   create newProject3/.gitignore
   create newProject3/.prettierignore
   create newProject3/.prettierrc
   create newProject3/package.json

myMbp:Projects dkelll$ cd newProject3
myMbp:newProject3 dkelll$
```

I modified the package.xml file to pull an apex class that exists in the sandbox but not locally since this is a new sfdx project.

```
myMbp:newProject3 dkelll$ cat manifest/package.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MyApexClass</members>
        <name>ApexClass</name>
    </types>
    <version>48.0</version>
</Package>
myMbp:newProject3 dkelll$
```

I then tried to pull from the sandbox with `sfdx force:source:retrieve` and still had the issue.

```
myMbp:newProject3 dkelll$ sfdx force:source:retrieve -r manifest/ -x manifest/package.xml
/Users/dkelll/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/fineGrainTrackingCommitStrategy.js:21
});
^
SyntaxError: Unexpected token }
    at NativeCompileCache._moduleCompile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Function._load (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (~/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/decompositionStrategy/decompositionStrategyFactory.js:12:43)
    at Module._compile (/usr/local/lib/node_modules/sfdx-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Function._load (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
myMbp:newProject3 dkelll$
```

So I try pulling as metadata instead of source:

```
myMbp:newProject3 dkelll$ sfdx force:mdapi:retrieve -r manifest/ -k manifest/package.xml
ERROR running force:mdapi:retrieve:  Unexpected token }
myMbp:newProject3 dkelll$
```

I don't think it's an issue with mixing metadata formats because I can't get it to work with neither command.

**Comment by shetzel** [comment]
Yeah that looks like a corrupt installation.  That js file is definitely incomplete.  I'd try reinstalling again but first take these steps to completely wipe your installation:
rm -f /usr/local/bin/sfdx
rm -rf /usr/local/lib/sfdx
rm -rf ~/.local/share/sfdx
rm -rf ~/.config/sfdx
rm -rf ~/Library/Caches/sfdx
rm -rf /usr/local/heroku
rm -rf /usr/local/sfdx
rm -rf /usr/local/lib/heroku
rm -rf /usr/local/bin/heroku
rm -rf ~/.heroku ~/.local/share/heroku ~/.config/heroku ~/.cache/heroku
rm -rf ~/.local/share/sfdx ~/.config/sfdx ~/.cache/sfdx

After wiping it make sure `sfdx` doesn't still somehow point to something and then reinstall either via the installers or npm.

**Comment by dkelll** [comment]
Fixed mate, thanks again for your help!
