### ISSUE TITLE
Package installation fails but exit code is zero

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/cli#393]
### Summary

When a package installation fails, the CLI's exit code is zero (non-error).

### Steps To Reproduce:

I got this when trying to install an unlocked package version that had a class with a certain name that was shared by another class in another unlocked package. The class (an invocable action) was used in a flow.

### Expected result

Error message still the same, but status code 1 instead of 0.

### Actual result

Status code 0.

### Additional information

Since this happened in an automated environment, the command was provided with the `--json` parameter, which might affect its results. But I believe that being an error, the status code should be non-zero.

The error is something like this:
```shell
>>> sfdx force:package:install --targetusername SANDBOX --package 04t000000000000AAA --wait 10 --publishwait 10 --noprompt --json
```

```json
{
    "status": 1,
    "name": "Error",
    "message": "Installation errors: \n1) (The_Action) A_Simple_Action (Action) - Type mapping \"T__record\" is not referenced in Apex action \"MyActionClass\"., Details: The_Action: A_Simple_Action (Action) - Type mapping \"T__record\" is not referenced in Apex action \"MyActionClass\".",
    "exitCode": 1,
    "commandName": "PackageInstallCommand",
    "stack": "Error: Installation errors: \n1) (The_Action) A_Simple_Action (Action) - Type mapping \"T__record\" is not referenced in Apex action \"MyActionClass\"., Details: The_Action: A_Simple_Action (Action) - Type mapping \"T__record\" is not referenced in Apex action \"MyActionClass\".\n    at force.toolingRetrieve.then.request (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/package/packageInstallCommand.js:89:27)\n    at tryCatcher (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\nOuter stack:\n    at Function.wrap (/usr/local/lib/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at PackageInstallCommand.catch (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)",
    "warnings": []
}
```

Using the salesforce/salesforcedx Docker image. No specific version provided, so I assume it is the latest available for that image.

**Comment by clairebianchi** [comment]
@renatoliveira  Thank you for reporting. I am letting the packaging team know.

**Comment by shetzel** [comment]
This should not be happening anymore with the latest CLI releases and plugin-packaging.  Please report a new issue if this is reproducible in the latest CLI.
