### ISSUE TITLE
Enable sfdx force:package:version:list to run outside of a sfdx project

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#416]
When running `sfdx force:package:version:list -v MY_DEV_HUB`, sfdx asks me to run it from within a sfdx project. Since this command returns a list of all my dev hub packages, instead of all package versions of the current project, I don't think that requiring it to run from the root of a sfdx project makes sense.

Response when running this command outside of a sfdx project

````json
{
  "status": 1,
  "name": "InvalidProjectWorkspace",
  "message": "This directory does not contain a valid Salesforce DX project.",
  "exitCode": 1,
  "commandName": "PackageVersionListCommand",
  "stack": "InvalidProjectWorkspace: This directory does not contain a valid Salesforce DX project.\n    at traverseForFile (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\projectDir.js:42:39)\n    at traverseForFile (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\projectDir.js:39:25)\n    at traverseForFile (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\projectDir.js:39:25)\n    at traverseForFile (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\projectDir.js:39:25)\n    at traverseForFile (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\projectDir.js:39:25)\n    at Object.getPath (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\projectDir.js:50:13)\n    at exports.Config.getProjectPath (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\configApi.js:129:44)\n    at exports.Config.getConfigContent (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\core\\configApi.js:336:73)\n    at Object.getPackageAliasesFromId (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\package\\packageUtils.js:441:44)\n    at ids.forEach.id (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\package\\packageVersionListCommand.js:75:50)\n    at Array.forEach (<anonymous>)\n    at records.forEach.record (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\package\\packageVersionListCommand.js:74:25)\n    at Array.forEach (<anonymous>)\n    at force.toolingQuery.then (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\lib\\package\\packageVersionListCommand.js:71:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nOuter stack:\n    at Function.wrap (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at PackageVersionListCommand.catch (C:\\Users\\oricil\\AppData\\Local\\sfdx\\client\\7.58.2-937f666ed4\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:246:46)",
  "warnings": []
}

````

**Comment by yippie** [comment]
Same here, I don't see any reason it needs to be in a project and is useful outside of one
