### ISSUE TITLE
Unable to retrieve Test run report in JSON format for long running test classes

### ISSUE THREAD

**Issue by alokvping** [forcedotcom/cli#440]
Hi,
I am unable to retrieve Test run report in JSON format for long running test classes using sfdx force:apex:test:report command.

It gives me the below error:

{
  "status": 1,
  "name": "TestResultRetrievalFailed",
  "message": "<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>",
  "exitCode": 1,
  "commandName": "ApexTestReportCommand",
  "stack": "ERROR_HTTP_414: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>\n    at HttpApi.getError (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\jsforce\\lib\\http-api.js:250:13)\n    at C:\\Program Files\\Salesforce CLI\\client\\node_modules\\jsforce\\lib\\http-api.js:95:22\n    at tryCallOne (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\promise\\lib\\core.js:37:12)\n    at C:\\Program Files\\Salesforce CLI\\client\\node_modules\\promise\\lib\\core.js:123:15\n    at flush (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\asap\\raw.js:50:29)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\nOuter stack:\n    at Function.wrap (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at ApexTestReportCommand.catch (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:246:46)",
  "warnings": []
}
 
### Steps To Reproduce:
1. Run test apex classes using sfdx force:apex:test:run
2. You will get the test run ID from above command
3. Run command: sfdx force:apex:test:report -i <testrunID> -c --json -d c:\
4. After 1 hour of long test run, I get below error and NO JSON is generated

{
  "status": 1,
  "name": "TestResultRetrievalFailed",
  "message": "<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>",
  "exitCode": 1,
  "commandName": "ApexTestReportCommand",
  "stack": "ERROR_HTTP_414: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>\n    at HttpApi.getError (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\jsforce\\lib\\http-api.js:250:13)\n    at C:\\Program Files\\Salesforce CLI\\client\\node_modules\\jsforce\\lib\\http-api.js:95:22\n    at tryCallOne (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\promise\\lib\\core.js:37:12)\n    at C:\\Program Files\\Salesforce CLI\\client\\node_modules\\promise\\lib\\core.js:123:15\n    at flush (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\asap\\raw.js:50:29)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\nOuter stack:\n    at Function.wrap (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at ApexTestReportCommand.catch (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:246:46)",
  "warnings": []
}

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.62.1-309fe6da17 win32-x64 node-v10.20.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 3.0.0 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.9.1 (core)
generator 1.1.2 (core)
salesforcedx 48.18.1 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ custom-metadata 1.0.0 (core)
└─ salesforce-alm 48.19.0 (core)
**OS and version**:
Windows 10 - 4 bit

**Comment by iowillhoit** [comment]
Hey :wave: I am grooming some old Github issues. This bug has been fixed for quite a while. 
A [constant is set here](https://github.com/forcedotcom/salesforcedx-apex/blob/55ab3b1dfb01a795d5f5403595e4e459ecc1fd06/src/tests/constants.ts#L8-L12) to match sure they queries do not hit the `URI Too Long` error. The queries themselves [are chunked here](https://github.com/forcedotcom/salesforcedx-apex/blob/55ab3b1dfb01a795d5f5403595e4e459ecc1fd06/src/tests/codeCoverage.ts#L200-L207) to reduce their size.

You can see this for yourself by running this on a project with _a lot_ of tests:
`DEBUG=* sf apex get test -i THE_TEST_RUN_ID --code-coverage`

You will see debug logs similar to:
```sh
[11:11:56.799] DEBUG (sf:connection): request
    method: "GET"
    url: "https://nosoftware-momentum-15-dev-ed.scratch.my.salesforce.com/services/data/v59.0/tooling/query?q=SELECT%20ApexTestClassId%2C%20ApexClassOrTrigger.Id%2C%20ApexClassOrTrigger.Name%2C%20TestMethodName%2C%20NumLinesCovered%2C%20NumLinesUncovered%2C%20Coverage%20FROM%20ApexCodeCoverage%20WHERE%20ApexTestClassId%20IN%20('01p03000008FYvDAAW'%2C'01p03000008FYubAAG'%2C'01p03000008FYtLAAW'%2C'01p03000008FYsjAAG'%2C'01p03000008FYtNAAW'%2C'01p03000008FYslAAG'%2C'01p03000008FYtHAAW'%2C'01p03000008FYsfAAG'%2C'01p03000008FYtJAAW'%2C'01p03000008FYshAAG'%2C'01p03000008FYtTAAW'%2C'01p03000008FYu5AAG'%2C'01p03000008FYsrAAG'%2C'01p03000008FYtVAAW'%2C'01p03000008FYu7AAG'%2C'01p03000008FYstAAG'%2C'01p03000008FYtPAAW'%2C'01p03000008FYu1AAG'%2C'01p03000008FYsnAAG'%2C'01p03000008FYtRAAW'%2C'01p03000008FYu3AAG'%2C'01p03000008FYspAAG'%2C'01p03000008FYszAAG'%2C'01p03000008FYtXAAW'%2C'01p03000008FYu9AAG'%2C'01p03000008FYsvAAG'%2C'01p03000008FYtZAAW'%2C'01p03000008FYsxAAG'%2C'01p03000008FYtdAAG'%2C'01p03000008FYuDAAW'%2C'01p03000008FYtfAAG'%2C'01p03000008FYuFAAW'%2C'01p03000008FYtbAAG'%2C'01p03000008FYuBAAW'%2C'01p03000008FYrjAAG'%2C'01p03000008FYsJAAW'%2C'01p03000008FYrlAAG'%2C'01p03000008FYsLAAW'%2C'01p03000008FYrfAAG'%2C'01p03000008FYsFAAW'%2C'01p03000008FYrhAAG'%2C'01p03000008FYsHAAW'%2C'01p03000008FYrrAAG'%2C'01p03000008FYsRAAW'%2C'01p03000008FYt3AAG'%2C'01p03000008FYrtAAG'%2C'01p03000008FYsTAAW'%2C'01p03000008FYt5AAG'%2C'01p03000008FYrnAAG'%2C'01p03000008FYsNAAW'%2C'01p03000008FYrpAAG'%2C'01p03000008FYsPAAW'%2C'01p03000008FYt1AAG'%2C'01p03000008FYrzAAG'%2C'01p03000008FYsZAAW'%2C'01p03000008FYrvAAG'%2C'01p03000008FYsVAAW'%2C'01p03000008FYt7AAG'%2C'01p03000008FYrxAAG'%2C'01p03000008FYsXAAW'%2C'01p03000008FYt9AAG'%2C'01p03000008FZ3FAAW'%2C'01p03000008FZ2dAAG'%2C'01p03000008FYRHAA4'%2C'01p03000008FZ3HAAW'%2C'01p03000008FYQfAAO'%2C'01p03000008FZ2fAAG'%2C'01p03000008FYRRAA4'%2C'01p03000008FZ3RAAW'%2C'01p03000008FZ43AAG'%2C'01p03000008FYQpAAO'%2C'01p03000008FYS2AAO'%2C'01p03000008FZ2pAAG'%2C'01p03000008FYRTAA4'%2C'01p03000008FYS5AAO'%2C'01p03000008FZ3TAAW'%2C'01p03000008FZ45AAG'%2C'01p03000008FYQrAAO'%2C'01p03000008FZ2rAAG'%2C'01p03000008FYRNAA4'%2C'01p03000008FZ3NAAW'%2C'01p03000008FYQlAAO'%2C'01p03000008FZ2lAAG'%2C'01p03000008FYRPAA4'%2C'01p03000008FYS1AAO'%2C'01p03000008FZ3PAAW'%2C'01p03000008FZ41AAG'%2C'01p03000008FYQnAAO'%2C'01p03000008FZ2nAAG'%2C'01p03000008FYQyAAO'%2C'01p03000008FYRZAA4'%2C'01p03000008FZ3ZAAW'%2C'01p03000008FYQxAAO'%2C'01p03000008FZ2xAAG'%2C'01p03000008FZ2zAAG'%2C'01p03000008FYRVAA4'%2C'01p03000008FYS7AAO'%2C'01p03000008FZ3VAAW'%2C'01p03000008FZ47AAG'%2C'01p03000008FYQtAAO'%2C'01p03000008FZ2tAAG'%2C'01p03000008FYRXAA4'%2C'01p03000008FYS9AAO'%2C'01p03000008FZ3XAAW'%2C'01p03000008FZ49AAG'%2C'01p03000008FYQvAAO'%2C'01p03000008FZ2vAAG'%2C'01p03000008FYRbAAO'%2C'01p03000008FZ3bAAG'%2C'01p03000008FYSBAA4'%2C'01p03000008FZ4BAAW'%2C'01p03000008FYRdAAO'%2C'01p03000008FZ3dAAG'%2C'01p03000008FYSDAA4'%2C'01p03000008FZ4DAAW'%2C'01p03000008FZ1hAAG'%2C'01p03000008FZ2HAAW'%2C'01p03000008FZ1jAAG'%2C'01p03000008FYQJAA4'%2C'01p03000008FZ2JAAW'%2C'01p03000008FZ1dAAG'%2C'01p03000008FYQDAA4'%2C'01p03000008FZ2DAAW'%2C'01p03000008FYQGAA4'%2C'01p03000008FZ1fAAG'%2C'01p03000008FYQFAA4'%2C'01p03000008FZ2FAAW'%2C'01p03000008FZ1pAAG'%2C'01p03000008FYQPAA4'%2C'01p03000008FYR1AAO'%2C'01p03000008FZ2PAAW'%2C'01p03000008FZ31AAG'%2C'01p03000008FZ1rAAG'%2C'01p03000008FYQRAA4'%2C'01p03000008FYR3AAO'%2C'01p03000008FZ2RAAW'%2C'01p03000008FZ33AAG'%2C'01p03000008FZ1lAAG'%2C'01p03000008FYQLAA4'%2C'01p03000008FZ2LAAW'%2C'01p03000008FZ1nAAG'%2C'01p03000008FYQNAA4'%2C'01p03000008FZ2NAAW'%2C'01p03000008FYPxAAO'%2C'01p03000008FZ1xAAG'%2C'01p03000008FYQXAA4'%2C'01p03000008FYR9AAO'%2C'01p03000008FZ2XAAW'%2C'01p03000008FZ39AAG'%2C'01p03000008FYPzAAO'%2C'01p03000008FZ1zAAG'%2C'01p03000008FYQZAA4'%2C'01p03000008FZ2ZAAW'%2C'01p03000008FZ1tAAG'%2C'01p03000008FYQTAA4'%2C'01p03000008FYR5AAO'%2C'01p03000008FZ2TAAW'%2C'01p03000008FZ35AAG'%2C'01p03000008FZ1vAAG'%2C'01p03000008FYQVAA4'%2C'01p03000008FYR7AAO'%2C'01p03000008FZ2VAAW'%2C'01p03000008FZ37AAG'%2C'01p03000008FYRBAA4'%2C'01p03000008FZ3BAAW'%2C'01p03000008FYQcAAO'%2C'01p03000008FYRDAA4'%2C'01p03000008FZ3DAAW'%2C'01p03000008FYQbAAO'%2C'01p03000008FZ2bAAG'%2C'01p03000008FZ1HAAW'%2C'01p03000008FZ0fAAG'%2C'01p03000008FZ1JAAW'%2C'01p03000008FZ0hAAG'%2C'01p03000008FZ1DAAW'%2C'01p03000008FZ0bAAG'%2C'01p03000008FZ1FAAW'%2C'01p03000008FZ0dAAG'%2C'01p03000008FYQ1AAO'%2C'01p03000008FpOhAAK'%2C'01p03000008FooHAAS'%2C'01p03000008FpPHAA0'%2C'01p03000008FonjAAC'%2C'01p03000008FpOjAAK'%2C'01p03000008FooJAAS'%2C'01p03000008FpPJAA0'%2C'01p03000008FondAAC'%2C'01p03000008FpOdAAK'%2C'01p03000008FooDAAS'%2C'01p03000008FpPDAA0'%2C'01p03000008FonfAAC'%2C'01p03000008FpOfAAK'%2C'01p03000008FooFAAS'%2C'01p03000008FpPFAA0'%2C'01p03000008FolnAAC'%2C'01p03000008FpMnAAK'%2C'01p03000008FomNAAS'%2C'01p03000008FpNNAA0'%2C'01p03000008FolpAAC'%2C'01p03000008FpMpAAK'%2C'01p03000008FomPAAS'%2C'01p03000008Fon1AAC'%2C'01p03000008FpNPAA0'%2C'01p03000008FpO1AAK'%2C'01p03000008FoljAAC'%2C'01p03000008FpMjAAK'%2C'01p03000008FomJAAS'%2C'01p03000008FpNJAA0'%2C'01p03000008FollAAC'%2C'01p03000008FpMlAAK'%2C'01p03000008FomLAAS'%2C'01p03000008FpNLAA0'%2C'01p03000008FolvAAC'%2C'01p03000008FpMvAAK'%2C'01p03000008FomVAAS'%2C'01p03000008Fon7AAC'%2C'01p03000008FpNVAA0'%2C'01p03000008FpO7AAK'%2C'01p03000008FolxAAC'%2C'01p03000008FpMxAAK'%2C'01p03000008FomXAAS'%2C'01p03000008Fon9AAC'%2C'01p03000008FpNXAA0'%2C'01p03000008FpO9AAK'%2C'01p03000008FolrAAC'%2C'01p03000008FpMrAAK'%2C'01p03000008FomRAAS'%2C'01p03000008Fon3AAC'%2C'01p03000008FpNRAA0'%2C'01p03000008FpO3AAK'%2C'01p03000008FoltAAC'%2C'01p03000008FpMtAAK'%2C'01p03000008FomTAAS'%2C'01p03000008Fon5AAC'%2C'01p03000008FpNTAA0'%2C'01p03000008FpO5AAK'%2C'01p03000008FonBAAS'%2C'01p03000008FpOBAA0'%2C'01p03000008Fp7VAAS'%2C'01p03000008Fp87AAC'%2C'01p03000008FoUtAAK'%2C'01p03000008Fp6tAAC'%2C'01p03000008FoVbAAK'%2C'01p03000008Fp7bAAC'%2C'01p03000008FoWBAA0'%2C'01p03000008Fp8BAAS'%2C'01p03000008FoUzAAK'%2C'01p03000008Fp6zAAC'%2C'01p03000008FoVhAAK'%2C'01p03000008Fp7hAAC'%2C'01p03000008FoWHAA0'%2C'01p03000008Fp8HAAS'%2C'01p03000008FoVjAAK'%2C'01p03000008Fp7jAAC'%2C'01p03000008FoWJAA0'%2C'01p03000008Fp8JAAS'%2C'01p03000008FoVdAAK'%2C'01p03000008Fp7dAAC'%2C'01p03000008FoWDAA0'%2C'01p03000008Fp8DAAS'%2C'01p03000008FoVfAAK'%2C'01p03000008Fp7fAAC'%2C'01p03000008FoWFAA0'%2C'01p03000008Fp8FAAS'%2C'01p03000008FoVpAAK'%2C'01p03000008Fp7pAAC'%2C'01p03000008FoWPAA0'%2C'01p03000008FoX1AAK'%2C'01p03000008Fp8PAAS'%2C'01p03000008Fp91AAC'%2C'01p03000008FoVrAAK'%2C'01p03000008Fp7rAAC'%2C'01p03000008FoWRAA0'%2C'01p03000008FoX3AAK'%2C'01p03000008Fp8RAAS'%2C'01p03000008Fp93AAC'%2C'01p03000008FoVlAAK'%2C'01p03000008Fp7lAAC'%2C'01p03000008FoWLAA0'%2C'01p03000008Fp8LAAS'%2C'01p03000008FoVnAAK'%2C'01p03000008Fp7nAAC'%2C'01p03000008FoWNAA0'%2C'01p03000008Fp8NAAS'%2C'01p03000008Fp5vAAC'%2C'01p03000008FoUVAA0'%2C'01p03000008FoV7AAK'%2C'01p03000008Fp6VAAS'%2C'01p03000008Fp77AAC'%2C'01p03000008Fp5xAAC'%2C'01p03000008FoUXAA0'%2C'01p03000008FoV9AAK'%2C'01p03000008Fp6XAAS'%2C'01p03000008Fp79AAC'%2C'01p03000008Fp5rAAC'%2C'01p03000008FoV3AAK'%2C'01p03000008Fp6RAAS'%2C'01p03000008Fp73AAC'%2C'01p03000008Fp5tAAC'%2C'01p03000008FoUTAA0'%2C'01p03000008FoV5AAK'%2C'01p03000008Fp6TAAS'%2C'01p03000008Fp75AAC'%2C'01p03000008FoVBAA0'%2C'01p03000008Fp7BAAS'%2C'01p03000008Fp5zAAC'%2C'01p03000008FoUZAA0'%2C'01p03000008Fp6ZAAS'%2C'01p03000008FoVHAA0'%2C'01p03000008Fp7HAAS'%2C'01p03000008FoUfAAK'%2C'01p03000008Fp6fAAC'%2C'01p03000008FoVJAA0'%2C'01p03000008Fp7JAAS'%2C'01p03000008FoUhAAK'%2C'01p03000008Fp6hAAC'%2C'01p03000008FoVDAA0'%2C'01p03000008Fp7DAAS'%2C'01p03000008FoUbAAK'%2C'01p03000008Fp6bAAC'%2C'01p03000008FoVFAA0'%2C'01p03000008Fp7FAAS'%2C'01p03000008FoUdAAK'%2C'01p03000008Fp6dAAC'%2C'01p03000008FoVPAA0'%2C'01p03000008FoW1AAK'%2C'01p03000008Fp7PAAS'%2C'01p03000008Fp81AAC'%2C'01p03000008FoUnAAK'%2C'01p03000008Fp6nAAC'%2C'01p03000008FoVRAA0'%2C'01p03000008FoW3AAK'%2C'01p03000008Fp7RAAS'%2C'01p03000008Fp83AAC'%2C'01p03000008FoUpAAK'%2C'01p03000008Fp6pAAC'%2C'01p03000008FoVLAA0'%2C'01p03000008Fp7LAAS'%2C'01p03000008FoUjAAK'%2C'01p03000008Fp6jAAC'%2C'01p03000008FoVNAA0'%2C'01p03000008Fp7NAAS'%2C'01p03000008FoUlAAK'%2C'01p03000008Fp6lAAC'%2C'01p03000008Fp5VAAS'%2C'01p03000008Fp67AAC'%2C'01p03000008Fp4tAAC'%2C'01p03000008Fp5XAAS'%2C'01p03000008Fp69AAC'%2C'01p03000008Fp4vAAC'%2C'01p03000008FpBvAAK'%2C'01p03000008FobZAAS'%2C'01p03000008FpCZAA0'%2C'01p03000008FoaxAAC'%2C'01p03000008FpBxAAK'%2C'01p03000008FpAbAAK'%2C'01p03000008FoaBAAS'%2C'01p03000008FpBBAA0'%2C'01p03000008FpAdAAK'%2C'01p03000008FoaDAAS'%2C'01p03000008FpBDAA0'%2C'01p03000008FpAjAAK'%2C'01p03000008FoaJAAS'%2C'01p03000008FpBJAA0'%2C'01p03000008FpAlAAK'%2C'01p03000008FoaLAAS'%2C'01p03000008FpBLAA0'%2C'01p03000008FpAfAAK'%2C'01p03000008FoaFAAS'%2C'01p03000008FpBFAA0'%2C'01p03000008FpAhAAK'%2C'01p03000008FoaHAAS'%2C'01p03000008FpBHAA0'%2C'01p03000008FpArAAK'%2C'01p03000008FoaRAAS'%2C'01p03000008Fob3AAC'%2C'01p03000008FpBRAA0'%2C'01p03000008FpC3AAK'%2C'01p03000008FpAtAAK'%2C'01p03000008FoaTAAS'%2C'01p03000008Fob5AAC'%2C'01p03000008FpBTAA0'%2C'01p03000008FpC5AAK'%2C'01p03000008FpAnAAK'%2C'01p03000008FoaNAAS'%2C'01p03000008FpBNAA0'%2C'01p03000008FpApAAK'%2C'01p03000008FoaPAAS'%2C'01p03000008Fob1AAC'%2C'01p03000008FpBPAA0'%2C'01p03000008FpC1AAK'%2C'01p03000008FpAzAAK'%2C'01p03000008FoaZAAS'%2C'01p03000008FpBZAA0'%2C'01p03000008FpAvAAK'%2C'01p03000008FoaVAAS'%2C'01p03000008Fob7AAC'%2C'01p03000008FpBVAA0'%2C'01p03000008FpC7AAK'%2C'01p03000008FpAxAAK'%2C'01p03000008FoaXAAS'%2C'01p03000008Fob9AAC'%2C'01p03000008FpBXAA0'%2C'01p03000008FpC9AAK'%2C'01p03000008FpABAA0'%2C'01p03000008FpADAA0'%2C'01p03000008FpAJAA0'%2C'01p03000008FpALAA0'%2C'01p03000008FpAFAA0'%2C'01p03000008FpAHAA0'%2C'01p03000008Foa3AAC'%2C'01p03000008FpARAA0'%2C'01p03000008FpB3AAK'%2C'01p03000008Foa5AAC'%2C'01p03000008FpATAA0'%2C'01p03000008FpB5AAK'%2C'01p03000008FpANAA0'%2C'01p03000008Foa1AAC'%2C'01p03000008FpAPAA0'%2C'01p03000008FpB1AAK'%2C'01p03000008FpAZAA0'%2C'01p03000008Foa7AAC'%2C'01p03000008FpAVAA0'%2C'01p03000008FpB7AAK'%2C'01p03000008Foa9AAC'%2C'01p03000008FpAXAA0'%2C'01p03000008FpB9AAK'%2C'01p03000008FpA1AAK'%2C'01p03000008FpA3AAK'%2C'01p03000008FpA9AAK'%2C'01p03000008FpA5AAK'%2C'01p03000008FpA7AAK'%2C'01p03000008FoZxAAK'%2C'01p03000008FoZzAAK'%2C'01p03000008FoYzAAK'%2C'01p03000008FoZXAA0'%2C'01p03000008FoYvAAK'%2C'01p03000008FoZZAA0'%2C'01p03000008FoYxAAK'%2C'01p03000008FoZdAAK'%2C'01p03000008FoZfAAK'%2C'01p03000008FoZbAAK'%2C'01p03000008FoZlAAK'%2C'01p03000008FoZnAAK'%2C'01p03000008FoZhAAK'%2C'01p03000008FoZjAAK'%2C'01p03000008FoZtAAK'%2C'01p03000008FoZvAAK'%2C'01p03000008FoZpAAK'%2C'01p03000008FoZrAAK'%2C'01p03000008FoXzAAK'%2C'01p03000008Fp9zAAC'%2C'01p03000008FoYZAA0'%2C'01p03000008FoXvAAK'%2C'01p03000008Fp9vAAC'%2C'01p03000008FoYVAA0'%2C'01p03000008FoZ7AAK'%2C'01p03000008FoXxAAK'%2C'01p03000008Fp9xAAC'%2C'01p03000008FoYXAA0'%2C'01p03000008FoZ9AAK'%2C'01p03000008FoZDAA0'%2C'01p03000008FoYbAAK'%2C'01p03000008FoZFAA0'%2C'01p03000008FoYdAAK'%2C'01p03000008FoZBAA0'%2C'01p03000008FoZLAA0'%2C'01p03000008FoYjAAK'%2C'01p03000008FoZNAA0'%2C'01p03000008FoYlAAK'%2C'01p03000008FoZHAA0'%2C'01p03000008FoYfAAK'%2C'01p03000008FoZJAA0'%2C'01p03000008FoYhAAK'%2C'01p03000008FoZTAA0'%2C'01p03000008FoYrAAK'%2C'01p03000008FoZVAA0'%2C'01p03000008FoYtAAK'%2C'01p03000008FoZPAA0'%2C'01p03000008FoYnAAK'%2C'01p03000008FoZRAA0'%2C'01p03000008FoYpAAK'%2C'01p03000008FoXZAA0'%2C'01p03000008Fp9ZAAS'%2C'01p03000008FoWxAAK'%2C'01p03000008Fp8xAAC'%2C'01p03000008FoWzAAK'%2C'01p03000008Fp8zAAC'%2C'01p03000008FoXVAA0'%2C'01p03000008FoY7AAK'%2C'01p03000008Fp9VAAS'%2C'01p03000008FoWtAAK'%2C'01p03000008Fp8tAAC'%2C'01p03000008FoXXAA0'%2C'01p03000008FoY9AAK'%2C'01p03000008Fp9XAAS'%2C'01p03000008FoWvAAK'%2C'01p03000008Fp8vAAC'%2C'01p03000008FoXbAAK'%2C'01p03000008Fp9bAAC')"
    headers: {
      "content-type": "application/json",
      "user-agent": "sfdx toolbelt:"
    }
```

And sure enough, if you do a find on this page for `01p0300000` you see 500 results! 

If you are still having any trouble, please open a new Github Issue. Thanks!
