### ISSUE TITLE
Getting error  "ERROR running force:source:retrieve:  core_1.fs.fileExists is not a function" while retrieving

### ISSUE THREAD

**Issue by shalinimendu** [forcedotcom/cli#538]
Getting the error 'ERROR running force:source:retrieve:  core_1.fs.fileExists is not a function" when retrieving the source on package.xml from vscode after successsful authorization of the org. 
Getting this error on a windows NT machine only on a few projects.

Please help.
Version 1.47.2

**Comment by ddxxtony** [comment]
Hi @kunalmukhi  did you find a solution, I am having the same issue, but when I am trying to deploy a package.xml

**Comment by indrajitaus** [comment]
I am also facing similar issue...

**Comment by nramyasri-sf** [comment]
@kunalmukhi , is this still an issue? Do you see the same error when you execute the command directly through the CLI?

**Comment by shalinimendu** [comment]
I am experiencing this issue now.

Sent from Yahoo Mail on Android 
 
  On Fri, 7 Aug 2020 at 6:42 am, nramyasri-sf<notifications@github.com> wrote:   


@kunalmukhi , is this still an issue? Do you see the same error when you execute the command directly through the CLI?

**Comment by nramyasri-sf** [comment]
@shalinimendu , Do you see the same error when you execute the command directly through the CLI?

**Comment by shalinimendu** [comment]
Yes.

Sent from Yahoo Mail on Android 
 
  On Fri, 7 Aug 2020 at 1:03 pm, nramyasri-sf<notifications@github.com> wrote:   


@shalinimendu , Do you see the same error when you execute the command directly through the CLI?

**Comment by ddxxtony** [comment]
> @shalinimendu , Do you see the same error when you execute the command directly through the CLI?

I am also running the command directly through the CLI

**Comment by kunalmukhi** [comment]
Hi @ddxxtony , @shalinimendu , @nramyasri-sf , @indrajitaus ,

I have been able to fix this issue after a lots of debugging and grilling. 
Error will come with both CLI and retrieve command from right click @shalinimendu , @ddxxtony 
The problem that I found out is that one of the plugins installed with Salesforce CLI is creating an issue.
So we just need to run 2 commands and issue will get resolved.

Open cmd (command prompt) and run these 2 commands

1. sfdx plugins:uninstall salesforcedx
2. sfdx update

That's it and problem is solved.
Please let me know if you still face this problem.

**Comment by jpmonette** [comment]
Same issue over here:

```sh
> sfdx version
sfdx-cli/7.71.0-4193fb4acc darwin-x64 node-v12.18.3
```

Stacktrace:

```
TypeError: core_1.fs.fileExists is not a function
    at Workspace.walkDirectories (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/workspace.js:119:44)
    at Workspace.initializeStateFull (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/workspace.js:95:20)
    at Workspace.init (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/workspace.js:47:28)
    at Function.create (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/core/node_modules/@salesforce/kit/lib/creatable.js:31:9)
    at SourcePathStatusManager.init (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/sourcePathStatusManager.js:161:26)
    at Function.create (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at SourceWorkspaceAdapter.init (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:61:21)
    at Function.create (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at MdapiPushApi.init (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/sourcePushApi.js:29:20)
    at Function.create (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at SourceApiCommand.execute (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceApiCommand.js:48:15)
    at SourcePushCommand.execLegacyCommand (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:148:29)
    at SourcePushCommand.run (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/commands/force/source/push.js:29:16)
    at SourcePushCommand._run (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)
    at Config.runCommand (/Users/jpmonette/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/jpmonette/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/command/lib/main.js:22:9)
Outer stack:
    at Function.wrap (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at SourcePushCommand.catch (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)
    at SourcePushCommand._run (/Users/jpmonette/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)
    at Config.runCommand (/Users/jpmonette/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/jpmonette/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/command/lib/main.js:22:9)
    at Main._run (/Users/jpmonette/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/command/lib/command.js:43:20)
    at Object.run (/Users/jpmonette/.local/share/sfdx/client/7.71.0-4193fb4acc/dist/cli.js:32:20)
```

**Comment by jpmonette** [comment]
**UPDATE:**
Not ideal, but removing sfdx and reinstalling fixed the issue:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

**Comment by satishsfdc** [comment]
just run the command :  sfdx update, it resolved my issue.
