### ISSUE TITLE
Cannot read property 'fileName' of undefined  MAC

### ISSUE THREAD

**Issue by diegohna** [forcedotcom/cli#566]
### Summary

When i do a Retrieve in org in a project with manifest 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  MBP-de-Diego:Developer - CROSS diego.almeida$ sfdx force:source:retrieve --manifest --dev-debug manifest/package.xml
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name> 
    </types>
    <version>48.0</version>
</Package>`

### Expected result

Retrieve data from org

### Actual result

> RROR running force:source:retrieve:  Cannot read property 'fileName' of undefined 
*** Internal Diagnostic ***

TypeError: Cannot read property 'fileName' of undefined
    at Function.getMetadataFileNameFromBundleFileProperties (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:43:48)
    at Function.getPathFromBundleTypeFileProperties (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:35:43)
    at AuraDefinitionBundleMetadataType.getDefaultAggregateMetadataPath (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/metadataTypeImpl/bundleMetadataType.js:30:52)
    at SourceWorkspaceAdapter.processMdapiFileProperty (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:270:59)
    at /usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:165:22
    at Array.forEach (<anonymous>)
    at MdapiPullApi._syncDownSource (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:158:31)
    at SourceRetrieve.retrieveFromManifest (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceRetrieve.js:137:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SourceRetrieve.retrieve (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceRetrieve.js:65:27)
    at async SourceRetrieveCommand.execute (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceRetrieveCommand.js:31:16)
    at async SourceRetrieveCommand.execLegacyCommand (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:148:29)
    at async SourceRetrieveCommand.run (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/commands/force/source/retrieve.js:31:16)
    at async SourceRetrieveCommand._run (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)
    at async Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:22:9)
Outer stack:
    at Function.wrap (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at SourceRetrieveCommand.catch (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)
    at async SourceRetrieveCommand._run (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)
    at async Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/usr/local/lib/sfdx/dist/cli.js:32:20)
******

### Additional information

> what i have already done
`MBP-de-Diego:Developer - CROSS diego.almeida$ sfdx plugins:uninstall salesforcedxUninstalling salesforcedx...
MBP-de-Diego:Developer - CROSS diego.almeida$ sfdx plugins --core@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.1.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.2.1 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.6.1 (core)
├─ salesforcedx-templates 49.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.8 (core)
└─ salesforce-alm 49.6.0 (core)
sfdx-cli 7.70.1 (core)`

_Feel free to attach a screenshot_.
sfdx --version
sfdx-cli/7.70.1-3d8a6229fc darwin-x64 node-v12.18.3
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.1.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.2.1 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.6.1 (core)
├─ salesforce-alm 49.6.0 (core)
├─ custom-metadata 1.0.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforcedx-templates 49.2.0 (core)
sfdx-cli 7.70.1 (core)
**OS and version**:
![image](https://user-images.githubusercontent.com/15254999/90314434-20123880-deea-11ea-8de0-37cfea7323d4.png)

**Comment by diego-almeida-dhalmeida** [comment]
same problem

**Comment by Aleks15** [comment]
Same problem on linux machine.


```
//comand
sfdx force:source:pull --json

//error

{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'fileName' of undefined",
  "exitCode": 1,
  "commandName": "SourcePullCommand",
  "stack": "TypeError: Cannot read property 'fileName' of undefined
    at Function.getMetadataFileNameFromBundleFileProperties (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:41:48)
    at Function.getPathFromBundleTypeFileProperties (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/bundlePathHelper.js:35:43)
    at LightningComponentBundleMetadataType.getDefaultAggregateMetadataPath (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/metadataTypeImpl/bundleMetadataType.js:30:52)
    at SourceWorkspaceAdapter.processMdapiFileProperty (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:270:59)
    at /home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:165:22
    at Array.forEach (<anonymous>)
    at MdapiPullApi._syncDownSource (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:158:31)
    at MdapiPullApi._postRetrieve (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:134:48)
    at /home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:95:29
    Outer stack:
    at Function.wrap (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at SourcePullCommand.catch (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)
    at async SourcePullCommand._run (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)
    at async Config.runCommand (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/dist/cli.js:32:20)",
  "warnings": []
}

//addictional info:
at /home/alex/.local/share/sfdx/client/7.71.0-4193fb4acc/node_modules/salesforce-alm/dist/lib/source/sourcePullApi.js:95:29
(node:10669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:10669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10669) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)

sfdx-cli/7.71.0-4193fb4acc linux-x64 node-v12.18.3
```

**Comment by sf9y** [comment]
Same problem for me also if I include LightningComponentBundle type in package.xml.

**Comment by shetzel** [comment]
duplicate of #563 and #400
It will be fixed in the next CLI patch release.
