### ISSUE TITLE
ERROR running force:org:list:  Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by jayaprakash** [forcedotcom/cli#568]
### Summary

_sfdx force:org:list is failing_.

### Steps To Reproduce:

1.  Updated CLI to 7.70.1. with npm
2.  Execute the command 'sfdx force:org:list'

### Expected result

_Display the orgs authorised._

### Actual result

ERROR running force:org:list:  Cannot read property 'getInstance' of undefined

ERROR running force:org:list:  Cannot read property 'getInstance' of undefined 
*** Internal Diagnostic ***

TypeError: Cannot read property 'getInstance' of undefined
    at OrgListCommand.hooksFromLifecycleEvent (/Users/jmanchu/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:401:44)
    at OrgListCommand.init (/Users/jmanchu/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:248:20)
    at async OrgListCommand._run (/Users/jmanchu/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:92:13)
    at async Config.runCommand (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/dist/cli.js:32:20)
Outer stack:
    at Function.wrap (/Users/jmanchu/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at OrgListCommand.catch (/Users/jmanchu/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:259:67)
    at async OrgListCommand._run (/Users/jmanchu/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)
    at async Config.runCommand (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/Users/jmanchu/.nvm/versions/node/v14.5.0/lib/node_modules/sfdx-cli/dist/cli.js:32:20)
******

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version** sfdx-cli/7.70.1 darwin-x64 node-v14.5.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/analytics 0.22.0
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.6.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ custom-metadata 1.0.8
├─ salesforcedx-templates 49.2.0
└─ salesforce-alm 49.6.0
sfdx-cli 7.70.1 (core)

**OS and version**:
Mac OS: Catalina, 10.15.6

**Comment by jflowers45** [comment]
think this is a duplicate of https://github.com/forcedotcom/cli/issues/564

**Comment by jayaprakash** [comment]
Thanks for tagging it @jflowers45 
Executing **sfdx plugins:uninstall salesforcedx** resolved it. However salesforcedx plugin has been there for longtime in my installations. Surprised, how come an update of sfdx-cli caused above issue!

**Comment by shetzel** [comment]
duplicate
