### ISSUE TITLE
[Regression] force:package:version:create fails with JavaScript error

### ISSUE THREAD

**Issue by pozil** [forcedotcom/cli#594]
### Summary

I've been successfully running managed package creation in CI for the [Automation Components sample app](https://github.com/trailheadapps/automation-components) for the last couple of months.
Recently, I re-ran my packaging flow and `force:package:version:create` now fails with the following JavaScript error: `typesArr.filter is not a function`.

I am able to reproduce the issue locally as well.

### Steps To Reproduce:

1. Get the [Automation Components sample app](https://github.com/trailheadapps/automation-components).

1. Set up a namespace

1. Create an "AC - Data" managed package with a namespace

1. Create a package version:
    ```
    sfdx force:package:version:create -c -p "AC - Data" -x -w 20 -f config/project-scratch-def.json --json
    ```

### Expected result

Package version should be created.

### Actual result

I get this error consistently in CI and on my machine:
```
➜  automation-components git:(master) sfdx force:package:version:create -c -p "AC - Data" -x -w 20 -f config/project-scratch-def.json --json
{
  "status": 1,
  "name": "TypeError",
  "message": "typesArr.filter is not a function",
  "exitCode": 1,
  "commandName": "PackageVersionCreateCommand",
  "stack": "TypeError: typesArr.filter is not a function\n    at ProfileApi.filterAndGenerateProfilesForManifest (/Users/pozil/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/package/profileApi.js:145:29)\n    at /Users/pozil/.local/share/sfdx/node_modules/salesforce-alm/dist/lib/package/packageVersionCreateCommand.js:274:40\n    at tryCatcher (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/promise.js:673:18)\n    at /Users/pozil/.local/share/sfdx/node_modules/bluebird/js/release/nodeback.js:42:21\n    at /Users/pozil/.local/share/sfdx/node_modules/graceful-fs/graceful-fs.js:115:16\nOuter stack:\n    at Function.wrap (/Users/pozil/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at PackageVersionCreateCommand.catch (/Users/pozil/.local/share/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)\n    at async PackageVersionCreateCommand._run (/Users/pozil/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n    at async Config.runCommand (/Users/pozil/.local/share/sfdx/client/7.72.0-697e9faee2/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/pozil/.local/share/sfdx/client/7.72.0-697e9faee2/node_modules/@oclif/command/lib/main.js:22:9)\n    at async Main._run (/Users/pozil/.local/share/sfdx/client/7.72.0-697e9faee2/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/pozil/.local/share/sfdx/client/7.72.0-697e9faee2/dist/cli.js:32:20)",
  "warnings": []
}
```

### Additional information

**SFDX CLI Version**:
7.72.0-697e9faee2

**SFDX plugin Version**:
49.8.0

**OS and version**:
macOS on my machine and ubuntu-latest in a GitHub Action container.

**Comment by amphro** [comment]
Fixed in sfdx-cli 7.73.2 salesforcedx 49.9.2
