### ISSUE TITLE
EISDIR: illegal operation on a directory, read by right-clicking package.xml

### ISSUE THREAD

**Issue by k010c1232** [forcedotcom/cli#68]
### Summary

I just got this error, when I retrieve metadata to production org from VSCode(1.32.3) with salesforce cli ver 7.1.4.

### Steps To Reproduce:

1.  Triggered the retrieve by right-clicking package.xml

### Expected result

Retrieve meta data

### Actual result

EISDIR: illegal operation on a directory, read.

### Additional information

```
{"name":"sfdx","hostname":"winmyintoo.local","pid":29085,"level":50,"msg":"EISDIR: illegal operation on a directory, read.","time":"2019-04-01T00:47:58.715Z","v":0}
{"name":"sfdx","hostname":"winmyintoo.local","pid":29085,"level":50,"msg":"[ false,\n  '{\"message\":\"EISDIR: illegal operation on a directory, read\",\"status\":1,\"stack\":\"Error: EISDIR: illegal operation on a directory, read\\\\n    at Object.fs.readSync (fs.js:600:3)\\\\n    at Object.readSync (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/graceful-fs/polyfills.js:137:28)\\\\n    at tryReadSync (fs.js:440:20)\\\\n    at Object.fs.readFileSync (fs.js:481:19)\\\\n    at AggregateSourceElement.decomposeMetadata (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/aggregateSourceElement.js:471:39)\\\\n    at AggregateSourceElement.commitMetadata (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/aggregateSourceElement.js:312:87)\\\\n    at AggregateSourceElement.commit (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/aggregateSourceElement.js:279:18)\\\\n    at sourceElements.forEach.sourceElement (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/sourceWorkspaceAdapter.js:193:103)\\\\n    at Map.forEach (<anonymous>)\\\\n    at SourceWorkspaceAdapter.updateSource (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/sourceWorkspaceAdapter.js:192:20)\\\\n    at MdapiPullApi._syncDownSource (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/mdapiPullApi.js:137:20)\\\\n    at SourceRetrieve.<anonymous> (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/source/sourceRetrieve.js:111:56)\\\\n    at Generator.next (<anonymous>)\\\\n    at fulfilled (/Users/owin/.nodebrew/node/v10.0.0/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/source/sourceRetrieve.js:10:58)\",\"name\":\"Error\",\"warnings\":[]}' ]","time":"2019-04-01T00:47:58.717Z","v":0}

```

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.1.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.8.2 (core)
├─ force-language-services 45.9.0 (core)
└─ salesforce-alm 45.11.0 (core)

```
**OS and version**:
macOS High Sierra ver: 10.13.6

**Comment by clairebianchi** [comment]
@k010c1232, can you check the permissions? are you using SUDO? I think your user that is logged into CLI does not have permissions. See: https://npm.community/t/global-installs-sudo-npm-i-g-fail-on-mac-after-6-5-upgrade-works-fine-after-6-4-1-downgrade/4082
