### ISSUE TITLE
SFDX_IMPROVED_CODE_COVERAGE not working for apex report

### ISSUE THREAD

**Issue by davidncruz** [forcedotcom/cli#698]
### Summary

Setting env SFDX_IMPROVED_CODE_COVERAGE=true will result in a connection error

### Steps To Reproduce:

run these commands

SFDX_IMPROVED_CODE_COVERAGE=true sfdx force:apex:test:report -i $JOB_ID

### Expected result

Report to be retrieved and printed

### Actual result

```
{
  "status": 1,
  "name": "TestResultRetrievalFailed",
  "message": "read ECONNRESET",
  "exitCode": 1,
  "commandName": "ApexTestReportCommand",
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)\nOuter stack:\n    at Function.wrap (/usr/local/lib/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at ApexTestReportCommand.catch (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)\n    at async ApexTestReportCommand._run (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n    at async Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/sfdx/dist/cli.js:32:20)",
  "warnings": []
}
```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.74.1 win32-x64 node-v10.19.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ apex 0.0.9 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 49.9.1 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)

**OS and version**:
Local ran with git bash or cmd
![image](https://user-images.githubusercontent.com/33698728/96994068-1299b000-1524-11eb-8cd1-8d6b7c59c8c4.png)

Githib Actions
![image](https://user-images.githubusercontent.com/33698728/96994179-3bba4080-1524-11eb-84e2-f9930960265e.png)

**Comment by yippie** [comment]
There is a similar issue with getting response size issues. it seems that the new code coverage is inefficient and just dies if you have more than a couple dozen unit tests. So it is worthless unless you have a tiny project

**Comment by mshanemc** [comment]
Not reproducible with dreamhouse.  This example has 1 intentionally failing test, but I also tried it with all passing tests. 

```bash
dreamhouse-lwc git:(main) ✗ sf apex run test --resultformat junit --codecoverage --testlevel RunLocalTests --wait 0
Warning: The "--codecoverage" flag has been deprecated. Use "--code-coverage | -c" instead.
Warning: The "--testlevel" flag has been deprecated. Use "--test-level | -l" instead.
Warning: The "--resultformat" flag has been deprecated. Use "--result-format | -r" instead.
Run "sf apex get test -i 707DR00002EuPvM -o test-8uyifrxw8gab@example.com" to retrieve test results
Run with --synchronous or increase --wait timeout to wait for results.
➜  dreamhouse-lwc git:(main) ✗ SFDX_IMPROVED_CODE_COVERAGE=true sf apex get test -i 707DR00002EuPvM -o test-8uyifrxw8gab@example.com
(node:44759) Warning: Deprecated environment variable: SFDX_IMPROVED_CODE_COVERAGE. Please use SF_IMPROVED_CODE_COVERAGE instead.
(Use `node --trace-warnings ...` to show where the warning was created)
=== Test Summary
NAME                 VALUE                        
───────────────────  ─────────────────────────────
Outcome              Failed                       
Tests Ran            11                           
Pass Rate            91%                          
Fail Rate            9%                           
Skip Rate            0%                           
Test Run Id          707DR00002EuPvM              
Test Execution Time  3097 ms                      
Org Id               00DDR000001Nyx42AC           
Username             test-8uyifrxw8gab@example.com


=== Test Results
TEST NAME                                                 OUTCOME  MESSAGE                                                                                 RUNTIME (MS)
────────────────────────────────────────────────────────  ───────  ──────────────────────────────────────────────────────────────────────────────────────  ────────────
FileUtilitiesTest.createFileFailsWhenIncorrectBase64Data  Pass                                                                                             87          
FileUtilitiesTest.createFileFailsWhenIncorrectFilename    Pass                                                                                             25          
FileUtilitiesTest.createFileFailsWhenIncorrectRecordId    Pass                                                                                             245         
FileUtilitiesTest.createFileSucceedsWhenCorrectInput      Fail     System.AssertException: Assertion Failed: Nullable object asserted with non null value  
                                                                   External entry point                                                                    
                                                                   Class.FileUtilitiesTest.createFileSucceedsWhenCorrectInput: line 21, column 1                       
TestPropertyController.testGetPagedPropertyList           Pass                                                                                             848         
TestPropertyController.testGetPicturesNoResults           Pass                                                                                             36          
TestPropertyController.testGetPicturesWithResults         Pass                                                                                             1173        
TestSampleDataController.importSampleData                 Pass                                                                                             278         
GeocodingServiceTest.blankAddress                         Pass                                                                                             25          
GeocodingServiceTest.errorResponse                        Pass                                                                                             6           
GeocodingServiceTest.successResponse                      Pass                                                                                             120     
```


If you can still reproduce it, please open a new issue with a repro with the number of tests it takes to cause the error.
