### ISSUE TITLE
sfdx force:lightning:component:create -n myFirstWebComponent -d force-app/main/default/lwc --type lwc // not working 

### ISSUE THREAD

**Issue by jaya-karthik-Karnati** [forcedotcom/cli#773]
Hi all,

In salesforce trailhead they asked to run the following command in the terminal

sfdx force:lightning:component:create -n myFirstWebComponent -d force-app/main/default/lwc --type lwc

after running the command i am getting the below error . 

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Salesforce CLI\client\node_modules\@salesforce\templates\lib\templates\lightningcomponent\lwc\DefaultLightningLWC.js
    at EditionInterface.exports.copy (C:\Program Files (x86)\Salesforce CLI\client\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Salesforce CLI\client\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at LightningComponentGenerator.writing (C:\Program Files (x86)\Salesforce CLI\client\node_modules\@salesforce\templates\lib\generators\lightningComponentGenerator.js:62:21)
    at Object.<anonymous> (C:\Program Files (x86)\Salesforce CLI\client\node_modules\yeoman-generator\lib\index.js:427:27)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:26:19
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\yeoman-generator\lib\index.js:428:13
    at processImmediate (internal/timers.js:456:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Salesforce CLI\client\node_modules\@salesforce\templates\lib\templates\lightningcomponent\lwc\DefaultLightningLWC.js
    at EditionInterface.exports.copy (C:\Program Files (x86)\Salesforce CLI\client\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Salesforce CLI\client\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at LightningComponentGenerator.writing (C:\Program Files (x86)\Salesforce CLI\client\node_modules\@salesforce\templates\lib\generators\lightningComponentGenerator.js:62:21)
    at Object.<anonymous> (C:\Program Files (x86)\Salesforce CLI\client\node_modules\yeoman-generator\lib\index.js:427:27)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:26:19
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\yeoman-generator\lib\index.js:428:13
    at processImmediate (internal/timers.js:456:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files (x86)\Salesforce CLI\client\node_modules\@salesforce\templates\lib\templates\lightningcomponent\lwc\DefaultLightningLWC.js
    at EditionInterface.exports.copy (C:\Program Files (x86)\Salesforce CLI\client\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\Salesforce CLI\client\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at LightningComponentGenerator.writing (C:\Program Files (x86)\Salesforce CLI\client\node_modules\@salesforce\templates\lib\generators\lightningComponentGenerator.js:62:21)
    at Object.<anonymous> (C:\Program Files (x86)\Salesforce CLI\client\node_modules\yeoman-generator\lib\index.js:427:27)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\run-async\index.js:26:19
    at C:\Program Files (x86)\Salesforce CLI\client\node_modules\yeoman-generator\lib\index.js:428:13
    at processImmediate (internal/timers.js:456:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='

Please suggest what to do .

Thanks in advance :)

**Comment by shetzel** [comment]
That exact command works for us on both windows and mac.  What are your plugin versions?  If they aren't the core versions you may want to udpate.  `sfdx plugins --core` to list them.

**Comment by jaya-karthik-Karnati** [comment]
Hi shetzel,

Thanks for the reply , these are the plugins in my machine.

![image](https://user-images.githubusercontent.com/76443232/102808297-23f91e80-43e6-11eb-8bdb-bb1fb0ad8dbe.png)

**Comment by shetzel** [comment]
Hmmm..something might be wrong with the generator for that template.  Needs investigation.

**Comment by AnanyaJha** [comment]
Hi @jaya-karthik-Karnati thanks for reporting this! Like Steve said, we were not able to reproduce this issue on Windows or Mac with a fresh install of the CLI and the salesorcedx-templates plugin. Can you try installing the plugin separately by running the command `sfdx plugins:install salesforcedx-templates`?

**Comment by jaya-karthik-Karnati** [comment]
Hi @AnanyaJha and @shetzel ,

The  `sfdx plugins:install salesforcedx-templates ` has worked.

Thank you so much both for your valuable input :)
