### ISSUE TITLE
Why is sfdx looking in my user directory for the project config file?

### ISSUE THREAD

**Issue by robert-strunk** [forcedotcom/cli#774]
When I do a  
    `sfdx force:source:retrieve --manifest assets/package.xml --targetusername DevHub --wait 10 --loglevel TRACE`   
 
I am getting the error 
    `ERROR running force:source:retrieve:  Cannot convert undefined or null to object`. 

When I review the log I am seeing something that I believe is a bit odd but I am not entirely sure. Why is it looking for the project file in my user directory? I'm not sure how to troubleshoot this. I'm running the command from within my project root which is not in my user directory. 

`sfdx --version` => `sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3`

**log result**
```
{"name":"sfdx","hostname":"Rstru147310","pid":2552,"log":"SfdxProjectJson","level":40,"msg":"The config file: C:\\Users\\Rob\\.sfdx\\sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2020-12-21T15:25:20.085Z","v":0}
{"name":"sfdx","hostname":"Rstru147310","pid":2552,"log":"SfdxProjectJson","level":40,"msg":"The config file: C:\\Users\\Rob\\.sfdx\\sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2020-12-21T15:25:20.089Z","v":0}
{"name":"sfdx","hostname":"Rstru147310","pid":2552,"log":"SourceRetrieveCommand","level":50,"msg":"[\n  '\\u001b[1mERROR running force:source:retrieve: \\u001b[22m',\n  '\\u001b[31mCannot convert undefined or null to object\\u001b[39m'\n]","time":"2020-12-21T15:25:20.096Z","v":0}
```

**Comment by shetzel** [comment]
Because there is the notion of local config values and global config values.  Local config values take precedence over global config values.  Local config is defined within a project.  Global config is defined within the user dir and applies for all projects unless overridden in another scope.  The log output about the global config file validation is just a warning and isn't logged in an upcoming release.

To get more info on the actual error, run the command appending `--dev-debug`.

I don't know what version of the plugins you have, but you might want to update to the latest if you are not on the core versions.  `sfdx plugins --core`

**Comment by robert-strunk** [comment]
@shetzel Thanks for replying. I get the concept of global and local wrt settings, what puzzles me is that the cli is demonstrating that type of behavior when looking for a sfdx-project.json file. I thought the local > workspace > global hierarchy would only apply to settings. Unless there is a concept of a global project which I am not aware of (entirely possible, I'm new to dx) I do not know why it would be looking for a project file in the global space. 

Thanks for mentioning the --dev-debug switch, reviewing that dump now.

**Comment by robert-strunk** [comment]
After using the --dev-debug switch on the same command it now generates the following log entries. 

```
{"name":"sfdx","hostname":"Rstru147310","pid":1672,"log":"SfdxProjectJson","level":40,"msg":"The config file: C:\\Users\\Rob\\.sfdx\\sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2020-12-21T19:04:28.591Z","v":0}
{"name":"sfdx","hostname":"Rstru147310","pid":1672,"log":"SfdxProjectJson","level":40,"msg":"The config file: C:\\Users\\Rob\\.sfdx\\sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2020-12-21T19:04:28.659Z","v":0}
{"name":"sfdx","hostname":"Rstru147310","pid":1672,"log":"SourceRetrieveCommand","level":50,"msg":"[\n  'ERROR running force:source:retrieve: ',\n  'Cannot convert undefined or null to object',\n  '\\n' +\n    '*** Internal Diagnostic ***\\n' +\n    '\\n' +\n    'TypeError: Cannot convert undefined or null to object\\n' +\n    '    at C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\lib\\\\mdapi\\\\mdapiRetrieveApi.js:131:13\\n' +\n    '    at async SourceElementsResolver.getSourceElementsFromManifest (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\lib\\\\source\\\\sourceElementsResolver.js:30:31)\\n' +\n    '    at async SourceRetrieve.retrieveFromManifest (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\lib\\\\source\\\\sourceRetrieve.js:97:43)\\n' +\n    '    at async SourceRetrieve.retrieve (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\lib\\\\source\\\\sourceRetrieve.js:57:27)\\n' +\n    '    at async SourceRetrieveCommand.execute (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\lib\\\\source\\\\sourceRetrieveCommand.js:32:16)\\n' +\n    '    at async SourceRetrieveCommand.execLegacyCommand (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\ToolbeltCommand.js:149:29)\\n' +\n    '    at async SourceRetrieveCommand.run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\commands\\\\force\\\\source\\\\retrieve.js:32:16)\\n' +\n    '    at async SourceRetrieveCommand._run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@salesforce\\\\command\\\\lib\\\\sfdxCommand.js:93:40)\\n' +\n    '    at async Config.runCommand (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@oclif\\\\config\\\\lib\\\\config.js:173:24)\\n' +\n    '    at async Main.run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@oclif\\\\command\\\\lib\\\\main.js:27:9)\\n' +\n    '    at async Main._run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@oclif\\\\command\\\\lib\\\\command.js:43:20)\\n' +\n    '    at async Object.run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\dist\\\\cli.js:32:20)\\n' +\n    'Outer stack:\\n' +\n    '    at Function.wrap (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\node_modules\\\\@salesforce\\\\core\\\\lib\\\\sfdxError.js:171:27)\\n' +\n    '    at SourceRetrieveCommand.catch (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\salesforce-alm\\\\dist\\\\ToolbeltCommand.js:248:46)\\n' +\n    '    at async SourceRetrieveCommand._run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@salesforce\\\\command\\\\lib\\\\sfdxCommand.js:97:13)\\n' +\n    '    at async Config.runCommand (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@oclif\\\\config\\\\lib\\\\config.js:173:24)\\n' +\n    '    at async Main.run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@oclif\\\\command\\\\lib\\\\main.js:27:9)\\n' +\n    '    at async Main._run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\node_modules\\\\@oclif\\\\command\\\\lib\\\\command.js:43:20)\\n' +\n    '    at async Object.run (C:\\\\Users\\\\Rob\\\\AppData\\\\Local\\\\sfdx\\\\client\\\\7.82.0-3d0c527ac6\\\\dist\\\\cli.js:32:20)\\n' +\n    '******\\n'\n]","time":"2020-12-21T19:04:28.763Z","v":0}
```

**Comment by robert-strunk** [comment]
Turns out there was something wrong with my package xml file located at "./assets/package.xml". It was a copy paste from trailhead so not sure whats going on there. I created a new package xml from scratch and put all the same types in there and the retrieve call works fine. I had checked for this issue early on and didn't see any special characters in the package file but perhaps I missed some.

**Comment by shetzel** [comment]
@robert-strunk - Glad you got it working.  `Cannot convert undefined or null to object` is a CLI plugin bug, even if the package.xml is invalid.  If you don't mind, can you let me know how that file was invalid so we can reproduce and fix the code to display a better and more helpful error message?

It's possible to have a global sfdx-project.json that applies to all your projects, then override certain things per project.  I doubt it's a common usecase but it's possible.

**Comment by robert-strunk** [comment]
Sure thing. I suppose I am not 100% sure it is the package file but it sure looks that way. In this repo, the package.xml file that is in the assets directory is the offending one. [trailhead project repo - feature-chan-map branch](https://github.com/robert-strunk/sfdx-project/tree/feature-chan-map)
