### ISSUE TITLE
"Cannot read property 'success' of undefined" error when pushing source to org

### ISSUE THREAD

**Issue by copmill** [forcedotcom/cli#793]
### Summary

When attempting to push source code to an org with the '-f' force flag, I receive the error message "Cannot read property 'success' of undefined" and the code is not pushed to the org.

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-push-error](https://github.com/copmill/sfdx-push-error)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Run dev-start.sh from the repo above. (This creates a scratch org and pushes the code.)
1.  Delete the file `force-app/main/default/objects/Test_SObject__c/Test_SObject__c.object-meta.xml`.
1. Run `sfdx force:source:push -f` (The -f is important. It works fine without.)

### Expected result

The push should fail with a message which explains that the `Test_SObject__c.object-meta.xml` file is missing.

### Actual result

The push fails with a generic, unhelpful, message: ERROR running force:source:push:  Cannot read property 'success' of undefined

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.75.0 darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
apexflow-sfdx 1.3.0 (link) /Users/alexmiller/.vscode/extensions/financialforce.apexflow-1.4.0-SNAPSHOT/sfdx
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.13.0 (core)
├─ salesforce-alm 49.12.1 (core)
├─ templates 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.0 (core)
sfdx-cli 7.75.0 (core)

**OS and version**:
MacOS Catalina version: 10.15.7

**Comment by copmill** [comment]
Stacktrace obtained by adding `--json` flag to the push command:
```
{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'success' of undefined",
  "exitCode": 1,
  "commandName": "SourcePushCommand",
  "stack": "TypeError: Cannot read property 'success' of undefined\n   
 at MdapiPushApi.processResults (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/dist/lib/source/sourcePushApi.js:151:20)\n    
at MdapiPushApi.deployPackage (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/dist/lib/source/sourcePushApi.js:46:35)\n    
at async MdapiPushApi.doDeploy (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/dist/lib/source/sourcePushApi.js:74:38)\n    
at async SourcePushCommand.execLegacyCommand (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/dist/ToolbeltCommand.js:149:29)\n    
at async SourcePushCommand.run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/dist/commands/force/source/push.js:30:16)\n    
at async SourcePushCommand._run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)\n    
at async Config.runCommand (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@oclif/config/lib/config.js:173:24)\n    
at async Main.run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@oclif/command/lib/main.js:27:9)\n    
at async Main._run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@oclif/command/lib/command.js:43:20)\n    
at async Object.run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/sfdx-cli/dist/cli.js:32:20)\nOuter stack:\n    
at Function.wrap (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    
at SourcePushCommand.catch (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/salesforce-alm/dist/ToolbeltCommand.js:248:46)\n    
at async SourcePushCommand._run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n   
at async Config.runCommand (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@oclif/config/lib/config.js:173:24)\n    
at async Main.run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@oclif/command/lib/main.js:27:9)\n    
at async Main._run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/@oclif/command/lib/command.js:43:20)\n    
at async Object.run (/Users/alexmiller/.nvm/versions/node/v12.18.3/lib/node_modules/@ffdev/sfdx-wrapper/node_modules/sfdx-cli/dist/cli.js:32:20)",
  "warnings": []
}
```

**Comment by shetzel** [comment]
@copmill - please update the CLI to see if that fixes it.  e.g., `sfdx update`. If you no longer see the error with the latest CLI and plugins, please close.

**Comment by copmill** [comment]
@shetzel - updated the CLI to version `sfdx-cli/7.82.1-0 darwin-x64 node-v12.18.3` (assume this is the latest?). The issue is now resolved.  Apologies for not checking with the latest version. Closing.
