### ISSUE TITLE
INVALID_HEADER_TYPE error when force:org:open --targetusername in CI

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#814]
### Summary

Getting this error when using my Github action:

```
2021-01-21T23:24:16.1309590Z {
2021-01-21T23:24:16.1310214Z   "status": 1,
2021-01-21T23:24:16.1310795Z   "name": "INVALID_AUTH_HEADER",
2021-01-21T23:24:16.1311417Z   "message": "INVALID_HEADER_TYPE",
2021-01-21T23:24:16.1311952Z   "exitCode": 1,
2021-01-21T23:24:16.1312599Z   "commandName": "OrgOpenCommand",
2021-01-21T23:24:16.1318645Z   "stack": "INVALID_AUTH_HEADER: INVALID_HEADER_TYPE\n    at HttpApi.getError (/usr/local/lib/sfdx/node_modules/jsforce/lib/http-api.js:250:13)\n    at /usr/local/lib/sfdx/node_modules/jsforce/lib/http-api.js:95:22\n    at tryCallOne (/usr/local/lib/sfdx/node_modules/promise/lib/core.js:37:12)\n    at /usr/local/lib/sfdx/node_modules/promise/lib/core.js:123:15\n    at flush (/usr/local/lib/sfdx/node_modules/asap/raw.js:50:29)\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)\nOuter stack:\n    at Function.wrap (/usr/local/lib/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at OrgOpenCommand.catch (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:259:67)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async OrgOpenCommand._run (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n    at async Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/sfdx/dist/cli.js:32:20)",
2021-01-21T23:24:16.1321716Z   "warnings": []
2021-01-21T23:24:16.1322208Z }
```

Strangely only happens in CI. Works fine on my mac...

The user is definitely there fwiw:

```
2021-01-21T23:24:14.7297790Z === Orgs
2021-01-21T23:24:14.7325708Z   ALIAS   USERNAME               ORG ID              CONNECTED STATUS
2021-01-21T23:24:14.7327500Z   ──────  ─────────────────────  ──────────────────  ────────────────
2021-01-21T23:24:14.7331337Z   HubOrg  ci@devhub.myns.com  00Dd0000000fbMlEAI  Connected
2021-01-21T23:24:14.7331975Z 
2021-01-21T23:24:14.7336057Z      ALIAS   USERNAME                                     ORG ID              EXPIRATION DATE
2021-01-21T23:24:14.7337543Z ───  ──────  ───────────────────────────────────────────  ──────────────────  ───────────────
2021-01-21T23:24:14.7338961Z (U)  ciorg   test-hh70dktloj0m@example.com                00D54000000GvJ9EAK  2021-01-22
2021-01-21T23:24:14.7340416Z      qauser  1611271444586_test-hh70dktloj0m@example.com  00D54000000GvJ9EAK  2021-01-22
```

### Steps To Reproduce:

Working on a repo to reproduce this cleanly...

### Expected result

Prints login url

### Actual result

Throws error

### Additional information

Namespaced org.

`sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3`
Ubuntu 18.04.5

**Comment by sjurgis** [comment]
Only seems to be happening in namespaced devhub, not in regular developer edition hub.

**Comment by sjurgis** [comment]
Ran out of scratch orgs for the day to reproduce

**Comment by sjurgis** [comment]
Using alias isn't the issue, opening by username fails in same way

```
userinit=$(sfdx force:user:create -f ci/modules/services/qa-user-template.json --json)
username=$(echo $userinit | jq -r '.result.fields.username')
sfdx force:org:list
sfdx force:org:open -u $username -r --loglevel=TRACE --json
```

**Comment by amphro** [comment]
Does adding `--dev-debug` give you any additional information around the request being made?

Out of curiosity, why are you trying to open the org in CI? Can you share a github action config that would reproduce off the fork of the dreamhouse app?

**Comment by sjurgis** [comment]
Hi @amphro, thanks for the flag. Nothing obvious so far.
To makes things even weirder I can only reproduce it in our internal repo, but not in public one 🥴 
I've used credentials from public one (totally different NS, dev org AND also removed all files from internal repo) - command fails in our internal repo. Log attached below:
[reproduced.txt](https://github.com/forcedotcom/cli/files/5859874/reproduced.txt)

Here's a log from identical action, from [this repo](https://github.com/sjurgis/sfdx-issue-repro) - command succeeds.
[not-repro.txt](https://github.com/forcedotcom/cli/files/5859884/not-repro.txt)

I don't wanna steal my repo credentials just yet to try it out in a separate repo. At this point I'm quite confused what could be causing this. My guess env flag or Github runner thyself 😳 

>  why are you trying to open the org in CI?

I'm testing permissions using jest+playwright (via [sfdx-node](https://www.npmjs.com/package/sfdx-node) ... IMO you guys need first-party support for node interface but I digress). I use nodejs to create user, assign permset and all sort of other things. Here's my [workhorse wrapper](https://gist.github.com/sjurgis/f10f3f22db83c36ec28eef75b1c2f20b) I extensively use in jest to drive my org.

**Comment by sjurgis** [comment]
One thing that stands out is that failing request has two slashes after domain

> 2021-01-23T07:15:41.5956366Z 2021-01-23T07:15:41.595Z sfdx:connection DEBUG request: {"url":"https://efficiency-ability-90682-dev-ed.cs43.my.salesforce.com//services/data/v50.0","method":"GET","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}}

vs

> 2021-01-23T07:58:36.1805001Z 2021-01-23T07:58:36.180Z sfdx:connection DEBUG request: {"url":"https://agility-force-32812-dev-ed.cs92.my.salesforce.com/services/data/v50.0","method":"GET","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}}


Also (more interesting)

Failing: 
> 2021-01-23T07:15:41.3013194Z 2021-01-23T07:15:41.300Z sfdx:AuthInfo INFO Returning fields for a connection using access token.

Working:
> 2021-01-23T07:58:36.0045228Z 2021-01-23T07:58:36.004Z sfdx:AuthInfo INFO Returning fields for a connection using JWT config.

**Comment by sjurgis** [comment]
@amphro any ideas why one would be using JWT another using access token and if that's the root cause?

I'm quite limited to what I can do with my devhub/repo.

**Comment by WillieRuemmele** [comment]
Hi @sjurgiscould you try running this with the latest-rc build of the cli, you can install it with `npm install sfdx-cli@latest-rc --global` and uninstall it with `npm uninstall sfdx-cli@latest-rc --global`
