### ISSUE TITLE
sourcePathInfo.getPendingPathInfo is not a function issue in source pull/push deploy/retrieve

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#856]
### Summary

I have updated to the latest sfdx-cli and salesforcedx and I cannot use the source commands anymore. I am using sfdx installed using npm instead of the stand-alone one.

` sfdx plugins --core`
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-update 1.3.10
└─ @oclif/plugin-help 2.2.3
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-scanner 2.6.0
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.7 (core)
config 1.2.4 (core)
generator 1.1.5 (core)
salesforcedx 50.16.1
├─ user 1.1.0
├─ salesforce-alm 50.16.1
├─ limits 1.0.3
├─ schema 1.0.3
├─ apex 0.1.4
├─ custom-metadata 1.0.11
├─ templates 50.4.0
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7
sfdmu 3.9.4
sfdx-cli 7.86.3 (core)
sfdx-git-delta 4.2.0
sfpowerkit 2.6.5
telemetry 1.0.1 (core)
texei-sfdx-plugin 1.9.3

### Additional information

Tried re-installing the earlier versions of the cli and the dx plugins but wouldn't work.

Error block when runusing --deb-debug
```
sfdx:SchemaValidator DEBUG Schema loaded for C:\Users\sfuser\AppData\Local\sfdx\node_modules\@salesforce\schemas\sfdx-project.schema.json +21ms
ERROR running force:source:pull:  sourcePathInfo.getPendingPathInfo is not a function 
*** Internal Diagnostic ***

TypeError: sourcePathInfo.getPendingPathInfo is not a function
    at SourcePathStatusManager.getSourcePathInfos (C:\Users\sfuser\AppData\Local\sfdx\node_modules\salesforcedx\node_modules\salesforce-alm\dist\lib\source\sourcePathStatusManager.js:209:64)
    at SourceWorkspaceAdapter.init (C:\Users\sfuser\AppData\Local\sfdx\node_modules\salesforcedx\node_modules\salesforce-alm\dist\lib\source\sourceWorkspaceAdapter.js:76:47)
    at async Function.create (C:\Users\sfuser\AppData\Local\sfdx\node_modules\@salesforce\kit\lib\creatable.js:31:9)
    at async MdapiPullApi.init (C:\Users\sfuser\AppData\Local\sfdx\node_modules\salesforcedx\node_modules\salesforce-alm\dist\lib\source\sourcePullApi.js:55:24)
    at async Function.create (C:\Users\sfuser\AppData\Local\sfdx\node_modules\@salesforce\kit\lib\creatable.js:31:9)
    at async SourcePullCommand.execLegacyCommand (C:\Users\sfuser\AppData\Local\sfdx\node_modules\salesforcedx\node_modules\salesforce-alm\dist\ToolbeltCommand.js:149:29)
    at async SourcePullCommand._run (C:\Users\sfuser\AppData\Local\sfdx\node_modules\@salesforce\command\lib\sfdxCommand.js:81:40)
    at async Config.runCommand (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\dist\cli.js:117:20)
Outer stack:
    at Function.wrap (C:\Users\sfuser\AppData\Local\sfdx\node_modules\@salesforce\core\lib\sfdxError.js:171:27)
    at SourcePullCommand.catch (C:\Users\sfuser\AppData\Local\sfdx\node_modules\salesforcedx\node_modules\salesforce-alm\dist\ToolbeltCommand.js:248:46)
    at async SourcePullCommand._run (C:\Users\sfuser\AppData\Local\sfdx\node_modules\@salesforce\command\lib\sfdxCommand.js:85:13)
    at async Config.runCommand (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\Users\sfuser\AppData\Roaming\npm\node_modules\sfdx-cli\dist\cli.js:117:20)
******

  sfdx:SourcePullCommand ERROR [
  sfdx:SourcePullCommand   '\x1B[1mERROR running force:source:pull: \x1B[22m',
  sfdx:SourcePullCommand   '\x1B[31msourcePathInfo.getPendingPathInfo is not a function\x1B[39m',
  sfdx:SourcePullCommand   '\x1B[31m\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m*** Internal Diagnostic ***\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31mTypeError: sourcePathInfo.getPendingPathInfo is not a function\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at SourcePathStatusManager.getSourcePathInfos (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\salesforcedx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePathStatusManager.js:209:64)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at SourceWorkspaceAdapter.init (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\salesforcedx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:76:47)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Function.create (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\kit\\lib\\creatable.js:31:9)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async MdapiPullApi.init (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\salesforcedx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:55:24)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Function.create (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\kit\\lib\\creatable.js:31:9)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async SourcePullCommand.execLegacyCommand (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\salesforcedx\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:149:29)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async SourcePullCommand._run (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Config.runCommand (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Main.run (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Main._run (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Object.run (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js:117:20)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31mOuter stack:\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at Function.wrap (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at SourcePullCommand.catch (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\salesforcedx\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:248:46)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async SourcePullCommand._run (C:\\Users\\sfuser\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Config.runCommand (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Main.run (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Main._run (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m    at async Object.run (C:\\Users\\sfuser\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js:117:20)\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m******\x1B[39m\n' +
  sfdx:SourcePullCommand     '\x1B[31m\x1B[39m'
  sfdx:SourcePullCommand ] +3s
```

**Comment by mshanemc** [comment]
the code that used SourcePathInfo isn't in use in the current version of plugin-source, so I'm sure that error doesn't exist anymore.  🤪 

If you've still got deploy problems on newer code, please open an issue.

sorry this was left open so long
