### ISSUE TITLE
Org auth status unknown after sfdx update to 7.89.2

### ISSUE THREAD

**Issue by JuliWaver** [forcedotcom/cli#887]
After updating my sfdx with command 'sfdx update' to version 7.89.2 I am not longer able to use my autheticated orgs.
Status is unknown instead of connected and I am not able to perform any commands with my alias or username.

I have already tried several times to logout and login again, but nothing has changed.

With an older version 7.81.0 it is still working and the same alias are shown as connected.

**Comment by peternhale** [comment]
@JuliWaver are you seeing any errors when referencing an alias or username in a command?

**Comment by dcstuff** [comment]
For me, a force:source:push fails until I login. Logging is not an issue. But if I don't, I get `Error: INVALID_SESSION_ID: Session expired or invalid` on the push.

**Comment by JuliWaver** [comment]
@peternhale Unfortunately I get erros if I try to upload a screenshot.

Following error is visible after I try to use e.g. a deploy command with an alias:
**ERROR running force:source:deploy: The org cannot be found

Try this:
Verfiy that the org still exists
If your org is newly created, wait a minute and run your comman again
If you deployed or updated the org's My Domain, logout from the CLI and autheticate again
If you are running in a CI environment with DNS that blocks external IPs, try setting SFDX_DISABLE_DNS_CHECK=true**

I have checked all of those proposals, the only one which is really relevant is the last one regarding SFDX_DISABLE_DNS_CHECK=true, but if I set this one I get a follow up error about Unexbeceted token JSON at position 0. 
Almost the same than named here: https://github.com/forcedotcom/cli/issues/884

**Comment by peternhale** [comment]
@JuliWaver Would you run the failing example again with 7.89.2 with the `--dev-debug` flag.

Also, which platform are you using?

**Comment by JuliWaver** [comment]
@peternhale 
Following Error message is shown after setting variavble SFDX_DISABLE_DNS_CHECK=true and deploy/validate command:

*** Deploying with REST ***
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.89.2-d1d2614d02\node_modules\salesforce-alm\dist\lib\core\force.js:583:25)
    at self.callback (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.89.2-d1d2614d02\node_modules\request\request.js:185:22)
    at Request.emit (events.js:327:22)
    at Request.onRequestError (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.89.2-d1d2614d02\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.onError (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.89.2-d1d2614d02\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)


I am using Windows 10 Enterprise Version 1909 and sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4.
What information do you need from the debug log? Uploading attachments is still not working for me, sorry.

**Comment by peternhale** [comment]
@JuliWaver,

Thank you.

Which command are you running that get the above error?

Can you run it again w/o SFDX_DISABLE_DNS_CHECK set.

Can you share the domain name of the org that is the target of the command being run?

**Comment by JuliWaver** [comment]
@peternhale  The command was: sfdx force:source:deploy --verbose --targetusername cis -p force-app -c

If SFDX_DISABLE_DNS_CHECK is not set in my variables I recieve following error message again:

_ERROR running force:source:deploy:  The org cannot be found

Try this:
Verify that the org still exists
If your org is newly created, wait a minute and run your command again
If you deployed or updated the org's My Domain, logout from the CLI and authenticate again
If you are running in a CI environment with a DNS that blocks external IPs, try setting SFDX_DISABLE_DNS_CHECK=true_

The Domain is: https://bosch-bbm--cis.my.salesforce.com/

**Comment by yippie** [comment]
I have been getting this a lot lately also. running `sfdx force:org:list --clean` fixes it temporarily and I can push again but then after a bit it fails again saying org not found and half of my orgs, including prod and sandbox connections, say "Unknown"

These are all orgs that have existed for days or months.

**Comment by JuliWaver** [comment]
@yippie Have you tried to set a system variable SFDX_DISABLE_DNS_CHECK=true?

**Comment by JuliWaver** [comment]
I have updated my sfdx version to 7.91.0 today and set user system variable to SFDX_DISABLE_DNS_CHECK=true to solve unknown org issue and I have now a new error message if I try to deploy/validate. 


**Used command:** sfdx force:source:deploy --verbose --targetusername julikaDev2 -p force-app -c

**Error message:**
Using specified username julika.weller@bosch-bbm.org.julikadev2

*** Deploying with REST ***
TypeError: Cannot read property 'message' of undefined
    at Function.wrap (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\@salesforce\core\lib\sfdxError.js:171:45)
    at Request._callback (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\salesforce-alm\dist\lib\core\force.js:587:41)
    at self.callback (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\request\request.js:185:22)
    at Request.emit (events.js:327:22)
    at Request.onRequestError (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.onError (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)


@peternhale Do you know this error?

**Comment by peternhale** [comment]
@JuliWaver this appears to be a new issue. I created issue #923 for tracking.

**Comment by JuliWaver** [comment]
my issue was solved with sytsem variable SFDX_REST_DEPLOY=false

**Comment by hatorijobs** [comment]
Hi there,
I am having the same issue.
But I solved it using the following command.

sfdx force:config:set restDeploy=false

sfdx force:config:list

=== List Config
Name             Value  Location
───────────────  ─────  ────────
defaultusername  hoge   Local
restDeploy       false  Local


Thank you!! Good luck!!
