### ISSUE TITLE
Running force:source:deploy is failing with "Cannot read property 'message' of undefined"

### ISSUE THREAD

**Issue by peternhale** [forcedotcom/cli#923]
I have updated my sfdx version to 7.91.0 today and set user system variable to SFDX_DISABLE_DNS_CHECK=true to solve unknown org issue and I have now a new error message if I try to deploy/validate. 

**Used command:** sfdx force:source:deploy --verbose --targetusername julikaDev2 -p force-app -c

**Error message:**
Using specified username julika.weller@bosch-bbm.org.julikadev2

*** Deploying with REST ***
TypeError: Cannot read property 'message' of undefined
    at Function.wrap (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\@salesforce\core\lib\sfdxError.js:171:45)
    at Request._callback (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\salesforce-alm\dist\lib\core\force.js:587:41)
    at self.callback (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\request\request.js:185:22)
    at Request.emit (events.js:327:22)
    at Request.onRequestError (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.onError (C:\Users\WJL7FE\AppData\Local\sfdx\client\7.91.0-6a6ed69ebe\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

@peternhale Do you know this error?

_Originally posted by @JuliWaver in https://github.com/forcedotcom/cli/issues/887#issuecomment-800859635_

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9018958](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008aEJOIA2/view)

**Comment by JuliWaver** [comment]
@peternhale I was able to solve it with system variable SFDX_REST_DEPLOY=false

https://github.com/forcedotcom/cli/tree/main/releasenotes#5122-march-4-2021---cli-7902

CHANGE: As of v51, all force:source and force:mdapi commands use REST API by default to deploy. Previously they used SOAP API by default. Set the restDeploy config value or SFDX_REST_DEPLOY environment variable to false to switch back to SOAP.

**Comment by mshanemc** [comment]
solved by switching the whole CLI back to soap https://github.com/forcedotcom/cli/issues/942
