### ISSUE TITLE
SfdxError sfdx force:source:deploy

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#950]
### Summary

Im trying to push some metadata using `sfdx force:source:deploy` and Im receiving this response from sfdx. I ran this several times, and I always get the same response, so it is not a service instability.

````shell
SfdxError:
    at Object.spawn (C:\Users\oricil\workspace\sfdx-plugins\src\lib\utils.ts:12:17)
    at C:\Users\oricil\workspace\sfdx-plugins\src\commands\hpe\community\install.ts:69:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Org.run (C:\Users\oricil\workspace\sfdx-plugins\src\commands\hpe\community\install.ts:59:5)
    at Org._run (C:\Users\oricil\workspace\sfdx-plugins\node_modules\@salesforce\command\lib\sfdxCommand.js:91:40)
    at Config.runCommand (C:\Users\oricil\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at Main.run (C:\Users\oricil\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at Main._run (C:\Users\oricil\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\command.js:43:20)       
    at Object.run (C:\Users\oricil\AppData\Roaming\npm\node_modules\sfdx-cli\dist\cli.js:114:21)
Outer stack:
    at Function.wrap (C:\Users\oricil\workspace\sfdx-plugins\node_modules\@salesforce\core\lib\sfdxError.js:151:27)
    at ChildProcess.<anonymous> (C:\Users\oricil\workspace\sfdx-plugins\src\lib\utils.ts:49:37)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  cause: undefined,
  name: 'Error',
  actions: undefined,
  exitCode: 1,
  data: {
    status: 1,
    name: 'SfdxError',
    message: '\n' +
      '<html>\n' +
      '<body>\n' +
      '\n' +
      '<table cellspacing=10>\n' +
      '    <tr>\n' +
      '        <td><span style="font-weight: bold; font-size: 12pt;">Illegal Request</span></td>\n' +
      '    </tr>\n' +
      '    <tr>\n' +
      '        <td>You have sent us an Illegal URL or an improperly formatted request. \n' +
      '        </td>\n' +
      '    </tr>\n' +
      '    <tr>\n' +
      '        <td>\n' +
      '            \n' +
      '        </td>\n' +
      '    </tr>\n' +
      '</table>\n' +
      '\n' +
      '\n' +
      '\n' +
      '<!-- Body events -->\n' +
      '<script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>\n' +
      '\t\t\t\n' +
      '</body>\n' +
      '</html>\n' +
      '\n' +
      '\n' +
      '<!--\n' +
      '...................................................................................................\n' +
      '...................................................................................................\n' +
      '...................................................................................................\n' +
      '...................................................................................................\n' +
      '-->\n',
    exitCode: 1,
    commandName: 'SourcePushCommand',
    stack: 'SfdxError: \n' +
      '<html>\n' +
      '<body>\n' +
      '\n' +
      '<table cellspacing=10>\n' +
      '    <tr>\n' +
      '        <td><span style="font-weight: bold; font-size: 12pt;">Illegal Request</span></td>\n' +
      '    </tr>\n' +
      '    <tr>\n' +
      '        <td>You have sent us an Illegal URL or an improperly formatted request. \n' +
      '        </td>\n' +
      '    </tr>\n' +
      '    <tr>\n' +
      '        <td>\n' +
      '            \n' +
      '        </td>\n' +
      '    </tr>\n' +
      '</table>\n' +
      '\n' +
      '\n' +
      '\n' +
      '<!-- Body events -->\n' +
      '<script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>\n' +
      '\t\t\t\n' +
      '</body>\n' +
      '</html>\n' +
      '\n' +
      '\n' +
      '<!--\n' +
      '...................................................................................................\n' +
      '...................................................................................................\n' +
      '...................................................................................................\n' +
      '...................................................................................................\n' +
      '-->\n' +
      '\n' +
      '    at Function.wrap (C:\\Users\\oricil\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:169:20)\n' +
      '    at Request._callback (C:\\Users\\oricil\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\core\\force.js:587:41)\n' +
      '    at Request.self.callback (C:\\Users\\oricil\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\request\\request.js:185:22)\n' +
      '    at Request.emit (events.js:210:5)\n' +
      '    at Request.<anonymous> (C:\\Users\\oricil\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\request\\request.js:1154:10)\n' +
      '    at Request.emit (events.js:210:5)\n' +
      '    at IncomingMessage.<anonymous> (C:\\Users\\oricil\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\request\\request.js:1076:12)\n' +
      '    at Object.onceWrapper (events.js:299:28)\n' +
      '    at IncomingMessage.emit (events.js:215:7)\n' +
      '    at endReadableNT (_stream_readable.js:1184:12)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:80:21)',
    warnings: []
  }
}
````
 
### Steps To Reproduce:

I can share a repository to the responsible of this feature so you can debug what is happening.

### Expected result

`sfdx force:source:deploy` should work, and if not, at least, tell me what is the error

### Actual result

`sfdx force:source:deploy` is not working

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):  sfdx-cli/7.92.0 win32-x64 node-v12.13.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

λ sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
generator 1.1.5 (core)
hpe-sfdx-plugins 0.3.10 (link) C:\Users\oricil\workspace\sfdx-plugins
salesforcedx 51.4.0 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ org 1.3.3 (core)
├─ user 1.2.0 (core)
├─ apex 0.1.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.11 (core)
├─ salesforce-alm 51.4.0 (core)
└─ templates 51.3.0 (core)
sfdx-cli 7.92.0 (core)
telemetry 1.1.1 (core)

**OS and version**: Windows 10

**Comment by AllanOricil** [comment]
Using the solution from https://github.com/forcedotcom/cli/issues/942 fixed my problem.
