### ISSUE TITLE
Warning: Accessing non-existent property [prop] of module exports inside circular dependency

### ISSUE THREAD

**Issue by fenixjke** [forcedotcom/cli#957]
### Summary

When trying to use sfdx command in terminal a bunch of warnings are showing.

### Additional information

<img width="780" alt="warning" src="https://user-images.githubusercontent.com/20062691/113741648-89111f80-970a-11eb-8eb0-9ee514da60f0.png">

**SFDX CLI Version**: sfdx-cli/7.94.3-a4e7c7955b darwin-x64 node-v14.15.4

**OS and version**: macOS Big Sur 11.2.3

**Comment by peternhale** [comment]
@fenixjke Thank for reporting this issue. May I ask a favor. Run the command again using NODE_OPTIONS
```
export NODE_OPTIONS='--trace-warnings'
sfdx
```
and post those results.

I do not see these warnings on Mac, still on Catalina.

**Comment by fenixjke** [comment]
@peternhale 
(node:79199) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object._register [as register] (/Users/u/.local/share/sfdx/node_modules/shelljs/src/common.js:453:12)
    at Object.<anonymous> (/Users/u/.local/share/sfdx/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (/Users/u/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/u/.local/share/sfdx/client/7.94.3-a4e7c7955b/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)

**Comment by mshanemc** [comment]
did this go away on more recent versions?

**Comment by fenixjke** [comment]
@mshanemc Cannot reproduce it on 7.129
